/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// opamp_opamp1_csr_v1: OPAMP1_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp1_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp1_tcmr_v1: OPAMP1_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp1_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

// opamp_opamp2_csr_v1: OPAMP2_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp2_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp2_tcmr_v1: OPAMP2_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp2_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

// opamp_opamp3_csr_v1: OPAMP3_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp3_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp3_tcmr_v1: OPAMP3_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp3_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

// opamp_opamp4_csr_v1: OPAMP4_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp4_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp4_tcmr_v1: OPAMP4_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp4_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

// opamp_opamp5_csr_v1: OPAMP5_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp5_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp5_tcmr_v1: OPAMP5_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp5_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

// opamp_opamp6_csr_v1: OPAMP6_CSR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp6_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"calout", bool, 30, 30>,
               groov::field<"reserved1", bool, 29, 29, common::access::ro>,
               groov::field<"trimoffsetn", std::uint8_t, 28, 24>,
               groov::field<"trimoffsetp", std::uint8_t, 23, 19>,
               groov::field<"pga_gain", std::uint8_t, 18, 14>,
               groov::field<"calsel", std::uint8_t, 13, 12>,
               groov::field<"calon", bool, 11, 11>,
               groov::field<"reserved0", std::uint8_t, 10, 9, common::access::ro>,
               groov::field<"opaintoen", common::bit_enable, 8, 8>,
               groov::field<"opahsm", bool, 7, 7>,
               groov::field<"vm_sel", std::uint8_t, 6, 5>,
               groov::field<"usertrim", bool, 4, 4>,
               groov::field<"vp_sel", std::uint8_t, 3, 2>,
               groov::field<"force_vp", bool, 1, 1>,
               groov::field<"opaen", common::bit_enable, 0, 0>>;

// opamp_opamp6_tcmr_v1: OPAMP6_TCMR
// Used by: OPAMP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using opamp_opamp6_tcmr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lock", common::bit_locked, 31, 31>,
               groov::field<"reserved0", std::uint32_t, 30, 6, common::access::ro>,
               groov::field<"t20cm_en", common::bit_enable, 5, 5>,
               groov::field<"t8cm_en", common::bit_enable, 4, 4>,
               groov::field<"t1cm_en", common::bit_enable, 3, 3>,
               groov::field<"vps_sel", std::uint8_t, 2, 1>,
               groov::field<"vms_sel", bool, 0, 0>>;

} // namespace stm32::regs
