/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/fmc.hpp"
namespace mcu::stm32::stm32h7s {
#include "../../../common/peripherals/fmc_5b4f346847e0.inc"
} // namespace mcu::stm32::stm32h7s
