/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/jpeg.hpp"
namespace mcu::stm32::stm32h755_cm7 {
#include "../../common/peripherals/jpeg_fc622f49ddc7.inc"
} // namespace mcu::stm32::stm32h755_cm7
