/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/bsec.hpp"
namespace erworks::stm32::stm32n657 {
#include "../../../common/peripherals/bsec_344755fb7ebd.inc"
} // namespace erworks::stm32::stm32n657
