/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/access.hpp"
#include "../../common/bittypes.hpp"
namespace erworks::stm32::stm32wba54 {
namespace regs {

// rcc_rcc_ahb1enr_v1: RCC_AHB1ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb1enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sram1en", common::bit_enable, 31, 31>,
               groov::field<"reserved4", std::uint8_t, 30, 25, common::access::ro>,
               groov::field<"gtzc1en", common::bit_enable, 24, 24>,
               groov::field<"reserved3", std::uint8_t, 23, 18, common::access::ro>,
               groov::field<"ramcfgen", common::bit_enable, 17, 17>,
               groov::field<"tscen", common::bit_enable, 16, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 13, common::access::ro>,
               groov::field<"crcen", common::bit_enable, 12, 12>,
               groov::field<"reserved1", std::uint8_t, 11, 9, common::access::ro>,
               groov::field<"flashen", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"gpdma1en", common::bit_enable, 0, 0>>;

// rcc_rcc_ahb1rstr_v1: RCC_AHB1RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb1rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"tscrst", common::bit_reset, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 13, common::access::ro>,
               groov::field<"crcrst", common::bit_reset, 12, 12>,
               groov::field<"reserved0", std::uint16_t, 11, 1, common::access::ro>,
               groov::field<"gpdma1rst", common::bit_reset, 0, 0>>;

// rcc_rcc_ahb1smenr_v1: RCC_AHB1SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb1smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sram1smen", common::bit_enable, 31, 31>,
               groov::field<"reserved5", bool, 30, 30, common::access::ro>,
               groov::field<"icachesmen", common::bit_enable, 29, 29>,
               groov::field<"reserved4", std::uint8_t, 28, 25, common::access::ro>,
               groov::field<"gtzc1smen", common::bit_enable, 24, 24>,
               groov::field<"reserved3", std::uint8_t, 23, 18, common::access::ro>,
               groov::field<"ramcfgsmen", common::bit_enable, 17, 17>,
               groov::field<"tscsmen", common::bit_enable, 16, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 13, common::access::ro>,
               groov::field<"crcsmen", common::bit_enable, 12, 12>,
               groov::field<"reserved1", std::uint8_t, 11, 9, common::access::ro>,
               groov::field<"flashsmen", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"gpdma1smen", common::bit_enable, 0, 0>>;

// rcc_rcc_ahb2enr_v1: RCC_AHB2ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb2enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", bool, 31, 31, common::access::ro>,
               groov::field<"sram2en", common::bit_enable, 30, 30>,
               groov::field<"reserved2", std::uint8_t, 29, 22, common::access::ro>,
               groov::field<"pkaen", common::bit_enable, 21, 21>,
               groov::field<"hsemen", common::bit_enable, 20, 20>,
               groov::field<"saesen", common::bit_enable, 19, 19>,
               groov::field<"rngen", common::bit_enable, 18, 18>,
               groov::field<"hashen", common::bit_enable, 17, 17>,
               groov::field<"aesen", common::bit_enable, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"gpiohen", common::bit_enable, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 3, common::access::ro>,
               groov::field<"gpiocen", common::bit_enable, 2, 2>,
               groov::field<"gpioben", common::bit_enable, 1, 1>,
               groov::field<"gpioaen", common::bit_enable, 0, 0>>;

// rcc_rcc_ahb2rstr_v1: RCC_AHB2RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb2rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"pkarst", common::bit_reset, 21, 21>,
               groov::field<"hsemrst", common::bit_reset, 20, 20>,
               groov::field<"saesrst", common::bit_reset, 19, 19>,
               groov::field<"rngrst", common::bit_reset, 18, 18>,
               groov::field<"hashrst", common::bit_reset, 17, 17>,
               groov::field<"aesrst", common::bit_reset, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"gpiohrst", common::bit_reset, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 3, common::access::ro>,
               groov::field<"gpiocrst", common::bit_reset, 2, 2>,
               groov::field<"gpiobrst", common::bit_reset, 1, 1>,
               groov::field<"gpioarst", common::bit_reset, 0, 0>>;

// rcc_rcc_ahb2smenr_v1: RCC_AHB2SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb2smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", bool, 31, 31, common::access::ro>,
               groov::field<"sram2smen", common::bit_enable, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 22, common::access::ro>,
               groov::field<"pkasmen", common::bit_enable, 21, 21>,
               groov::field<"reserved2", bool, 20, 20, common::access::ro>,
               groov::field<"saessmen", common::bit_enable, 19, 19>,
               groov::field<"rngsmen", common::bit_enable, 18, 18>,
               groov::field<"hashsmen", common::bit_enable, 17, 17>,
               groov::field<"aessmen", common::bit_enable, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"gpiohsmen", common::bit_enable, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 3, common::access::ro>,
               groov::field<"gpiocsmen", common::bit_enable, 2, 2>,
               groov::field<"gpiobsmen", common::bit_enable, 1, 1>,
               groov::field<"gpioasmen", common::bit_enable, 0, 0>>;

// rcc_rcc_ahb4enr_v1: RCC_AHB4ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb4enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"adc4en", common::bit_enable, 5, 5>,
               groov::field<"reserved1", std::uint8_t, 4, 3, common::access::ro>,
               groov::field<"pwren", common::bit_enable, 2, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// rcc_rcc_ahb4rstr_v1: RCC_AHB4RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb4rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"adc4rst", common::bit_reset, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 0, common::access::ro>>;

// rcc_rcc_ahb4smenr_v1: RCC_AHB4SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb4smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"adc4smen", common::bit_enable, 5, 5>,
               groov::field<"reserved1", std::uint8_t, 4, 3, common::access::ro>,
               groov::field<"pwrsmen", common::bit_enable, 2, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// rcc_rcc_ahb5enr_v1: RCC_AHB5ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb5enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"radioen", common::bit_enable, 0, 0>>;

// rcc_rcc_ahb5rstr_v1: RCC_AHB5RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb5rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"radiorst", common::bit_reset, 0, 0>>;

// rcc_rcc_ahb5smenr_v1: RCC_AHB5SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ahb5smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"radiosmen", common::bit_enable, 0, 0>>;

// rcc_rcc_apb1enr1_v1: RCC_APB1ENR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1enr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"i2c1en", common::bit_enable, 21, 21>,
               groov::field<"reserved2", std::uint8_t, 20, 18, common::access::ro>,
               groov::field<"usart2en", common::bit_enable, 17, 17>,
               groov::field<"reserved1", std::uint8_t, 16, 12, common::access::ro>,
               groov::field<"wwdgen", common::bit_enable, 11, 11>,
               groov::field<"reserved0", std::uint16_t, 10, 2, common::access::ro>,
               groov::field<"tim3en", common::bit_enable, 1, 1>,
               groov::field<"tim2en", common::bit_enable, 0, 0>>;

// rcc_rcc_apb1enr2_v1: RCC_APB1ENR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1enr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"lptim2en", common::bit_enable, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 0, common::access::ro>>;

// rcc_rcc_apb1rstr1_v1: RCC_APB1RSTR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1rstr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"i2c1rst", common::bit_reset, 21, 21>,
               groov::field<"reserved1", std::uint8_t, 20, 18, common::access::ro>,
               groov::field<"usart2rst", common::bit_reset, 17, 17>,
               groov::field<"reserved0", std::uint16_t, 16, 2, common::access::ro>,
               groov::field<"tim3rst", common::bit_reset, 1, 1>,
               groov::field<"tim2rst", common::bit_reset, 0, 0>>;

// rcc_rcc_apb1rstr2_v1: RCC_APB1RSTR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1rstr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"lptim2rst", common::bit_reset, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 0, common::access::ro>>;

// rcc_rcc_apb1smenr1_v1: RCC_APB1SMENR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1smenr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"i2c1smen", common::bit_enable, 21, 21>,
               groov::field<"reserved2", std::uint8_t, 20, 18, common::access::ro>,
               groov::field<"usart2smen", common::bit_enable, 17, 17>,
               groov::field<"reserved1", std::uint8_t, 16, 12, common::access::ro>,
               groov::field<"wwdgsmen", common::bit_enable, 11, 11>,
               groov::field<"reserved0", std::uint16_t, 10, 2, common::access::ro>,
               groov::field<"tim3smen", common::bit_enable, 1, 1>,
               groov::field<"tim2smen", common::bit_enable, 0, 0>>;

// rcc_rcc_apb1smenr2_v1: RCC_APB1SMENR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb1smenr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, common::access::ro>,
               groov::field<"lptim2smen", common::bit_enable, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 0, common::access::ro>>;

// rcc_rcc_apb2enr_v1: RCC_APB2ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb2enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"tim17en", common::bit_enable, 18, 18>,
               groov::field<"tim16en", common::bit_enable, 17, 17>,
               groov::field<"reserved2", std::uint8_t, 16, 15, common::access::ro>,
               groov::field<"usart1en", common::bit_enable, 14, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"spi1en", common::bit_enable, 12, 12>,
               groov::field<"tim1en", common::bit_enable, 11, 11>,
               groov::field<"reserved0", std::uint16_t, 10, 0, common::access::ro>>;

// rcc_rcc_apb2rstr_v1: RCC_APB2RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb2rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"tim17rst", common::bit_reset, 18, 18>,
               groov::field<"tim16rst", common::bit_reset, 17, 17>,
               groov::field<"reserved2", std::uint8_t, 16, 15, common::access::ro>,
               groov::field<"usart1rst", common::bit_reset, 14, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"spi1rst", common::bit_reset, 12, 12>,
               groov::field<"tim1rst", common::bit_reset, 11, 11>,
               groov::field<"reserved0", std::uint16_t, 10, 0, common::access::ro>>;

// rcc_rcc_apb2smenr_v1: RCC_APB2SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb2smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"tim17smen", common::bit_enable, 18, 18>,
               groov::field<"tim16smen", common::bit_enable, 17, 17>,
               groov::field<"reserved2", std::uint8_t, 16, 15, common::access::ro>,
               groov::field<"usart1smen", common::bit_enable, 14, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"spi1smen", common::bit_enable, 12, 12>,
               groov::field<"tim1smen", common::bit_enable, 11, 11>,
               groov::field<"reserved0", std::uint16_t, 10, 0, common::access::ro>>;

// rcc_rcc_apb7enr_v1: RCC_APB7ENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb7enr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"rtcapben", common::bit_enable, 21, 21>,
               groov::field<"reserved3", std::uint16_t, 20, 12, common::access::ro>,
               groov::field<"lptim1en", common::bit_enable, 11, 11>,
               groov::field<"reserved2", std::uint8_t, 10, 8, common::access::ro>,
               groov::field<"i2c3en", common::bit_enable, 7, 7>,
               groov::field<"lpuart1en", common::bit_enable, 6, 6>,
               groov::field<"spi3en", common::bit_enable, 5, 5>,
               groov::field<"reserved1", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"syscfgen", common::bit_enable, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// rcc_rcc_apb7rstr_v1: RCC_APB7RSTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb7rstr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"lptim1rst", common::bit_reset, 11, 11>,
               groov::field<"reserved2", std::uint8_t, 10, 8, common::access::ro>,
               groov::field<"i2c3rst", common::bit_reset, 7, 7>,
               groov::field<"lpuart1rst", common::bit_reset, 6, 6>,
               groov::field<"spi3rst", common::bit_reset, 5, 5>,
               groov::field<"reserved1", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"syscfgrst", common::bit_reset, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// rcc_rcc_apb7smenr_v1: RCC_APB7SMENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_apb7smenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"rtcapbsmen", common::bit_enable, 21, 21>,
               groov::field<"reserved3", std::uint16_t, 20, 12, common::access::ro>,
               groov::field<"lptim1smen", common::bit_enable, 11, 11>,
               groov::field<"reserved2", std::uint8_t, 10, 8, common::access::ro>,
               groov::field<"i2c3smen", common::bit_enable, 7, 7>,
               groov::field<"lpuart1smen", common::bit_enable, 6, 6>,
               groov::field<"spi3smen", common::bit_enable, 5, 5>,
               groov::field<"reserved1", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"syscfgsmen", common::bit_enable, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// rcc_rcc_bdcr1_v1: RCC_BDCR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_bdcr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", bool, 31, 31, common::access::ro>,
               groov::field<"lsi2rdy", common::bit_ready, 30, 30, common::access::ro>,
               groov::field<"lsi2on", bool, 29, 29>,
               groov::field<"lsi1prediv", bool, 28, 28>,
               groov::field<"lsi1rdy", common::bit_ready, 27, 27, common::access::ro>,
               groov::field<"lsi1on", bool, 26, 26>,
               groov::field<"lscosel", bool, 25, 25>,
               groov::field<"lscoen", common::bit_enable, 24, 24>,
               groov::field<"reserved3", std::uint8_t, 23, 20, common::access::ro>,
               groov::field<"radiostsel", std::uint8_t, 19, 18>,
               groov::field<"reserved2", bool, 17, 17, common::access::ro>,
               groov::field<"bdrst", common::bit_reset, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"lsetrim", std::uint8_t, 14, 13>,
               groov::field<"lsegfon", bool, 12, 12>,
               groov::field<"lsesysrdy", common::bit_ready, 11, 11, common::access::ro>,
               groov::field<"reserved0", bool, 10, 10, common::access::ro>,
               groov::field<"rtcsel", std::uint8_t, 9, 8>,
               groov::field<"lsesysen", common::bit_enable, 7, 7>,
               groov::field<"lsecssd", bool, 6, 6, common::access::ro>,
               groov::field<"lsecsson", bool, 5, 5>,
               groov::field<"lsedrv", std::uint8_t, 4, 3>,
               groov::field<"lsebyp", bool, 2, 2>,
               groov::field<"lserdy", common::bit_ready, 1, 1, common::access::ro>,
               groov::field<"lseon", bool, 0, 0>>;

// rcc_rcc_ccipr1_v1: RCC_CCIPR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ccipr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"timicsel", bool, 31, 31>,
               groov::field<"reserved2", std::uint8_t, 30, 24, common::access::ro>,
               groov::field<"systicksel", std::uint8_t, 23, 22>,
               groov::field<"spi1sel", std::uint8_t, 21, 20>,
               groov::field<"lptim2sel", std::uint8_t, 19, 18>,
               groov::field<"reserved1", std::uint8_t, 17, 12, common::access::ro>,
               groov::field<"i2c1sel", std::uint8_t, 11, 10>,
               groov::field<"reserved0", std::uint8_t, 9, 4, common::access::ro>,
               groov::field<"usart2sel", std::uint8_t, 3, 2>,
               groov::field<"usart1sel", std::uint8_t, 1, 0>>;

// rcc_rcc_ccipr2_v1: RCC_CCIPR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ccipr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 14, common::access::ro>,
               groov::field<"rngsel", std::uint8_t, 13, 12>,
               groov::field<"reserved0", std::uint16_t, 11, 0, common::access::ro>>;

// rcc_rcc_ccipr3_v1: RCC_CCIPR3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ccipr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"adcsel", std::uint8_t, 14, 12>,
               groov::field<"lptim1sel", std::uint8_t, 11, 10>,
               groov::field<"reserved2", std::uint8_t, 9, 8, common::access::ro>,
               groov::field<"i2c3sel", std::uint8_t, 7, 6>,
               groov::field<"reserved1", bool, 5, 5, common::access::ro>,
               groov::field<"spi3sel", std::uint8_t, 4, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"lpuart1sel", std::uint8_t, 1, 0>>;

// rcc_rcc_cfgr1_v1: RCC_CFGR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cfgr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", bool, 31, 31, common::access::ro>,
               groov::field<"mcopre", std::uint8_t, 30, 28>,
               groov::field<"mcosel", std::uint8_t, 27, 24>,
               groov::field<"reserved0", std::uint32_t, 23, 4, common::access::ro>,
               groov::field<"sws", std::uint8_t, 3, 2, common::access::ro>,
               groov::field<"sw", std::uint8_t, 1, 0>>;

// rcc_rcc_cfgr2_v1: RCC_CFGR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cfgr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 11, common::access::ro>,
               groov::field<"ppre2", std::uint8_t, 10, 8>,
               groov::field<"reserved1", bool, 7, 7, common::access::ro>,
               groov::field<"ppre1", std::uint8_t, 6, 4>,
               groov::field<"reserved0", bool, 3, 3, common::access::ro>,
               groov::field<"hpre", std::uint8_t, 2, 0>>;

// rcc_rcc_cfgr3_v1: RCC_CFGR3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cfgr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 7, common::access::ro>,
               groov::field<"ppre7", std::uint8_t, 6, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 0, common::access::ro>>;

// rcc_rcc_cfgr4_v1: RCC_CFGR4
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cfgr4_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 5, common::access::ro>,
               groov::field<"hdiv5", bool, 4, 4>,
               groov::field<"reserved0", bool, 3, 3, common::access::ro>,
               groov::field<"hpre5", std::uint8_t, 2, 0>>;

// rcc_rcc_cicr_v1: RCC_CICR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cicr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 11, common::access::ro>,
               groov::field<"hsecssc", bool, 10, 10, common::access::wo>,
               groov::field<"reserved2", std::uint8_t, 9, 7, common::access::ro>,
               groov::field<"pll1rdyc", common::bit_ready, 6, 6, common::access::wo>,
               groov::field<"reserved1", bool, 5, 5, common::access::ro>,
               groov::field<"hserdyc", common::bit_ready, 4, 4, common::access::wo>,
               groov::field<"hsirdyc", common::bit_ready, 3, 3, common::access::wo>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"lserdyc", common::bit_ready, 1, 1, common::access::wo>,
               groov::field<"lsi1rdyc", common::bit_ready, 0, 0, common::access::wo>>;

// rcc_rcc_cier_v1: RCC_CIER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 7, common::access::ro>,
               groov::field<"pll1rdyie", common::bit_ready, 6, 6>,
               groov::field<"reserved1", bool, 5, 5, common::access::ro>,
               groov::field<"hserdyie", common::bit_ready, 4, 4>,
               groov::field<"hsirdyie", common::bit_ready, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"lserdyie", common::bit_ready, 1, 1>,
               groov::field<"lsi1rdyie", common::bit_ready, 0, 0>>;

// rcc_rcc_cifr_v1: RCC_CIFR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cifr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 11, common::access::ro>,
               groov::field<"hsecssf", bool, 10, 10, common::access::ro>,
               groov::field<"reserved2", std::uint8_t, 9, 7, common::access::ro>,
               groov::field<"pll1rdyf", common::bit_ready, 6, 6, common::access::ro>,
               groov::field<"reserved1", bool, 5, 5, common::access::ro>,
               groov::field<"hserdyf", common::bit_ready, 4, 4, common::access::ro>,
               groov::field<"hsirdyf", common::bit_ready, 3, 3, common::access::ro>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"lserdyf", common::bit_ready, 1, 1, common::access::ro>,
               groov::field<"lsi1rdyf", common::bit_ready, 0, 0, common::access::ro>>;

// rcc_rcc_cr_v1: RCC_CR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", std::uint8_t, 31, 26, common::access::ro>,
               groov::field<"pll1rdy", common::bit_ready, 25, 25, common::access::ro>,
               groov::field<"pll1on", bool, 24, 24>,
               groov::field<"reserved3", std::uint8_t, 23, 21, common::access::ro>,
               groov::field<"hsepre", bool, 20, 20>,
               groov::field<"hsecsson", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"hserdy", common::bit_ready, 17, 17, common::access::ro>,
               groov::field<"hseon", bool, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 11, common::access::ro>,
               groov::field<"hsirdy", common::bit_ready, 10, 10, common::access::ro>,
               groov::field<"hsikeron", bool, 9, 9>,
               groov::field<"hsion", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// rcc_rcc_csr_v1: RCC_CSR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_csr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lpwrrstf", bool, 31, 31, common::access::ro>,
               groov::field<"wwdgrstf", bool, 30, 30, common::access::ro>,
               groov::field<"iwdgrstf", bool, 29, 29, common::access::ro>,
               groov::field<"sftrstf", bool, 28, 28, common::access::ro>,
               groov::field<"borrstf", bool, 27, 27, common::access::ro>,
               groov::field<"pinrstf", bool, 26, 26, common::access::ro>,
               groov::field<"oblrstf", bool, 25, 25, common::access::ro>,
               groov::field<"reserved1", bool, 24, 24, common::access::ro>,
               groov::field<"rmvf", bool, 23, 23>,
               groov::field<"reserved0", std::uint32_t, 22, 0, common::access::ro>>;

// rcc_rcc_ecscr1_v1: RCC_ECSCR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_ecscr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"hsetrim", std::uint8_t, 21, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// rcc_rcc_icscr3_v1: RCC_ICSCR3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_icscr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 21, common::access::ro>,
               groov::field<"hsitrim", std::uint8_t, 20, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 12, common::access::ro>,
               groov::field<"hsical", std::uint16_t, 11, 0, common::access::ro>>;

// rcc_rcc_pll1cfgr_v1: RCC_PLL1CFGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_pll1cfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 23, common::access::ro>,
               groov::field<"pll1rclkprerdy", common::bit_ready, 22, 22, common::access::ro>,
               groov::field<"pll1rclkprestep", bool, 21, 21>,
               groov::field<"pll1rclkpre", bool, 20, 20>,
               groov::field<"reserved2", bool, 19, 19, common::access::ro>,
               groov::field<"pll1ren", common::bit_enable, 18, 18>,
               groov::field<"pll1qen", common::bit_enable, 17, 17>,
               groov::field<"pll1pen", common::bit_enable, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 11, common::access::ro>,
               groov::field<"pll1m", std::uint8_t, 10, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"pll1fracen", common::bit_enable, 4, 4>,
               groov::field<"pll1rge", std::uint8_t, 3, 2>,
               groov::field<"pll1src", std::uint8_t, 1, 0>>;

// rcc_rcc_pll1divr_v1: RCC_PLL1DIVR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_pll1divr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", bool, 31, 31, common::access::ro>,
               groov::field<"pll1r", std::uint8_t, 30, 24>,
               groov::field<"reserved0", bool, 23, 23, common::access::ro>,
               groov::field<"pll1q", std::uint8_t, 22, 16>,
               groov::field<"pll1p", std::uint8_t, 15, 9>,
               groov::field<"pll1n", std::uint16_t, 8, 0>>;

// rcc_rcc_pll1fracr_v1: RCC_PLL1FRACR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_pll1fracr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"pll1fracn", std::uint16_t, 15, 3>,
               groov::field<"reserved0", std::uint8_t, 2, 0, common::access::ro>>;

// rcc_rcc_radioenr_v1: RCC_RADIOENR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_radioenr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 18, common::access::ro>,
               groov::field<"radioclkrdy", common::bit_ready, 17, 17, common::access::ro>,
               groov::field<"stradioclkon", bool, 16, 16>,
               groov::field<"reserved1", std::uint16_t, 15, 2, common::access::ro>,
               groov::field<"bbclken", common::bit_enable, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// rcc_rcc_seccfgr_v1: RCC_SECCFGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rcc_rcc_seccfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 13, common::access::ro>,
               groov::field<"rmvfsec", bool, 12, 12>,
               groov::field<"reserved1", std::uint8_t, 11, 8, common::access::ro>,
               groov::field<"pll1sec", bool, 7, 7>,
               groov::field<"prescsec", bool, 6, 6>,
               groov::field<"sysclksec", bool, 5, 5>,
               groov::field<"lsesec", bool, 4, 4>,
               groov::field<"lsisec", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"hsesec", bool, 1, 1>,
               groov::field<"hsisec", bool, 0, 0>>;

} // namespace regs

namespace rccx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cr_tt = regs::rcc_rcc_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_icscr3_tt = regs::rcc_rcc_icscr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cfgr1_tt = regs::rcc_rcc_cfgr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cfgr2_tt = regs::rcc_rcc_cfgr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cfgr3_tt = regs::rcc_rcc_cfgr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_pll1cfgr_tt = regs::rcc_rcc_pll1cfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_pll1divr_tt = regs::rcc_rcc_pll1divr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_pll1fracr_tt = regs::rcc_rcc_pll1fracr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cier_tt = regs::rcc_rcc_cier_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cifr_tt = regs::rcc_rcc_cifr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cicr_tt = regs::rcc_rcc_cicr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb1rstr_tt = regs::rcc_rcc_ahb1rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb2rstr_tt = regs::rcc_rcc_ahb2rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb4rstr_tt = regs::rcc_rcc_ahb4rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb5rstr_tt = regs::rcc_rcc_ahb5rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1rstr1_tt = regs::rcc_rcc_apb1rstr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1rstr2_tt = regs::rcc_rcc_apb1rstr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb2rstr_tt = regs::rcc_rcc_apb2rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb7rstr_tt = regs::rcc_rcc_apb7rstr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb1enr_tt = regs::rcc_rcc_ahb1enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb2enr_tt = regs::rcc_rcc_ahb2enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb4enr_tt = regs::rcc_rcc_ahb4enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb5enr_tt = regs::rcc_rcc_ahb5enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1enr1_tt = regs::rcc_rcc_apb1enr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1enr2_tt = regs::rcc_rcc_apb1enr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb2enr_tt = regs::rcc_rcc_apb2enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb7enr_tt = regs::rcc_rcc_apb7enr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb1smenr_tt = regs::rcc_rcc_ahb1smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb2smenr_tt = regs::rcc_rcc_ahb2smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb4smenr_tt = regs::rcc_rcc_ahb4smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ahb5smenr_tt = regs::rcc_rcc_ahb5smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1smenr1_tt = regs::rcc_rcc_apb1smenr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb1smenr2_tt = regs::rcc_rcc_apb1smenr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb2smenr_tt = regs::rcc_rcc_apb2smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_apb7smenr_tt = regs::rcc_rcc_apb7smenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ccipr1_tt = regs::rcc_rcc_ccipr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ccipr2_tt = regs::rcc_rcc_ccipr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ccipr3_tt = regs::rcc_rcc_ccipr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_bdcr1_tt = regs::rcc_rcc_bdcr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_csr_tt = regs::rcc_rcc_csr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_seccfgr_tt = regs::rcc_rcc_seccfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_privcfgr_tt = regs::flash_flash_prifcfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_cfgr4_tt = regs::rcc_rcc_cfgr4_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_radioenr_tt = regs::rcc_rcc_radioenr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rcc_ecscr1_tt = regs::rcc_rcc_ecscr1_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using rccx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 rcc_cr_tt<"rcc_cr", baseaddress, 0x0>,
                 rcc_icscr3_tt<"rcc_icscr3", baseaddress, 0x10>,
                 rcc_cfgr1_tt<"rcc_cfgr1", baseaddress, 0x1c>,
                 rcc_cfgr2_tt<"rcc_cfgr2", baseaddress, 0x20>,
                 rcc_cfgr3_tt<"rcc_cfgr3", baseaddress, 0x24>,
                 rcc_pll1cfgr_tt<"rcc_pll1cfgr", baseaddress, 0x28>,
                 rcc_pll1divr_tt<"rcc_pll1divr", baseaddress, 0x34>,
                 rcc_pll1fracr_tt<"rcc_pll1fracr", baseaddress, 0x38>,
                 rcc_cier_tt<"rcc_cier", baseaddress, 0x50>,
                 rcc_cifr_tt<"rcc_cifr", baseaddress, 0x54>,
                 rcc_cicr_tt<"rcc_cicr", baseaddress, 0x58>,
                 rcc_ahb1rstr_tt<"rcc_ahb1rstr", baseaddress, 0x60>,
                 rcc_ahb2rstr_tt<"rcc_ahb2rstr", baseaddress, 0x64>,
                 rcc_ahb4rstr_tt<"rcc_ahb4rstr", baseaddress, 0x6c>,
                 rcc_ahb5rstr_tt<"rcc_ahb5rstr", baseaddress, 0x70>,
                 rcc_apb1rstr1_tt<"rcc_apb1rstr1", baseaddress, 0x74>,
                 rcc_apb1rstr2_tt<"rcc_apb1rstr2", baseaddress, 0x78>,
                 rcc_apb2rstr_tt<"rcc_apb2rstr", baseaddress, 0x7c>,
                 rcc_apb7rstr_tt<"rcc_apb7rstr", baseaddress, 0x80>,
                 rcc_ahb1enr_tt<"rcc_ahb1enr", baseaddress, 0x88>,
                 rcc_ahb2enr_tt<"rcc_ahb2enr", baseaddress, 0x8c>,
                 rcc_ahb4enr_tt<"rcc_ahb4enr", baseaddress, 0x94>,
                 rcc_ahb5enr_tt<"rcc_ahb5enr", baseaddress, 0x98>,
                 rcc_apb1enr1_tt<"rcc_apb1enr1", baseaddress, 0x9c>,
                 rcc_apb1enr2_tt<"rcc_apb1enr2", baseaddress, 0xa0>,
                 rcc_apb2enr_tt<"rcc_apb2enr", baseaddress, 0xa4>,
                 rcc_apb7enr_tt<"rcc_apb7enr", baseaddress, 0xa8>,
                 rcc_ahb1smenr_tt<"rcc_ahb1smenr", baseaddress, 0xb0>,
                 rcc_ahb2smenr_tt<"rcc_ahb2smenr", baseaddress, 0xb4>,
                 rcc_ahb4smenr_tt<"rcc_ahb4smenr", baseaddress, 0xbc>,
                 rcc_ahb5smenr_tt<"rcc_ahb5smenr", baseaddress, 0xc0>,
                 rcc_apb1smenr1_tt<"rcc_apb1smenr1", baseaddress, 0xc4>,
                 rcc_apb1smenr2_tt<"rcc_apb1smenr2", baseaddress, 0xc8>,
                 rcc_apb2smenr_tt<"rcc_apb2smenr", baseaddress, 0xcc>,
                 rcc_apb7smenr_tt<"rcc_apb7smenr", baseaddress, 0xd0>,
                 rcc_ccipr1_tt<"rcc_ccipr1", baseaddress, 0xe0>,
                 rcc_ccipr2_tt<"rcc_ccipr2", baseaddress, 0xe4>,
                 rcc_ccipr3_tt<"rcc_ccipr3", baseaddress, 0xe8>,
                 rcc_bdcr1_tt<"rcc_bdcr1", baseaddress, 0xf0>,
                 rcc_csr_tt<"rcc_csr", baseaddress, 0xf4>,
                 rcc_seccfgr_tt<"rcc_seccfgr", baseaddress, 0x110>,
                 rcc_privcfgr_tt<"rcc_privcfgr", baseaddress, 0x114>,
                 rcc_cfgr4_tt<"rcc_cfgr4", baseaddress, 0x200>,
                 rcc_radioenr_tt<"rcc_radioenr", baseaddress, 0x208>,
                 rcc_ecscr1_tt<"rcc_ecscr1", baseaddress, 0x210>>;

} // namespace rccx
} // namespace erworks::stm32::stm32wba54
