/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/rcc.hpp"
namespace erworks::stm32::stm32n647 {
#include "../../../common/peripherals/rcc_cae969dd4f31.inc"
} // namespace erworks::stm32::stm32n647
