/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/access.hpp"
#include "../../common/bittypes.hpp"
namespace erworks::stm32::stm32wba55 {
namespace regs {

// pwr_pwr_cr1_v1: PWR_CR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_cr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", std::uint32_t, 31, 13, common::access::ro>,
               groov::field<"r1rsb1", bool, 12, 12>,
               groov::field<"reserved3", std::uint8_t, 11, 10, common::access::ro>,
               groov::field<"radiorsb", bool, 9, 9>,
               groov::field<"reserved2", bool, 8, 8, common::access::ro>,
               groov::field<"ulpmen", common::bit_enable, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"r2rsb1", bool, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 3, common::access::ro>,
               groov::field<"lpms", std::uint8_t, 2, 0>>;

// pwr_pwr_cr2_v1: PWR_CR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_cr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"flashfwu", bool, 14, 14>,
               groov::field<"reserved2", std::uint8_t, 13, 9, common::access::ro>,
               groov::field<"icrampds", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"sram2pds1", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"sram1pds1", bool, 0, 0>>;

// pwr_pwr_cr3_v1: PWR_CR3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_cr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"fsten", common::bit_enable, 2, 2>,
               groov::field<"regsel", bool, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// pwr_pwr_dbpr_v1: PWR_DBPR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_dbpr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"dbp", bool, 0, 0>>;

// pwr_pwr_ioretenra_v1: PWR_IORETENRA
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretenra_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"en15", bool, 15, 15>,
               groov::field<"en14", bool, 14, 14>,
               groov::field<"en13", bool, 13, 13>,
               groov::field<"en12", bool, 12, 12>,
               groov::field<"en11", bool, 11, 11>,
               groov::field<"en10", bool, 10, 10>,
               groov::field<"en9", bool, 9, 9>,
               groov::field<"en8", bool, 8, 8>,
               groov::field<"en7", bool, 7, 7>,
               groov::field<"en6", bool, 6, 6>,
               groov::field<"en5", bool, 5, 5>,
               groov::field<"reserved0", bool, 4, 4, common::access::ro>,
               groov::field<"en3", bool, 3, 3>,
               groov::field<"en2", bool, 2, 2>,
               groov::field<"en1", bool, 1, 1>,
               groov::field<"en0", bool, 0, 0>>;

// pwr_pwr_ioretenrb_v1: PWR_IORETENRB
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretenrb_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"en15", bool, 15, 15>,
               groov::field<"en14", bool, 14, 14>,
               groov::field<"en13", bool, 13, 13>,
               groov::field<"en12", bool, 12, 12>,
               groov::field<"en11", bool, 11, 11>,
               groov::field<"en10", bool, 10, 10>,
               groov::field<"en9", bool, 9, 9>,
               groov::field<"en8", bool, 8, 8>,
               groov::field<"en7", bool, 7, 7>,
               groov::field<"en6", bool, 6, 6>,
               groov::field<"en5", bool, 5, 5>,
               groov::field<"en4", bool, 4, 4>,
               groov::field<"en3", bool, 3, 3>,
               groov::field<"en2", bool, 2, 2>,
               groov::field<"en1", bool, 1, 1>,
               groov::field<"en0", bool, 0, 0>>;

// pwr_pwr_ioretenrc_v1: PWR_IORETENRC
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretenrc_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"en15", bool, 15, 15>,
               groov::field<"en14", bool, 14, 14>,
               groov::field<"en13", bool, 13, 13>,
               groov::field<"reserved0", std::uint16_t, 12, 0, common::access::ro>>;

// pwr_pwr_ioretenrh_v1: PWR_IORETENRH
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretenrh_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"en3", bool, 3, 3>,
               groov::field<"reserved0", std::uint8_t, 2, 0, common::access::ro>>;

// pwr_pwr_ioretra_v1: PWR_IORETRA
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretra_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ret15", bool, 15, 15>,
               groov::field<"ret14", bool, 14, 14>,
               groov::field<"ret13", bool, 13, 13>,
               groov::field<"ret12", bool, 12, 12>,
               groov::field<"ret11", bool, 11, 11>,
               groov::field<"ret10", bool, 10, 10>,
               groov::field<"ret9", bool, 9, 9>,
               groov::field<"ret8", bool, 8, 8>,
               groov::field<"ret7", bool, 7, 7>,
               groov::field<"ret6", bool, 6, 6>,
               groov::field<"ret5", bool, 5, 5>,
               groov::field<"reserved0", bool, 4, 4, common::access::ro>,
               groov::field<"ret3", bool, 3, 3>,
               groov::field<"ret2", bool, 2, 2>,
               groov::field<"ret1", bool, 1, 1>,
               groov::field<"ret0", bool, 0, 0>>;

// pwr_pwr_ioretrb_v1: PWR_IORETRB
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretrb_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ret15", bool, 15, 15>,
               groov::field<"ret14", bool, 14, 14>,
               groov::field<"ret13", bool, 13, 13>,
               groov::field<"ret12", bool, 12, 12>,
               groov::field<"ret11", bool, 11, 11>,
               groov::field<"ret10", bool, 10, 10>,
               groov::field<"ret9", bool, 9, 9>,
               groov::field<"ret8", bool, 8, 8>,
               groov::field<"ret7", bool, 7, 7>,
               groov::field<"ret6", bool, 6, 6>,
               groov::field<"ret5", bool, 5, 5>,
               groov::field<"ret4", bool, 4, 4>,
               groov::field<"ret3", bool, 3, 3>,
               groov::field<"ret2", bool, 2, 2>,
               groov::field<"ret1", bool, 1, 1>,
               groov::field<"ret0", bool, 0, 0>>;

// pwr_pwr_ioretrc_v1: PWR_IORETRC
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretrc_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ret15", bool, 15, 15>,
               groov::field<"ret14", bool, 14, 14>,
               groov::field<"ret13", bool, 13, 13>,
               groov::field<"reserved0", std::uint16_t, 12, 0, common::access::ro>>;

// pwr_pwr_ioretrh_v1: PWR_IORETRH
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_ioretrh_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"ret3", bool, 3, 3>,
               groov::field<"reserved0", std::uint8_t, 2, 0, common::access::ro>>;

// pwr_pwr_radioscr_v1: PWR_RADIOSCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_radioscr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"regpardyvddrfpa", common::bit_ready, 15, 15, common::access::ro>,
               groov::field<"reserved1", std::uint8_t, 14, 13, common::access::ro>,
               groov::field<"rfvddhpa", std::uint8_t, 12, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 4, common::access::ro>,
               groov::field<"encmode", common::bit_enable, 3, 3, common::access::ro>,
               groov::field<"phymode", common::bit_enable, 2, 2, common::access::ro>,
               groov::field<"mode", std::uint8_t, 1, 0, common::access::ro>>;

// pwr_pwr_seccfgr_v1: PWR_SECCFGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_seccfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"vbsec", bool, 14, 14>,
               groov::field<"vdmsec", bool, 13, 13>,
               groov::field<"lpmsec", bool, 12, 12>,
               groov::field<"reserved0", std::uint8_t, 11, 8, common::access::ro>,
               groov::field<"wup8sec", bool, 7, 7>,
               groov::field<"wup7sec", bool, 6, 6>,
               groov::field<"wup6sec", bool, 5, 5>,
               groov::field<"wup5sec", bool, 4, 4>,
               groov::field<"wup4sec", bool, 3, 3>,
               groov::field<"wup3sec", bool, 2, 2>,
               groov::field<"wup2sec", bool, 1, 1>,
               groov::field<"wup1sec", bool, 0, 0>>;

// pwr_pwr_sr_v1: PWR_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"sbf", bool, 2, 2, common::access::ro>,
               groov::field<"stopf", bool, 1, 1, common::access::ro>,
               groov::field<"cssf", bool, 0, 0, common::access::wo>>;

// pwr_pwr_svmcr_v1: PWR_SVMCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_svmcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"pvdls", std::uint8_t, 7, 5>,
               groov::field<"pvde", common::bit_enable, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 0, common::access::ro>>;

// pwr_pwr_svmsr_v1: PWR_SVMSR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_svmsr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"actvos", bool, 16, 16, common::access::ro>,
               groov::field<"actvosrdy", common::bit_ready, 15, 15, common::access::ro>,
               groov::field<"reserved2", std::uint16_t, 14, 5, common::access::ro>,
               groov::field<"pvdo", bool, 4, 4, common::access::ro>,
               groov::field<"reserved1", std::uint8_t, 3, 2, common::access::ro>,
               groov::field<"regs", bool, 1, 1, common::access::ro>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// pwr_pwr_vosr_v1: PWR_VOSR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_vosr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"vos", bool, 16, 16>,
               groov::field<"vosrdy", common::bit_ready, 15, 15, common::access::ro>,
               groov::field<"reserved0", std::uint16_t, 14, 0, common::access::ro>>;

// pwr_pwr_wucr1_v1: PWR_WUCR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_wucr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"wupen8", bool, 7, 7>,
               groov::field<"wupen7", bool, 6, 6>,
               groov::field<"wupen6", bool, 5, 5>,
               groov::field<"wupen5", bool, 4, 4>,
               groov::field<"wupen4", bool, 3, 3>,
               groov::field<"wupen3", bool, 2, 2>,
               groov::field<"wupen2", bool, 1, 1>,
               groov::field<"wupen1", bool, 0, 0>>;

// pwr_pwr_wucr2_v1: PWR_WUCR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_wucr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"wupp8", bool, 7, 7>,
               groov::field<"wupp7", bool, 6, 6>,
               groov::field<"wupp6", bool, 5, 5>,
               groov::field<"wupp5", bool, 4, 4>,
               groov::field<"wupp4", bool, 3, 3>,
               groov::field<"wupp3", bool, 2, 2>,
               groov::field<"wupp2", bool, 1, 1>,
               groov::field<"wupp1", bool, 0, 0>>;

// pwr_pwr_wucr3_v1: PWR_WUCR3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_wucr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"wusel8", std::uint8_t, 15, 14>,
               groov::field<"wusel7", std::uint8_t, 13, 12>,
               groov::field<"wusel6", std::uint8_t, 11, 10>,
               groov::field<"wusel5", std::uint8_t, 9, 8>,
               groov::field<"wusel4", std::uint8_t, 7, 6>,
               groov::field<"wusel3", std::uint8_t, 5, 4>,
               groov::field<"wusel2", std::uint8_t, 3, 2>,
               groov::field<"wusel1", std::uint8_t, 1, 0>>;

// pwr_pwr_wuscr_v1: PWR_WUSCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_wuscr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"cwuf8", bool, 7, 7, common::access::wo>,
               groov::field<"cwuf7", bool, 6, 6, common::access::wo>,
               groov::field<"cwuf6", bool, 5, 5, common::access::wo>,
               groov::field<"cwuf5", bool, 4, 4, common::access::wo>,
               groov::field<"cwuf4", bool, 3, 3, common::access::wo>,
               groov::field<"cwuf3", bool, 2, 2, common::access::wo>,
               groov::field<"cwuf2", bool, 1, 1, common::access::wo>,
               groov::field<"cwuf1", bool, 0, 0, common::access::wo>>;

// pwr_pwr_wusr_v1: PWR_WUSR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pwr_pwr_wusr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"wuf8", bool, 7, 7, common::access::ro>,
               groov::field<"wuf7", bool, 6, 6, common::access::ro>,
               groov::field<"wuf6", bool, 5, 5, common::access::ro>,
               groov::field<"wuf5", bool, 4, 4, common::access::ro>,
               groov::field<"wuf4", bool, 3, 3, common::access::ro>,
               groov::field<"wuf3", bool, 2, 2, common::access::ro>,
               groov::field<"wuf2", bool, 1, 1, common::access::ro>,
               groov::field<"wuf1", bool, 0, 0, common::access::ro>>;

} // namespace regs

namespace pwrx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr1_tt = regs::pwr_pwr_cr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr2_tt = regs::pwr_pwr_cr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr3_tt = regs::pwr_pwr_cr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_vosr_tt = regs::pwr_pwr_vosr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_svmcr_tt = regs::pwr_pwr_svmcr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_wucr1_tt = regs::pwr_pwr_wucr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_wucr2_tt = regs::pwr_pwr_wucr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_wucr3_tt = regs::pwr_pwr_wucr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_dbpr_tt = regs::pwr_pwr_dbpr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_seccfgr_tt = regs::pwr_pwr_seccfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_privcfgr_tt = regs::flash_flash_prifcfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_sr_tt = regs::pwr_pwr_sr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_svmsr_tt = regs::pwr_pwr_svmsr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_wusr_tt = regs::pwr_pwr_wusr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_wuscr_tt = regs::pwr_pwr_wuscr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretenra_tt = regs::pwr_pwr_ioretenra_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretra_tt = regs::pwr_pwr_ioretra_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretenrb_tt = regs::pwr_pwr_ioretenrb_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretrb_tt = regs::pwr_pwr_ioretrb_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretenrc_tt = regs::pwr_pwr_ioretenrc_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretrc_tt = regs::pwr_pwr_ioretrc_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretenrh_tt = regs::pwr_pwr_ioretenrh_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_ioretrh_tt = regs::pwr_pwr_ioretrh_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_radioscr_tt = regs::pwr_pwr_radioscr_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using pwrx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 pwr_cr1_tt<"pwr_cr1", baseaddress, 0x0>,
                 pwr_cr2_tt<"pwr_cr2", baseaddress, 0x4>,
                 pwr_cr3_tt<"pwr_cr3", baseaddress, 0x8>,
                 pwr_vosr_tt<"pwr_vosr", baseaddress, 0xc>,
                 pwr_svmcr_tt<"pwr_svmcr", baseaddress, 0x10>,
                 pwr_wucr1_tt<"pwr_wucr1", baseaddress, 0x14>,
                 pwr_wucr2_tt<"pwr_wucr2", baseaddress, 0x18>,
                 pwr_wucr3_tt<"pwr_wucr3", baseaddress, 0x1c>,
                 pwr_dbpr_tt<"pwr_dbpr", baseaddress, 0x28>,
                 pwr_seccfgr_tt<"pwr_seccfgr", baseaddress, 0x30>,
                 pwr_privcfgr_tt<"pwr_privcfgr", baseaddress, 0x34>,
                 pwr_sr_tt<"pwr_sr", baseaddress, 0x38>,
                 pwr_svmsr_tt<"pwr_svmsr", baseaddress, 0x3c>,
                 pwr_wusr_tt<"pwr_wusr", baseaddress, 0x44>,
                 pwr_wuscr_tt<"pwr_wuscr", baseaddress, 0x48>,
                 pwr_ioretenra_tt<"pwr_ioretenra", baseaddress, 0x50>,
                 pwr_ioretra_tt<"pwr_ioretra", baseaddress, 0x54>,
                 pwr_ioretenrb_tt<"pwr_ioretenrb", baseaddress, 0x58>,
                 pwr_ioretrb_tt<"pwr_ioretrb", baseaddress, 0x5c>,
                 pwr_ioretenrc_tt<"pwr_ioretenrc", baseaddress, 0x60>,
                 pwr_ioretrc_tt<"pwr_ioretrc", baseaddress, 0x64>,
                 pwr_ioretenrh_tt<"pwr_ioretenrh", baseaddress, 0x88>,
                 pwr_ioretrh_tt<"pwr_ioretrh", baseaddress, 0x8c>,
                 pwr_radioscr_tt<"pwr_radioscr", baseaddress, 0x100>>;

} // namespace pwrx
} // namespace erworks::stm32::stm32wba55
