/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// firewall_cr_v1: CR
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"vde", common::bit_enable, 2, 2>,
               groov::field<"vds", bool, 1, 1>,
               groov::field<"fpa", bool, 0, 0>>;

// firewall_csl_v1: CSL
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_csl_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"leng", std::uint16_t, 21, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// firewall_cssa_v1: CSSA
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_cssa_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"add", std::uint16_t, 23, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// firewall_nvdsl_v1: NVDSL
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_nvdsl_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"leng", std::uint16_t, 21, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// firewall_nvdssa_v1: NVDSSA
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_nvdssa_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"add", std::uint16_t, 23, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// firewall_vdsl_v1: VDSL
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_vdsl_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"leng", std::uint16_t, 15, 6>,
               groov::field<"reserved0", std::uint8_t, 5, 0, common::access::ro>>;

// firewall_vdssa_v1: VDSSA
// Used by: FIREWALL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using firewall_vdssa_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"add", std::uint16_t, 15, 6>,
               groov::field<"reserved0", std::uint8_t, 5, 0, common::access::ro>>;

} // namespace stm32::regs
