/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/tims.hpp"
namespace erworks::stm32::stm32h7b3 {
#include "../../../common/peripherals/tims_92916eb29723.inc"
} // namespace erworks::stm32::stm32h7b3
