/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/gpdma.hpp"
namespace erworks::stm32::stm32h563 {
#include "../../../common/peripherals/gpdma_827395cc3ddb.inc"
} // namespace erworks::stm32::stm32h563
