/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// exti_emr_v1: EMR
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_emr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"em23", bool, 23, 23>,
               groov::field<"em22", bool, 22, 22>,
               groov::field<"em21", bool, 21, 21>,
               groov::field<"em20", bool, 20, 20>,
               groov::field<"em19", bool, 19, 19>,
               groov::field<"em18", bool, 18, 18>,
               groov::field<"em17", bool, 17, 17>,
               groov::field<"em16", bool, 16, 16>,
               groov::field<"em15", bool, 15, 15>,
               groov::field<"em14", bool, 14, 14>,
               groov::field<"em13", bool, 13, 13>,
               groov::field<"em12", bool, 12, 12>,
               groov::field<"em11", bool, 11, 11>,
               groov::field<"em10", bool, 10, 10>,
               groov::field<"em9", bool, 9, 9>,
               groov::field<"em8", bool, 8, 8>,
               groov::field<"em7", bool, 7, 7>,
               groov::field<"em6", bool, 6, 6>,
               groov::field<"em5", bool, 5, 5>,
               groov::field<"em4", bool, 4, 4>,
               groov::field<"em3", bool, 3, 3>,
               groov::field<"em2", bool, 2, 2>,
               groov::field<"em1", bool, 1, 1>,
               groov::field<"em0", bool, 0, 0>>;

// exti_ftsr_v1: FTSR
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_ftsr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"tr23", bool, 23, 23>,
               groov::field<"tr22", bool, 22, 22>,
               groov::field<"tr21", bool, 21, 21>,
               groov::field<"tr20", bool, 20, 20>,
               groov::field<"tr19", bool, 19, 19>,
               groov::field<"tr18", bool, 18, 18>,
               groov::field<"tr17", bool, 17, 17>,
               groov::field<"tr16", bool, 16, 16>,
               groov::field<"tr15", bool, 15, 15>,
               groov::field<"tr14", bool, 14, 14>,
               groov::field<"tr13", bool, 13, 13>,
               groov::field<"tr12", bool, 12, 12>,
               groov::field<"tr11", bool, 11, 11>,
               groov::field<"tr10", bool, 10, 10>,
               groov::field<"tr9", bool, 9, 9>,
               groov::field<"tr8", bool, 8, 8>,
               groov::field<"tr7", bool, 7, 7>,
               groov::field<"tr6", bool, 6, 6>,
               groov::field<"tr5", bool, 5, 5>,
               groov::field<"tr4", bool, 4, 4>,
               groov::field<"tr3", bool, 3, 3>,
               groov::field<"tr2", bool, 2, 2>,
               groov::field<"tr1", bool, 1, 1>,
               groov::field<"tr0", bool, 0, 0>>;

// exti_imr_v1: IMR
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_imr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"im23", bool, 23, 23>,
               groov::field<"im22", bool, 22, 22>,
               groov::field<"im21", bool, 21, 21>,
               groov::field<"im20", bool, 20, 20>,
               groov::field<"im19", bool, 19, 19>,
               groov::field<"im18", bool, 18, 18>,
               groov::field<"im17", bool, 17, 17>,
               groov::field<"im16", bool, 16, 16>,
               groov::field<"im15", bool, 15, 15>,
               groov::field<"im14", bool, 14, 14>,
               groov::field<"im13", bool, 13, 13>,
               groov::field<"im12", bool, 12, 12>,
               groov::field<"im11", bool, 11, 11>,
               groov::field<"im10", bool, 10, 10>,
               groov::field<"mi9", bool, 9, 9>,
               groov::field<"im8", bool, 8, 8>,
               groov::field<"im7", bool, 7, 7>,
               groov::field<"im6", bool, 6, 6>,
               groov::field<"im5", bool, 5, 5>,
               groov::field<"im4", bool, 4, 4>,
               groov::field<"im3", bool, 3, 3>,
               groov::field<"im2", bool, 2, 2>,
               groov::field<"im1", bool, 1, 1>,
               groov::field<"im0", bool, 0, 0>>;

// exti_pr_v1: PR
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_pr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"pr23", bool, 23, 23>,
               groov::field<"pr22", bool, 22, 22>,
               groov::field<"pr21", bool, 21, 21>,
               groov::field<"pr20", bool, 20, 20>,
               groov::field<"pr19", bool, 19, 19>,
               groov::field<"pr18", bool, 18, 18>,
               groov::field<"pr17", bool, 17, 17>,
               groov::field<"pr16", bool, 16, 16>,
               groov::field<"pr15", bool, 15, 15>,
               groov::field<"pr14", bool, 14, 14>,
               groov::field<"pr13", bool, 13, 13>,
               groov::field<"pr12", bool, 12, 12>,
               groov::field<"pr11", bool, 11, 11>,
               groov::field<"pr10", bool, 10, 10>,
               groov::field<"pr9", bool, 9, 9>,
               groov::field<"pr8", bool, 8, 8>,
               groov::field<"pr7", bool, 7, 7>,
               groov::field<"pr6", bool, 6, 6>,
               groov::field<"pr5", bool, 5, 5>,
               groov::field<"pr4", bool, 4, 4>,
               groov::field<"pr3", bool, 3, 3>,
               groov::field<"pr2", bool, 2, 2>,
               groov::field<"pr1", bool, 1, 1>,
               groov::field<"pr0", bool, 0, 0>>;

// exti_rtsr_v1: RTSR
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_rtsr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"tr23", bool, 23, 23>,
               groov::field<"tr22", bool, 22, 22>,
               groov::field<"tr21", bool, 21, 21>,
               groov::field<"tr20", bool, 20, 20>,
               groov::field<"tr19", bool, 19, 19>,
               groov::field<"tr18", bool, 18, 18>,
               groov::field<"tr17", bool, 17, 17>,
               groov::field<"tr16", bool, 16, 16>,
               groov::field<"tr15", bool, 15, 15>,
               groov::field<"tr14", bool, 14, 14>,
               groov::field<"tr13", bool, 13, 13>,
               groov::field<"tr12", bool, 12, 12>,
               groov::field<"tr11", bool, 11, 11>,
               groov::field<"tr10", bool, 10, 10>,
               groov::field<"tr9", bool, 9, 9>,
               groov::field<"tr8", bool, 8, 8>,
               groov::field<"tr7", bool, 7, 7>,
               groov::field<"tr6", bool, 6, 6>,
               groov::field<"tr5", bool, 5, 5>,
               groov::field<"tr4", bool, 4, 4>,
               groov::field<"tr3", bool, 3, 3>,
               groov::field<"tr2", bool, 2, 2>,
               groov::field<"tr1", bool, 1, 1>,
               groov::field<"tr0", bool, 0, 0>>;

// exti_swier_v1: SWIER
// Used by: EXTI
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exti_swier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"swier23", bool, 23, 23>,
               groov::field<"swier22", bool, 22, 22>,
               groov::field<"swier21", bool, 21, 21>,
               groov::field<"swier20", bool, 20, 20>,
               groov::field<"swier19", bool, 19, 19>,
               groov::field<"swier18", bool, 18, 18>,
               groov::field<"swier17", bool, 17, 17>,
               groov::field<"swier16", bool, 16, 16>,
               groov::field<"swier15", bool, 15, 15>,
               groov::field<"swier14", bool, 14, 14>,
               groov::field<"swier13", bool, 13, 13>,
               groov::field<"swier12", bool, 12, 12>,
               groov::field<"swier11", bool, 11, 11>,
               groov::field<"swier10", bool, 10, 10>,
               groov::field<"swier9", bool, 9, 9>,
               groov::field<"swier8", bool, 8, 8>,
               groov::field<"swier7", bool, 7, 7>,
               groov::field<"swier6", bool, 6, 6>,
               groov::field<"swier5", bool, 5, 5>,
               groov::field<"swier4", bool, 4, 4>,
               groov::field<"swier3", bool, 3, 3>,
               groov::field<"swier2", bool, 2, 2>,
               groov::field<"swier1", bool, 1, 1>,
               groov::field<"swier0", bool, 0, 0>>;

} // namespace stm32::regs
