/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// usbphyc_ldo_v1: LDO
// Used by: USBPHYC
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usbphyc_ldo_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"ldo_disable", bool, 2, 2>,
               groov::field<"ldo_status", bool, 1, 1, common::access::ro>,
               groov::field<"ldo_used", bool, 0, 0, common::access::ro>>;

// usbphyc_pll1_v1: PLL1
// Used by: USBPHYC
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usbphyc_pll1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"pll1sel", std::uint8_t, 3, 1>,
               groov::field<"pll1en", common::bit_enable, 0, 0>>;

// usbphyc_tune_v1: TUNE
// Used by: USBPHYC
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usbphyc_tune_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"sqlbyp", bool, 23, 23>,
               groov::field<"shtcctctlprot", bool, 22, 22>,
               groov::field<"hsrxoff", std::uint8_t, 21, 20>,
               groov::field<"hsfallpreem", bool, 19, 19>,
               groov::field<"stagsel", bool, 18, 18>,
               groov::field<"hdrxgneqen", common::bit_enable, 17, 17>,
               groov::field<"sqlchctl", std::uint8_t, 16, 15>,
               groov::field<"hsdrvchkztrm", std::uint8_t, 14, 13>,
               groov::field<"hsdrvchkitrm", std::uint8_t, 12, 9>,
               groov::field<"hsdrvrfred", bool, 8, 8>,
               groov::field<"fsdrvrfadj", bool, 7, 7>,
               groov::field<"hsdrvcurincr", bool, 6, 6>,
               groov::field<"hsdrvdclev", bool, 5, 5>,
               groov::field<"hsdrvdccur", bool, 4, 4>,
               groov::field<"hsdrvslew", bool, 3, 3>,
               groov::field<"lfscapen", common::bit_enable, 2, 2>,
               groov::field<"incurrint", bool, 1, 1>,
               groov::field<"incurren", common::bit_enable, 0, 0>>;

} // namespace stm32::regs
