/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/ltdc.hpp"
namespace erworks::stm32::stm32h7b0 {
#include "../../../common/peripherals/ltdc_96bec723491a.inc"
} // namespace erworks::stm32::stm32h7b0
