/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/flash.hpp"
namespace erworks::stm32::stm32f417 {
#include "../../../common/peripherals/flash_db81d925b17f.inc"
} // namespace erworks::stm32::stm32f417
