/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/tamp.hpp"
namespace mcu::stm32::stm32l562 {
#include "../../common/peripherals/tamp_d8d88e9feabf.inc"
} // namespace mcu::stm32::stm32l562
