/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/cec.hpp"
namespace mcu::stm32::stm32f100 {
#include "../../common/peripherals/cec_7e5e69d5db45.inc"
} // namespace mcu::stm32::stm32f100
