/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/access.hpp"
#include "../../common/bittypes.hpp"
namespace erworks::stm32::stm32g041 {
namespace regs {

// adc_adc_cfgr1_v1: ADC_CFGR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_adc_cfgr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", bool, 31, 31, common::access::ro>,
               groov::field<"awdch1ch", std::uint8_t, 30, 26>,
               groov::field<"reserved2", std::uint8_t, 25, 24, common::access::ro>,
               groov::field<"awd1en", common::bit_enable, 23, 23>,
               groov::field<"awd1sgl", bool, 22, 22>,
               groov::field<"chselrmod", bool, 21, 21>,
               groov::field<"reserved1", std::uint8_t, 20, 17, common::access::ro>,
               groov::field<"discen", common::bit_enable, 16, 16>,
               groov::field<"autoff", bool, 15, 15>,
               groov::field<"wait", bool, 14, 14>,
               groov::field<"cont", bool, 13, 13>,
               groov::field<"ovrmod", bool, 12, 12>,
               groov::field<"exten", std::uint8_t, 11, 10>,
               groov::field<"reserved0", bool, 9, 9, common::access::ro>,
               groov::field<"extsel", std::uint8_t, 8, 6>,
               groov::field<"align", bool, 5, 5>,
               groov::field<"res", std::uint8_t, 4, 3>,
               groov::field<"scandir", bool, 2, 2>,
               groov::field<"dmacfg", bool, 1, 1>,
               groov::field<"dmaen", common::bit_enable, 0, 0>>;

// adc_adc_cfgr2_v1: ADC_CFGR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_adc_cfgr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ckmode", std::uint8_t, 31, 30>,
               groov::field<"lftrig", bool, 29, 29>,
               groov::field<"reserved1", std::uint32_t, 28, 10, common::access::ro>,
               groov::field<"tovs", bool, 9, 9>,
               groov::field<"ovss", std::uint8_t, 8, 5>,
               groov::field<"ovsr", std::uint8_t, 4, 2>,
               groov::field<"reserved0", bool, 1, 1, common::access::ro>,
               groov::field<"ovse", bool, 0, 0>>;

// adc_awd1tr_v1: AWD1TR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_awd1tr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 28, common::access::ro>,
               groov::field<"ht1", std::uint16_t, 27, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 12, common::access::ro>,
               groov::field<"lt1", std::uint16_t, 11, 0>>;

// adc_awd2cr_v1: AWD2CR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_awd2cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"awd2ch", std::uint32_t, 18, 0>>;

// adc_awd2tr_v1: AWD2TR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_awd2tr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 28, common::access::ro>,
               groov::field<"ht2", std::uint16_t, 27, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 12, common::access::ro>,
               groov::field<"lt2", std::uint16_t, 11, 0>>;

// adc_awd3cr_v1: AWD3CR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_awd3cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"awd3ch", std::uint32_t, 18, 0>>;

// adc_awd3tr_v1: AWD3TR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_awd3tr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 28, common::access::ro>,
               groov::field<"ht3", std::uint16_t, 27, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 12, common::access::ro>,
               groov::field<"lt3", std::uint16_t, 11, 0>>;

// adc_calfact_v1: CALFACT
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_calfact_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 7, common::access::ro>,
               groov::field<"calfact", std::uint8_t, 6, 0>>;

// adc_ccr_v1: CCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_ccr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 25, common::access::ro>,
               groov::field<"vbaten", common::bit_enable, 24, 24>,
               groov::field<"tsen", common::bit_enable, 23, 23>,
               groov::field<"vrefen", common::bit_enable, 22, 22>,
               groov::field<"presc", std::uint8_t, 21, 18>,
               groov::field<"reserved0", std::uint32_t, 17, 0, common::access::ro>>;

// adc_chselr_v1: CHSELR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_chselr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"chsel", std::uint32_t, 18, 0>>;

// adc_chselr_1_v1: CHSELR_1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_chselr_1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sq8", std::uint8_t, 31, 28>,
               groov::field<"sq7", std::uint8_t, 27, 24>,
               groov::field<"sq6", std::uint8_t, 23, 20>,
               groov::field<"sq5", std::uint8_t, 19, 16>,
               groov::field<"sq4", std::uint8_t, 15, 12>,
               groov::field<"sq3", std::uint8_t, 11, 8>,
               groov::field<"sq2", std::uint8_t, 7, 4>,
               groov::field<"sq1", std::uint8_t, 3, 0>>;

// adc_cr_v1: CR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"adcal", bool, 31, 31>,
               groov::field<"reserved2", std::uint8_t, 30, 29, common::access::ro>,
               groov::field<"advregen", common::bit_enable, 28, 28>,
               groov::field<"reserved1", std::uint32_t, 27, 5, common::access::ro>,
               groov::field<"adstp", bool, 4, 4>,
               groov::field<"reserved0", bool, 3, 3, common::access::ro>,
               groov::field<"adstart", bool, 2, 2>,
               groov::field<"addis", common::bit_nenable, 1, 1>,
               groov::field<"aden", common::bit_enable, 0, 0>>;

// adc_dr_v1: DR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_dr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint16_t, 31, 16>,
               groov::field<"regulardata", std::uint16_t, 15, 0>>;

// adc_ier_v1: IER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_ier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 14, common::access::ro>,
               groov::field<"ccrdyie", common::bit_ready, 13, 13>,
               groov::field<"reserved2", bool, 12, 12, common::access::ro>,
               groov::field<"eocalie", common::bit_enable, 11, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"awd3ie", common::bit_enable, 9, 9>,
               groov::field<"awd2ie", common::bit_enable, 8, 8>,
               groov::field<"awd1ie", common::bit_enable, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 5, common::access::ro>,
               groov::field<"ovrie", common::bit_enable, 4, 4>,
               groov::field<"eosie", common::bit_enable, 3, 3>,
               groov::field<"eocie", common::bit_enable, 2, 2>,
               groov::field<"eosmpie", common::bit_enable, 1, 1>,
               groov::field<"adrdyie", common::bit_ready, 0, 0>>;

// adc_isr_v1: ISR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 14, common::access::ro>,
               groov::field<"ccrdy", common::bit_ready, 13, 13>,
               groov::field<"reserved2", bool, 12, 12, common::access::ro>,
               groov::field<"eocal", bool, 11, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"awd3", bool, 9, 9>,
               groov::field<"awd2", bool, 8, 8>,
               groov::field<"awd1", bool, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 5, common::access::ro>,
               groov::field<"ovr", bool, 4, 4>,
               groov::field<"eos", bool, 3, 3>,
               groov::field<"eoc", bool, 2, 2>,
               groov::field<"eosmp", bool, 1, 1>,
               groov::field<"adrdy", common::bit_ready, 0, 0>>;

// adc_smpr_v1: SMPR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using adc_smpr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 27, common::access::ro>,
               groov::field<"smpsel", std::uint32_t, 26, 8>,
               groov::field<"reserved1", bool, 7, 7, common::access::ro>,
               groov::field<"smp2", std::uint8_t, 6, 4>,
               groov::field<"reserved0", bool, 3, 3, common::access::ro>,
               groov::field<"smp1", std::uint8_t, 2, 0>>;

} // namespace regs

namespace adc {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using isr_tt = regs::adc_isr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ier_tt = regs::adc_ier_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cr_tt = regs::adc_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc_cfgr1_tt = regs::adc_adc_cfgr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc_cfgr2_tt = regs::adc_adc_cfgr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using smpr_tt = regs::adc_smpr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using awd1tr_tt = regs::adc_awd1tr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using awd2tr_tt = regs::adc_awd2tr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using chselr_tt = regs::adc_chselr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using chselr_1_tt = regs::adc_chselr_1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using awd3tr_tt = regs::adc_awd3tr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dr_tt = regs::adc_dr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using awd2cr_tt = regs::adc_awd2cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using awd3cr_tt = regs::adc_awd3cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using calfact_tt = regs::adc_calfact_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ccr_tt = regs::adc_ccr_v1_tt<name, baseaddress, offset>;

  template <std::uint32_t baseaddress>
  using adc_t =
    groov::group<"adc",
                 groov::mmio_bus<>,
                 isr_tt<"isr", baseaddress, 0x0>,
                 ier_tt<"ier", baseaddress, 0x4>,
                 cr_tt<"cr", baseaddress, 0x8>,
                 adc_cfgr1_tt<"adc_cfgr1", baseaddress, 0xc>,
                 adc_cfgr2_tt<"adc_cfgr2", baseaddress, 0x10>,
                 smpr_tt<"smpr", baseaddress, 0x14>,
                 awd1tr_tt<"awd1tr", baseaddress, 0x20>,
                 awd2tr_tt<"awd2tr", baseaddress, 0x24>,
                 chselr_tt<"chselr", baseaddress, 0x28>,
                 chselr_1_tt<"chselr_1", baseaddress, 0x28>,
                 awd3tr_tt<"awd3tr", baseaddress, 0x2c>,
                 dr_tt<"dr", baseaddress, 0x40>,
                 awd2cr_tt<"awd2cr", baseaddress, 0xa0>,
                 awd3cr_tt<"awd3cr", baseaddress, 0xa4>,
                 calfact_tt<"calfact", baseaddress, 0xb4>,
                 ccr_tt<"ccr", baseaddress, 0x308>>;

} // namespace adc
} // namespace erworks::stm32::stm32g041
