/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// aes_cr_v1: CR
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 13, common::access::ro>,
               groov::field<"dmaouten", common::bit_enable, 12, 12>,
               groov::field<"dmainen", common::bit_enable, 11, 11>,
               groov::field<"errie", common::bit_enable, 10, 10>,
               groov::field<"ccfie", common::bit_enable, 9, 9>,
               groov::field<"errc", bool, 8, 8>,
               groov::field<"ccfc", bool, 7, 7>,
               groov::field<"chmod", std::uint8_t, 6, 5>,
               groov::field<"mode", std::uint8_t, 4, 3>,
               groov::field<"datatype", std::uint8_t, 2, 1>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// aes_dinr_v1: DINR
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_dinr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_dinr", std::uint32_t, 31, 0>>;

// aes_doutr_v1: DOUTR
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_doutr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"aes_doutr", std::uint32_t, 31, 0>>;

// aes_ivr0_v1: IVR0
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_ivr0_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_ivr0", std::uint32_t, 31, 0>>;

// aes_ivr1_v1: IVR1
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_ivr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_ivr1", std::uint32_t, 31, 0>>;

// aes_ivr2_v1: IVR2
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_ivr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_ivr2", std::uint32_t, 31, 0>>;

// aes_ivr3_v1: IVR3
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_ivr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_ivr3", std::uint32_t, 31, 0>>;

// aes_keyr0_v1: KEYR0
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_keyr0_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_keyr0", std::uint32_t, 31, 0>>;

// aes_keyr1_v1: KEYR1
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_keyr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_keyr1", std::uint32_t, 31, 0>>;

// aes_keyr2_v1: KEYR2
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_keyr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_keyr2", std::uint32_t, 31, 0>>;

// aes_keyr3_v1: KEYR3
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_keyr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"aes_keyr3", std::uint32_t, 31, 0>>;

// aes_sr_v1: SR
// Used by: AES
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using aes_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 3>,
               groov::field<"wrerr", bool, 2, 2>,
               groov::field<"rderr", bool, 1, 1>,
               groov::field<"ccf", bool, 0, 0>>;

} // namespace stm32::regs
