/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/gpio.hpp"
namespace mcu::stm32::stm32l100 {
#include "../../common/peripherals/gpio_2afede07f1ba.inc"
} // namespace mcu::stm32::stm32l100
