/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/pwr.hpp"
namespace erworks::stm32::stm32f746 {
#include "../../../common/peripherals/pwr_f842d5d837a2.inc"
} // namespace erworks::stm32::stm32f746
