/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/gpio.hpp"
namespace mcu::stm32::stm32u545 {
#include "../../common/peripherals/gpio_7ecbd172278c.inc"
} // namespace mcu::stm32::stm32u545
