/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/lcd.hpp"
namespace erworks::stm32::stm32l475 {
#include "../../../common/peripherals/lcd_910e7999c0b4.inc"
} // namespace erworks::stm32::stm32l475
