/* File autogenerated with svd2groov */
#pragma once

#include <cstdint>

namespace mcu::stm32::stm32f3x4 {
namespace adc1 { inline constexpr std::uint32_t ADC1_BASE = 0x5000'0000; } // namespace adc1
namespace adc2 { inline constexpr std::uint32_t ADC2_BASE = 0x5000'0100; } // namespace adc2
namespace adc_common { inline constexpr std::uint32_t ADC_COMMON_BASE = 0x5000'0300; } // namespace adc_common
namespace can { inline constexpr std::uint32_t CAN_BASE = 0x4000'6400; } // namespace can
namespace crc { inline constexpr std::uint32_t CRC_BASE = 0x4002'3000; } // namespace crc
namespace dac1 { inline constexpr std::uint32_t DAC1_BASE = 0x4000'7400; } // namespace dac1
namespace dac2 { inline constexpr std::uint32_t DAC2_BASE = 0x4000'9800; } // namespace dac2
namespace dbgmcu { inline constexpr std::uint32_t DBGMCU_BASE = 0xe004'2000; } // namespace dbgmcu
namespace dma1 { inline constexpr std::uint32_t DMA1_BASE = 0x4002'0000; } // namespace dma1
namespace exti { inline constexpr std::uint32_t EXTI_BASE = 0x4001'0400; } // namespace exti
namespace flash { inline constexpr std::uint32_t FLASH_BASE = 0x4002'2000; } // namespace flash
namespace gpioa { inline constexpr std::uint32_t GPIOA_BASE = 0x4800'0000; } // namespace gpioa
namespace gpiob { inline constexpr std::uint32_t GPIOB_BASE = 0x4800'0400; } // namespace gpiob
namespace gpioc { inline constexpr std::uint32_t GPIOC_BASE = 0x4800'0800; } // namespace gpioc
namespace gpiod { inline constexpr std::uint32_t GPIOD_BASE = 0x4800'0c00; } // namespace gpiod
namespace gpiof { inline constexpr std::uint32_t GPIOF_BASE = 0x4800'1400; } // namespace gpiof
namespace hrtim_common { inline constexpr std::uint32_t HRTIM_COMMON_BASE = 0x4001'7780; } // namespace hrtim_common
namespace hrtim_master { inline constexpr std::uint32_t HRTIM_MASTER_BASE = 0x4001'7400; } // namespace hrtim_master
namespace hrtim_tima { inline constexpr std::uint32_t HRTIM_TIMA_BASE = 0x4001'7480; } // namespace hrtim_tima
namespace hrtim_timb { inline constexpr std::uint32_t HRTIM_TIMB_BASE = 0x4001'7500; } // namespace hrtim_timb
namespace hrtim_timc { inline constexpr std::uint32_t HRTIM_TIMC_BASE = 0x4001'7580; } // namespace hrtim_timc
namespace hrtim_timd { inline constexpr std::uint32_t HRTIM_TIMD_BASE = 0x4001'7600; } // namespace hrtim_timd
namespace hrtim_time { inline constexpr std::uint32_t HRTIM_TIME_BASE = 0x4001'7680; } // namespace hrtim_time
namespace i2c1 { inline constexpr std::uint32_t I2C1_BASE = 0x4000'5400; } // namespace i2c1
namespace i2c2 { inline constexpr std::uint32_t I2C2_BASE = 0x4000'5800; } // namespace i2c2
namespace i2c3 { inline constexpr std::uint32_t I2C3_BASE = 0x4000'7800; } // namespace i2c3
namespace i2s2ext { inline constexpr std::uint32_t I2S2EXT_BASE = 0x4000'3400; } // namespace i2s2ext
namespace i2s3ext { inline constexpr std::uint32_t I2S3EXT_BASE = 0x4000'4000; } // namespace i2s3ext
namespace iwdg { inline constexpr std::uint32_t IWDG_BASE = 0x4000'3000; } // namespace iwdg
namespace pwr { inline constexpr std::uint32_t PWR_BASE = 0x4000'7000; } // namespace pwr
namespace rcc { inline constexpr std::uint32_t RCC_BASE = 0x4002'1000; } // namespace rcc
namespace rtc { inline constexpr std::uint32_t RTC_BASE = 0x4000'2800; } // namespace rtc
namespace spi1 { inline constexpr std::uint32_t SPI1_BASE = 0x4001'3000; } // namespace spi1
namespace spi2 { inline constexpr std::uint32_t SPI2_BASE = 0x4000'3800; } // namespace spi2
namespace spi3 { inline constexpr std::uint32_t SPI3_BASE = 0x4000'3c00; } // namespace spi3
namespace syscfg_comp_opamp { inline constexpr std::uint32_t SYSCFG_COMP_OPAMP_BASE = 0x4001'0000; } // namespace syscfg_comp_opamp
namespace tim1 { inline constexpr std::uint32_t TIM1_BASE = 0x4001'2c00; } // namespace tim1
namespace tim15 { inline constexpr std::uint32_t TIM15_BASE = 0x4001'4000; } // namespace tim15
namespace tim16 { inline constexpr std::uint32_t TIM16_BASE = 0x4001'4400; } // namespace tim16
namespace tim17 { inline constexpr std::uint32_t TIM17_BASE = 0x4001'4800; } // namespace tim17
namespace tim2 { inline constexpr std::uint32_t TIM2_BASE = 0x4000'0000; } // namespace tim2
namespace tim3 { inline constexpr std::uint32_t TIM3_BASE = 0x4000'0400; } // namespace tim3
namespace tim6 { inline constexpr std::uint32_t TIM6_BASE = 0x4000'1000; } // namespace tim6
namespace tim7 { inline constexpr std::uint32_t TIM7_BASE = 0x4000'1400; } // namespace tim7
namespace tsc { inline constexpr std::uint32_t TSC_BASE = 0x4002'4000; } // namespace tsc
namespace usart1 { inline constexpr std::uint32_t USART1_BASE = 0x4001'3800; } // namespace usart1
namespace usart2 { inline constexpr std::uint32_t USART2_BASE = 0x4000'4400; } // namespace usart2
namespace usart3 { inline constexpr std::uint32_t USART3_BASE = 0x4000'4800; } // namespace usart3
namespace wwdg { inline constexpr std::uint32_t WWDG_BASE = 0x4000'2c00; } // namespace wwdg

} // namespace mcu::stm32::stm32f3x4
