/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/rng.hpp"
namespace mcu::stm32::stm32wb06 {
#include "../../../common/peripherals/rng_752665bbb1cf.inc"
} // namespace mcu::stm32::stm32wb06
