/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32wb10_cm4/registers/lptim.hpp>

namespace stm32::stm32wb10_cm4 {

namespace lptimx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using isr_tt = regs::lptim_isr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icr_tt = regs::lptim_icr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ier_tt = regs::lptim_ier_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cfgr_tt = regs::lptim_cfgr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cr_tt = regs::lptim_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cmp_tt = regs::lptim_cmp_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using arr_tt = regs::lptim_arr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cnt_tt = regs::lptim_cnt_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using or_tt = regs::lptim_or_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using lptimx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 isr_tt<"isr", baseaddress, 0x0>,
                 icr_tt<"icr", baseaddress, 0x4>,
                 ier_tt<"ier", baseaddress, 0x8>,
                 cfgr_tt<"cfgr", baseaddress, 0xc>,
                 cr_tt<"cr", baseaddress, 0x10>,
                 cmp_tt<"cmp", baseaddress, 0x14>,
                 arr_tt<"arr", baseaddress, 0x18>,
                 cnt_tt<"cnt", baseaddress, 0x1c>,
                 or_tt<"or", baseaddress, 0x20>>;

} // namespace lptimx

} // namespace stm32::stm32wb10_cm4
