/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// ramcfg_ram1cr_v1: RAM1CR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram1cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"wsc", std::uint8_t, 18, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 9, common::access::ro>,
               groov::field<"sramer", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"ale", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"ecce", bool, 0, 0>>;

// ramcfg_ram1erkeyr_v1: RAM1ERKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram1erkeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"erasekey", std::uint8_t, 7, 0>>;

// ramcfg_ram1isr_v1: RAM1ISR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram1isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 9>,
               groov::field<"srambusy", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 2>,
               groov::field<"ded", bool, 1, 1>,
               groov::field<"sedc", bool, 0, 0>>;

// ramcfg_ram2cr_v1: RAM2CR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"wsc", std::uint8_t, 18, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 9, common::access::ro>,
               groov::field<"sramer", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"ale", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"ecce", bool, 0, 0>>;

// ramcfg_ram2dear_v1: RAM2DEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2dear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"edea", std::uint32_t, 31, 0>>;

// ramcfg_ram2ecckeyr_v1: RAM2ECCKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2ecckeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"ecckey", std::uint8_t, 7, 0>>;

// ramcfg_ram2erkeyr_v1: RAM2ERKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2erkeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"erasekey", std::uint8_t, 7, 0>>;

// ramcfg_ram2icr_v1: RAM2ICR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2icr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 2, common::access::ro>,
               groov::field<"cded", bool, 1, 1>,
               groov::field<"csedc", bool, 0, 0>>;

// ramcfg_ram2ier_v1: RAM2IER
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2ier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"eccnmi", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"deie", common::bit_enable, 1, 1>,
               groov::field<"seie", common::bit_enable, 0, 0>>;

// ramcfg_ram2isr_v1: RAM2ISR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 9>,
               groov::field<"srambusy", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 2>,
               groov::field<"ded", bool, 1, 1>,
               groov::field<"sedc", bool, 0, 0>>;

// ramcfg_ram2sear_v1: RAM2SEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2sear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"esea", std::uint32_t, 31, 0>>;

// ramcfg_ram2wpr1_v1: RAM2WPR1
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2wpr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"p31wp", bool, 31, 31>,
               groov::field<"p30wp", bool, 30, 30>,
               groov::field<"p29wp", bool, 29, 29>,
               groov::field<"p28wp", bool, 28, 28>,
               groov::field<"p27wp", bool, 27, 27>,
               groov::field<"p26wp", bool, 26, 26>,
               groov::field<"p25wp", bool, 25, 25>,
               groov::field<"p24wp", bool, 24, 24>,
               groov::field<"p23wp", bool, 23, 23>,
               groov::field<"p22wp", bool, 22, 22>,
               groov::field<"p21wp", bool, 21, 21>,
               groov::field<"p20wp", bool, 20, 20>,
               groov::field<"p19wp", bool, 19, 19>,
               groov::field<"p18wp", bool, 18, 18>,
               groov::field<"p17wp", bool, 17, 17>,
               groov::field<"p16wp", bool, 16, 16>,
               groov::field<"p15wp", bool, 15, 15>,
               groov::field<"p14wp", bool, 14, 14>,
               groov::field<"p13wp", bool, 13, 13>,
               groov::field<"p12wp", bool, 12, 12>,
               groov::field<"p11wp", bool, 11, 11>,
               groov::field<"p10wp", bool, 10, 10>,
               groov::field<"p9wp", bool, 9, 9>,
               groov::field<"p8wp", bool, 8, 8>,
               groov::field<"p7wp", bool, 7, 7>,
               groov::field<"p6wp", bool, 6, 6>,
               groov::field<"p5wp", bool, 5, 5>,
               groov::field<"p4wp", bool, 4, 4>,
               groov::field<"p3wp", bool, 3, 3>,
               groov::field<"p2wp", bool, 2, 2>,
               groov::field<"p1wp", bool, 1, 1>,
               groov::field<"p0wp", bool, 0, 0>>;

// ramcfg_ram2wpr2_v1: RAM2WPR2
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram2wpr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"p63wp", bool, 31, 31>,
               groov::field<"p62wp", bool, 30, 30>,
               groov::field<"p61wp", bool, 29, 29>,
               groov::field<"p60wp", bool, 28, 28>,
               groov::field<"p59wp", bool, 27, 27>,
               groov::field<"p58wp", bool, 26, 26>,
               groov::field<"p57wp", bool, 25, 25>,
               groov::field<"p56wp", bool, 24, 24>,
               groov::field<"p55wp", bool, 23, 23>,
               groov::field<"p54wp", bool, 22, 22>,
               groov::field<"p53wp", bool, 21, 21>,
               groov::field<"p52wp", bool, 20, 20>,
               groov::field<"p51wp", bool, 19, 19>,
               groov::field<"p50wp", bool, 18, 18>,
               groov::field<"p49wp", bool, 17, 17>,
               groov::field<"p48wp", bool, 16, 16>,
               groov::field<"p47wp", bool, 15, 15>,
               groov::field<"p46wp", bool, 14, 14>,
               groov::field<"p45wp", bool, 13, 13>,
               groov::field<"p44wp", bool, 12, 12>,
               groov::field<"p43wp", bool, 11, 11>,
               groov::field<"p42wp", bool, 10, 10>,
               groov::field<"p41wp", bool, 9, 9>,
               groov::field<"p40wp", bool, 8, 8>,
               groov::field<"p39wp", bool, 7, 7>,
               groov::field<"p38wp", bool, 6, 6>,
               groov::field<"p37wp", bool, 5, 5>,
               groov::field<"p36wp", bool, 4, 4>,
               groov::field<"p35wp", bool, 3, 3>,
               groov::field<"p34wp", bool, 2, 2>,
               groov::field<"p33wp", bool, 1, 1>,
               groov::field<"p32wp", bool, 0, 0>>;

// ramcfg_ram3cr_v1: RAM3CR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"wsc", std::uint8_t, 18, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 9, common::access::ro>,
               groov::field<"sramer", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"ale", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"ecce", bool, 0, 0>>;

// ramcfg_ram3dear_v1: RAM3DEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3dear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"edea", std::uint32_t, 31, 0>>;

// ramcfg_ram3ecckeyr_v1: RAM3ECCKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3ecckeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"ecckey", std::uint8_t, 7, 0>>;

// ramcfg_ram3erkeyr_v1: RAM3ERKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3erkeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"erasekey", std::uint8_t, 7, 0>>;

// ramcfg_ram3icr_v1: RAM3ICR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3icr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 2, common::access::ro>,
               groov::field<"cded", bool, 1, 1>,
               groov::field<"csedc", bool, 0, 0>>;

// ramcfg_ram3ier_v1: RAM3IER
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3ier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"eccnmi", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"deie", common::bit_enable, 1, 1>,
               groov::field<"seie", common::bit_enable, 0, 0>>;

// ramcfg_ram3isr_v1: RAM3ISR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 9>,
               groov::field<"srambusy", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 2>,
               groov::field<"ded", bool, 1, 1>,
               groov::field<"sedc", bool, 0, 0>>;

// ramcfg_ram3sear_v1: RAM3SEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram3sear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"esea", std::uint32_t, 31, 0>>;

// ramcfg_ram4cr_v1: RAM4CR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram4cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"wsc", std::uint8_t, 18, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 9, common::access::ro>,
               groov::field<"sramer", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"ale", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"ecce", bool, 0, 0>>;

// ramcfg_ram4erkeyr_v1: RAM4ERKEYR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram4erkeyr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"erasekey", std::uint8_t, 7, 0>>;

// ramcfg_ram4isr_v1: RAM4ISR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram4isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 9>,
               groov::field<"srambusy", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 2>,
               groov::field<"ded", bool, 1, 1>,
               groov::field<"sedc", bool, 0, 0>>;

// ramcfg_ram5cr_v1: RAM5CR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 19, common::access::ro>,
               groov::field<"wsc", std::uint8_t, 18, 16>,
               groov::field<"reserved2", std::uint8_t, 15, 9, common::access::ro>,
               groov::field<"sramer", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"ale", bool, 4, 4>,
               groov::field<"reserved0", std::uint8_t, 3, 1, common::access::ro>,
               groov::field<"ecce", bool, 0, 0>>;

// ramcfg_ram5dear_v1: RAM5DEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5dear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"edea", std::uint32_t, 31, 0>>;

// ramcfg_ram5icr_v1: RAM5ICR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5icr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 2, common::access::ro>,
               groov::field<"cded", bool, 1, 1>,
               groov::field<"csedc", bool, 0, 0>>;

// ramcfg_ram5ier_v1: RAM5IER
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5ier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"eccnmi", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"deie", common::bit_enable, 1, 1>,
               groov::field<"seie", common::bit_enable, 0, 0>>;

// ramcfg_ram5isr_v1: RAM5ISR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5isr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 9>,
               groov::field<"srambusy", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 2>,
               groov::field<"ded", bool, 1, 1>,
               groov::field<"sedc", bool, 0, 0>>;

// ramcfg_ram5sear_v1: RAM5SEAR
// Used by: RAMCFG, SEC_RAMCFG
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ramcfg_ram5sear_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"esea", std::uint32_t, 31, 0>>;

} // namespace stm32::regs
