/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/wwdg.hpp"
namespace erworks::stm32::stm32wle5_cm4 {
#include "../../../common/peripherals/wwdg_953e1c514b88.inc"
} // namespace erworks::stm32::stm32wle5_cm4
