/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32h5e5/registers/gpiok.hpp>

namespace stm32::stm32h5e5 {

namespace gpiokx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_moder_tt = regs::gpiok_gpiok_moder_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_otyper_tt = regs::gpiok_gpiok_otyper_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_ospeedr_tt = regs::gpiok_gpiok_ospeedr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_pupdr_tt = regs::gpiok_gpiok_pupdr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_idr_tt = regs::gpiok_gpiok_idr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_odr_tt = regs::gpiok_gpiok_odr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_bsrr_tt = regs::gpiok_gpiok_bsrr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_lckr_tt = regs::gpiok_gpiok_lckr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_afrl_tt = regs::gpiok_gpiok_afrl_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_afrh_tt = regs::gpiok_gpiok_afrh_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_brr_tt = regs::gpiok_gpiok_brr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_hslvr_tt = regs::gpiok_gpiok_hslvr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiok_seccfgr_tt = regs::gpiok_gpiok_seccfgr_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpiokx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 gpiok_moder_tt<"gpiok_moder", baseaddress, 0x0>,
                 gpiok_otyper_tt<"gpiok_otyper", baseaddress, 0x4>,
                 gpiok_ospeedr_tt<"gpiok_ospeedr", baseaddress, 0x8>,
                 gpiok_pupdr_tt<"gpiok_pupdr", baseaddress, 0xc>,
                 gpiok_idr_tt<"gpiok_idr", baseaddress, 0x10>,
                 gpiok_odr_tt<"gpiok_odr", baseaddress, 0x14>,
                 gpiok_bsrr_tt<"gpiok_bsrr", baseaddress, 0x18>,
                 gpiok_lckr_tt<"gpiok_lckr", baseaddress, 0x1c>,
                 gpiok_afrl_tt<"gpiok_afrl", baseaddress, 0x20>,
                 gpiok_afrh_tt<"gpiok_afrh", baseaddress, 0x24>,
                 gpiok_brr_tt<"gpiok_brr", baseaddress, 0x28>,
                 gpiok_hslvr_tt<"gpiok_hslvr", baseaddress, 0x2c>,
                 gpiok_seccfgr_tt<"gpiok_seccfgr", baseaddress, 0x30>>;

} // namespace gpiokx

} // namespace stm32::stm32h5e5
