/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/crc.hpp"
namespace erworks::stm32::stm32h573 {
#include "../../../common/peripherals/crc_693d54776a92.inc"
} // namespace erworks::stm32::stm32h573
