/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/lptim.hpp"
namespace mcu::stm32::stm32h573 {
#include "../../../common/peripherals/lptim_6f93b494c307.inc"
} // namespace mcu::stm32::stm32h573
