/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/dma2d.hpp"
namespace mcu::stm32::stm32h7b3 {
#include "../../common/peripherals/dma2d_f487157450a6.inc"
} // namespace mcu::stm32::stm32h7b3
