/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/adf.hpp"
namespace mcu::stm32::stm32u5a9 {
#include "../../../common/peripherals/adf_838bed2609b1.inc"
} // namespace mcu::stm32::stm32u5a9
