
namespace hsem {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r0_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r1_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r2_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r3_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r4_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r5_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r6_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r7_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r8_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r9_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r10_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r11_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r12_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r13_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r14_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r15_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r16_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r17_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r18_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r19_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r20_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r21_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r22_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r23_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r24_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r25_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r26_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r27_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r28_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r29_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r30_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using r31_tt = regs::hsem_hsem_r0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr0_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr1_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr2_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr3_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr4_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr5_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr6_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr7_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr8_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr9_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr10_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr11_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr12_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr13_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr14_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr15_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr16_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr17_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr18_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr19_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr20_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr21_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr22_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr23_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr24_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr25_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr26_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr27_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr28_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr29_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr30_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rlr31_tt = regs::hsem_hsem_rlr0_v2_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cr_tt = regs::hsem_hsem_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using keyr_tt = regs::hsem_hsem_keyr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hwcfgr2_tt = regs::hardware_semaphore_hwcfgr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hwcfgr1_tt = regs::hardware_semaphore_hwcfgr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using verr_tt = regs::iwdg_verr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipidr_tt = regs::dmamux_dmamux_ipidr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sidr_tt = regs::iwdg_sidr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c1ier0_tt = regs::hardware_semaphore_c1ier0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c1icr_tt = regs::hardware_semaphore_c1icr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c1isr_tt = regs::hardware_semaphore_c1isr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c1misr_tt = regs::hardware_semaphore_c1misr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c2ier0_tt = regs::hardware_semaphore_c1ier0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c2icr_tt = regs::hardware_semaphore_c1icr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c2isr_tt = regs::hardware_semaphore_c1isr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using c2misr_tt = regs::hardware_semaphore_c1misr_v1_tt<name, baseaddress, offset>;

  template <std::uint32_t baseaddress>
  using hsem_t =
    groov::group<"hsem",
                 groov::mmio_bus<>,
                 r0_tt<"r0", baseaddress, 0x0>,
                 r1_tt<"r1", baseaddress, 0x4>,
                 r2_tt<"r2", baseaddress, 0x8>,
                 r3_tt<"r3", baseaddress, 0xc>,
                 r4_tt<"r4", baseaddress, 0x10>,
                 r5_tt<"r5", baseaddress, 0x14>,
                 r6_tt<"r6", baseaddress, 0x18>,
                 r7_tt<"r7", baseaddress, 0x1c>,
                 r8_tt<"r8", baseaddress, 0x20>,
                 r9_tt<"r9", baseaddress, 0x24>,
                 r10_tt<"r10", baseaddress, 0x28>,
                 r11_tt<"r11", baseaddress, 0x2c>,
                 r12_tt<"r12", baseaddress, 0x30>,
                 r13_tt<"r13", baseaddress, 0x34>,
                 r14_tt<"r14", baseaddress, 0x38>,
                 r15_tt<"r15", baseaddress, 0x3c>,
                 r16_tt<"r16", baseaddress, 0x40>,
                 r17_tt<"r17", baseaddress, 0x44>,
                 r18_tt<"r18", baseaddress, 0x48>,
                 r19_tt<"r19", baseaddress, 0x4c>,
                 r20_tt<"r20", baseaddress, 0x50>,
                 r21_tt<"r21", baseaddress, 0x54>,
                 r22_tt<"r22", baseaddress, 0x58>,
                 r23_tt<"r23", baseaddress, 0x5c>,
                 r24_tt<"r24", baseaddress, 0x60>,
                 r25_tt<"r25", baseaddress, 0x64>,
                 r26_tt<"r26", baseaddress, 0x68>,
                 r27_tt<"r27", baseaddress, 0x6c>,
                 r28_tt<"r28", baseaddress, 0x70>,
                 r29_tt<"r29", baseaddress, 0x74>,
                 r30_tt<"r30", baseaddress, 0x78>,
                 r31_tt<"r31", baseaddress, 0x7c>,
                 rlr0_tt<"rlr0", baseaddress, 0x80>,
                 rlr1_tt<"rlr1", baseaddress, 0x84>,
                 rlr2_tt<"rlr2", baseaddress, 0x88>,
                 rlr3_tt<"rlr3", baseaddress, 0x8c>,
                 rlr4_tt<"rlr4", baseaddress, 0x90>,
                 rlr5_tt<"rlr5", baseaddress, 0x94>,
                 rlr6_tt<"rlr6", baseaddress, 0x98>,
                 rlr7_tt<"rlr7", baseaddress, 0x9c>,
                 rlr8_tt<"rlr8", baseaddress, 0xa0>,
                 rlr9_tt<"rlr9", baseaddress, 0xa4>,
                 rlr10_tt<"rlr10", baseaddress, 0xa8>,
                 rlr11_tt<"rlr11", baseaddress, 0xac>,
                 rlr12_tt<"rlr12", baseaddress, 0xb0>,
                 rlr13_tt<"rlr13", baseaddress, 0xb4>,
                 rlr14_tt<"rlr14", baseaddress, 0xb8>,
                 rlr15_tt<"rlr15", baseaddress, 0xbc>,
                 rlr16_tt<"rlr16", baseaddress, 0xc0>,
                 rlr17_tt<"rlr17", baseaddress, 0xc4>,
                 rlr18_tt<"rlr18", baseaddress, 0xc8>,
                 rlr19_tt<"rlr19", baseaddress, 0xcc>,
                 rlr20_tt<"rlr20", baseaddress, 0xd0>,
                 rlr21_tt<"rlr21", baseaddress, 0xd4>,
                 rlr22_tt<"rlr22", baseaddress, 0xd8>,
                 rlr23_tt<"rlr23", baseaddress, 0xdc>,
                 rlr24_tt<"rlr24", baseaddress, 0xe0>,
                 rlr25_tt<"rlr25", baseaddress, 0xe4>,
                 rlr26_tt<"rlr26", baseaddress, 0xe8>,
                 rlr27_tt<"rlr27", baseaddress, 0xec>,
                 rlr28_tt<"rlr28", baseaddress, 0xf0>,
                 rlr29_tt<"rlr29", baseaddress, 0xf4>,
                 rlr30_tt<"rlr30", baseaddress, 0xf8>,
                 rlr31_tt<"rlr31", baseaddress, 0xfc>,
                 cr_tt<"cr", baseaddress, 0x140>,
                 keyr_tt<"keyr", baseaddress, 0x144>,
                 hwcfgr2_tt<"hwcfgr2", baseaddress, 0x3ec>,
                 hwcfgr1_tt<"hwcfgr1", baseaddress, 0x3f0>,
                 verr_tt<"verr", baseaddress, 0x3f4>,
                 ipidr_tt<"ipidr", baseaddress, 0x3f8>,
                 sidr_tt<"sidr", baseaddress, 0x3fc>,
                 c1ier0_tt<"c1ier0", baseaddress, 0x100>,
                 c1icr_tt<"c1icr", baseaddress, 0x104>,
                 c1isr_tt<"c1isr", baseaddress, 0x108>,
                 c1misr_tt<"c1misr", baseaddress, 0x10c>,
                 c2ier0_tt<"c2ier0", baseaddress, 0x110>,
                 c2icr_tt<"c2icr", baseaddress, 0x114>,
                 c2isr_tt<"c2isr", baseaddress, 0x118>,
                 c2misr_tt<"c2misr", baseaddress, 0x11c>>;

} // namespace hsem
