/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/sai.hpp"
namespace erworks::stm32::stm32f479 {
#include "../../../common/peripherals/sai_100d62a99a0a.inc"
} // namespace erworks::stm32::stm32f479
