/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/gpioe.hpp"
namespace erworks::stm32::stm32u375 {
#include "../../../common/peripherals/gpioe_a668df3de301.inc"
} // namespace erworks::stm32::stm32u375
