/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dac.hpp"
namespace erworks::stm32::stm32l4s7 {
#include "../../../common/peripherals/dac_e29297227fd0.inc"
} // namespace erworks::stm32::stm32l4s7
