/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include "../registers/gpiog.hpp"

namespace mcu::stm32::stm32h523 {

namespace gpiogx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_moder_tt = regs::gpiog_gpiog_moder_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_otyper_tt = regs::gpiog_gpiog_otyper_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_ospeedr_tt = regs::gpiog_gpiog_ospeedr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_pupdr_tt = regs::gpiog_gpiog_pupdr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_idr_tt = regs::gpiog_gpiog_idr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_odr_tt = regs::gpiog_gpiog_odr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_bsrr_tt = regs::gpiog_gpiog_bsrr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_lckr_tt = regs::gpiog_gpiog_lckr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_afrl_tt = regs::gpiog_gpiog_afrl_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_afrh_tt = regs::gpiog_gpiog_afrh_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_brr_tt = regs::gpiog_gpiog_brr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_hslvr_tt = regs::gpiog_gpiog_hslvr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gpiog_seccfgr_tt = regs::gpiog_gpiog_seccfgr_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpiogx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 gpiog_moder_tt<"gpiog_moder", baseaddress, 0x0>,
                 gpiog_otyper_tt<"gpiog_otyper", baseaddress, 0x4>,
                 gpiog_ospeedr_tt<"gpiog_ospeedr", baseaddress, 0x8>,
                 gpiog_pupdr_tt<"gpiog_pupdr", baseaddress, 0xc>,
                 gpiog_idr_tt<"gpiog_idr", baseaddress, 0x10>,
                 gpiog_odr_tt<"gpiog_odr", baseaddress, 0x14>,
                 gpiog_bsrr_tt<"gpiog_bsrr", baseaddress, 0x18>,
                 gpiog_lckr_tt<"gpiog_lckr", baseaddress, 0x1c>,
                 gpiog_afrl_tt<"gpiog_afrl", baseaddress, 0x20>,
                 gpiog_afrh_tt<"gpiog_afrh", baseaddress, 0x24>,
                 gpiog_brr_tt<"gpiog_brr", baseaddress, 0x28>,
                 gpiog_hslvr_tt<"gpiog_hslvr", baseaddress, 0x2c>,
                 gpiog_seccfgr_tt<"gpiog_seccfgr", baseaddress, 0x30>>;

} // namespace gpiogx

} // namespace mcu::stm32::stm32h523
