/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/usart.hpp"
namespace mcu::stm32::stm32f0x0 {
#include "../../common/peripherals/usart_63d795d83c50.inc"
} // namespace mcu::stm32::stm32f0x0
