/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/spi.hpp"
namespace erworks::stm32::stm32g081 {
#include "../../../common/peripherals/spi_18d7f649edfe.inc"
} // namespace erworks::stm32::stm32g081
