/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/usb_otg_hs.hpp"
namespace erworks::stm32::stm32h730 {
#include "../../../common/peripherals/usb_otg_hs_d06af227bad9.inc"
} // namespace erworks::stm32::stm32h730
