/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/access.hpp"
#include "../../common/bittypes.hpp"
namespace erworks::stm32::stm32wl33 {
namespace regs {

// rng_rng_cr_v1: RNG_CR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rng_cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"tst_clk", bool, 3, 3>,
               groov::field<"rng_dis", common::bit_nenable, 2, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// rng_rng_itip_v1: RNG_ITIP
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rng_itip_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"itip", bool, 0, 0>>;

// rng_rng_sr_v1: RNG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rng_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"fault", bool, 2, 2>,
               groov::field<"revclk", bool, 1, 1, common::access::ro>,
               groov::field<"rngrdy", common::bit_ready, 0, 0, common::access::ro>>;

// rng_rng_tcr_v1: RNG_TCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rng_tcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 1, common::access::ro>,
               groov::field<"tcr", bool, 0, 0>>;

// rng_rng_val_v1: RNG_VAL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rng_val_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint16_t, 31, 16>,
               groov::field<"random_value", std::uint16_t, 15, 0>>;

// rng_rngpcellid0_v1: RNGPCELLID0
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngpcellid0_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"rngpcellid0", std::uint8_t, 7, 0>>;

// rng_rngpcellid1_v1: RNGPCELLID1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngpcellid1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"rngpcellid1", std::uint8_t, 7, 0>>;

// rng_rngpcellid2_v1: RNGPCELLID2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngpcellid2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"rngpcellid2", std::uint8_t, 7, 0>>;

// rng_rngpcellid3_v1: RNGPCELLID3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngpcellid3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"rngpcellid3", std::uint8_t, 7, 0>>;

// rng_rngperiphid0_v1: RNGPERIPHID0
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngperiphid0_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"partnumber0", std::uint8_t, 7, 0>>;

// rng_rngperiphid1_v1: RNGPERIPHID1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngperiphid1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"designer0", std::uint8_t, 7, 4>,
               groov::field<"partnumber1", std::uint8_t, 3, 0>>;

// rng_rngperiphid2_v1: RNGPERIPHID2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngperiphid2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"revision", std::uint8_t, 7, 4>,
               groov::field<"designer1", std::uint8_t, 3, 0>>;

// rng_rngperiphid3_v1: RNGPERIPHID3
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using rng_rngperiphid3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"configuration", std::uint8_t, 7, 0>>;

} // namespace regs

namespace rng {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_cr_tt = regs::rng_rng_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_sr_tt = regs::rng_rng_sr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_val_tt = regs::rng_rng_val_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_tcr_tt = regs::rng_rng_tcr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_itip_tt = regs::rng_rng_itip_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid0_tt = regs::rng_rngperiphid0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid1_tt = regs::rng_rngperiphid1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid2_tt = regs::rng_rngperiphid2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid3_tt = regs::rng_rngperiphid3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid0_tt = regs::rng_rngpcellid0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid1_tt = regs::rng_rngpcellid1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid2_tt = regs::rng_rngpcellid2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid3_tt = regs::rng_rngpcellid3_v1_tt<name, baseaddress, offset>;

  template <std::uint32_t baseaddress>
  using rng_t =
    groov::group<"rng",
                 groov::mmio_bus<>,
                 rng_cr_tt<"rng_cr", baseaddress, 0x0>,
                 rng_sr_tt<"rng_sr", baseaddress, 0x4>,
                 rng_val_tt<"rng_val", baseaddress, 0x8>,
                 rng_tcr_tt<"rng_tcr", baseaddress, 0x80>,
                 rng_itip_tt<"rng_itip", baseaddress, 0x84>,
                 rngperiphid0_tt<"rngperiphid0", baseaddress, 0xfe0>,
                 rngperiphid1_tt<"rngperiphid1", baseaddress, 0xfe4>,
                 rngperiphid2_tt<"rngperiphid2", baseaddress, 0xfe8>,
                 rngperiphid3_tt<"rngperiphid3", baseaddress, 0xfec>,
                 rngpcellid0_tt<"rngpcellid0", baseaddress, 0xff0>,
                 rngpcellid1_tt<"rngpcellid1", baseaddress, 0xff4>,
                 rngpcellid2_tt<"rngpcellid2", baseaddress, 0xff8>,
                 rngpcellid3_tt<"rngpcellid3", baseaddress, 0xffc>>;

} // namespace rng
} // namespace erworks::stm32::stm32wl33
