/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// gpdma_gpdma_c0br1_v1: GPDMA_C0BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c0cr_v1: GPDMA_C0CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c0dar_v1: GPDMA_C0DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c0fcr_v1: GPDMA_C0FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c0lbar_v1: GPDMA_C0LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c0llr_v1: GPDMA_C0LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c0sar_v1: GPDMA_C0SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c0sr_v1: GPDMA_C0SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c0tr1_v1: GPDMA_C0TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c0tr2_v1: GPDMA_C0TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c0tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c1br1_v1: GPDMA_C1BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c1cr_v1: GPDMA_C1CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c1dar_v1: GPDMA_C1DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c1fcr_v1: GPDMA_C1FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c1lbar_v1: GPDMA_C1LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c1llr_v1: GPDMA_C1LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c1sar_v1: GPDMA_C1SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c1sr_v1: GPDMA_C1SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c1tr1_v1: GPDMA_C1TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c1tr2_v1: GPDMA_C1TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c1tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c2br1_v1: GPDMA_C2BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c2cr_v1: GPDMA_C2CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c2dar_v1: GPDMA_C2DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c2fcr_v1: GPDMA_C2FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c2lbar_v1: GPDMA_C2LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c2llr_v1: GPDMA_C2LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c2sar_v1: GPDMA_C2SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c2sr_v1: GPDMA_C2SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c2tr1_v1: GPDMA_C2TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c2tr2_v1: GPDMA_C2TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c2tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c3br1_v1: GPDMA_C3BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c3cr_v1: GPDMA_C3CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c3dar_v1: GPDMA_C3DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c3fcr_v1: GPDMA_C3FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c3lbar_v1: GPDMA_C3LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c3llr_v1: GPDMA_C3LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c3sar_v1: GPDMA_C3SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c3sr_v1: GPDMA_C3SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c3tr1_v1: GPDMA_C3TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c3tr2_v1: GPDMA_C3TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c3tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c4br1_v1: GPDMA_C4BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c4cr_v1: GPDMA_C4CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c4dar_v1: GPDMA_C4DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c4fcr_v1: GPDMA_C4FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c4lbar_v1: GPDMA_C4LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c4llr_v1: GPDMA_C4LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c4sar_v1: GPDMA_C4SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c4sr_v1: GPDMA_C4SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c4tr1_v1: GPDMA_C4TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c4tr2_v1: GPDMA_C4TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c4tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c5br1_v1: GPDMA_C5BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c5cr_v1: GPDMA_C5CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c5dar_v1: GPDMA_C5DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c5fcr_v1: GPDMA_C5FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c5lbar_v1: GPDMA_C5LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c5llr_v1: GPDMA_C5LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"reserved1", std::uint16_t, 26, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c5sar_v1: GPDMA_C5SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c5sr_v1: GPDMA_C5SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c5tr1_v1: GPDMA_C5TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c5tr2_v1: GPDMA_C5TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c5tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c6br1_v1: GPDMA_C6BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"brddec", bool, 31, 31>,
               groov::field<"brsdec", bool, 30, 30>,
               groov::field<"ddec", bool, 29, 29>,
               groov::field<"sdec", bool, 28, 28>,
               groov::field<"reserved0", bool, 27, 27, common::access::ro>,
               groov::field<"brc", std::uint16_t, 26, 16>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c6br2_v1: GPDMA_C6BR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6br2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"brdao", std::uint16_t, 31, 16>,
               groov::field<"brsao", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c6cr_v1: GPDMA_C6CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c6dar_v1: GPDMA_C6DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c6fcr_v1: GPDMA_C6FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c6lbar_v1: GPDMA_C6LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c6llr_v1: GPDMA_C6LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"ut3", bool, 26, 26>,
               groov::field<"ub2", bool, 25, 25>,
               groov::field<"reserved1", std::uint8_t, 24, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c6sar_v1: GPDMA_C6SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c6sr_v1: GPDMA_C6SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c6tr1_v1: GPDMA_C6TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c6tr2_v1: GPDMA_C6TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c6tr3_v1: GPDMA_C6TR3
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c6tr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 29, common::access::ro>,
               groov::field<"dao", std::uint16_t, 28, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 13, common::access::ro>,
               groov::field<"sao", std::uint16_t, 12, 0>>;

// gpdma_gpdma_c7br1_v1: GPDMA_C7BR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7br1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"brddec", bool, 31, 31>,
               groov::field<"brsdec", bool, 30, 30>,
               groov::field<"ddec", bool, 29, 29>,
               groov::field<"sdec", bool, 28, 28>,
               groov::field<"reserved0", bool, 27, 27, common::access::ro>,
               groov::field<"brc", std::uint16_t, 26, 16>,
               groov::field<"bndt", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c7br2_v1: GPDMA_C7BR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7br2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"brdao", std::uint16_t, 31, 16>,
               groov::field<"brsao", std::uint16_t, 15, 0>>;

// gpdma_gpdma_c7cr_v1: GPDMA_C7CR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7cr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"prio", std::uint8_t, 23, 22>,
               groov::field<"reserved2", std::uint8_t, 21, 18, common::access::ro>,
               groov::field<"lap", bool, 17, 17>,
               groov::field<"lsm", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"toie", common::bit_enable, 14, 14>,
               groov::field<"suspie", common::bit_enable, 13, 13>,
               groov::field<"useie", common::bit_enable, 12, 12>,
               groov::field<"uleie", common::bit_enable, 11, 11>,
               groov::field<"dteie", common::bit_enable, 10, 10>,
               groov::field<"htie", common::bit_enable, 9, 9>,
               groov::field<"tcie", common::bit_enable, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 3, common::access::ro>,
               groov::field<"susp", bool, 2, 2>,
               groov::field<"reset", bool, 1, 1, common::access::wo>,
               groov::field<"en", common::bit_enable, 0, 0>>;

// gpdma_gpdma_c7dar_v1: GPDMA_C7DAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7dar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"da", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c7fcr_v1: GPDMA_C7FCR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7fcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::wo>,
               groov::field<"suspf", bool, 13, 13, common::access::wo>,
               groov::field<"usef", bool, 12, 12, common::access::wo>,
               groov::field<"ulef", bool, 11, 11, common::access::wo>,
               groov::field<"dtef", bool, 10, 10, common::access::wo>,
               groov::field<"htf", bool, 9, 9, common::access::wo>,
               groov::field<"tcf", bool, 8, 8, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 7, 0, common::access::ro>>;

// gpdma_gpdma_c7lbar_v1: GPDMA_C7LBAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7lbar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lba", std::uint16_t, 31, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 0, common::access::ro>>;

// gpdma_gpdma_c7llr_v1: GPDMA_C7LLR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7llr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"ut1", bool, 31, 31>,
               groov::field<"ut2", bool, 30, 30>,
               groov::field<"ub1", bool, 29, 29>,
               groov::field<"usa", bool, 28, 28>,
               groov::field<"uda", bool, 27, 27>,
               groov::field<"ut3", bool, 26, 26>,
               groov::field<"ub2", bool, 25, 25>,
               groov::field<"reserved1", std::uint8_t, 24, 17, common::access::ro>,
               groov::field<"ull", bool, 16, 16>,
               groov::field<"la", std::uint16_t, 15, 2>,
               groov::field<"reserved0", std::uint8_t, 1, 0, common::access::ro>>;

// gpdma_gpdma_c7sar_v1: GPDMA_C7SAR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7sar_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sa", std::uint32_t, 31, 0>>;

// gpdma_gpdma_c7sr_v1: GPDMA_C7SR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"fifol", std::uint8_t, 23, 16, common::access::ro>,
               groov::field<"reserved1", bool, 15, 15, common::access::ro>,
               groov::field<"tof", bool, 14, 14, common::access::ro>,
               groov::field<"suspf", bool, 13, 13, common::access::ro>,
               groov::field<"usef", bool, 12, 12, common::access::ro>,
               groov::field<"ulef", bool, 11, 11, common::access::ro>,
               groov::field<"dtef", bool, 10, 10, common::access::ro>,
               groov::field<"htf", bool, 9, 9, common::access::ro>,
               groov::field<"tcf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 1, common::access::ro>,
               groov::field<"idlef", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_c7tr1_v1: GPDMA_C7TR1
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7tr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"dsec", bool, 31, 31>,
               groov::field<"dap", bool, 30, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 28, common::access::ro>,
               groov::field<"dhx", bool, 27, 27>,
               groov::field<"dbx", bool, 26, 26>,
               groov::field<"dbl_1", std::uint8_t, 25, 20>,
               groov::field<"dinc", bool, 19, 19>,
               groov::field<"reserved2", bool, 18, 18, common::access::ro>,
               groov::field<"ddw_log2", std::uint8_t, 17, 16>,
               groov::field<"ssec", bool, 15, 15>,
               groov::field<"sap", bool, 14, 14>,
               groov::field<"sbx", bool, 13, 13>,
               groov::field<"pam", std::uint8_t, 12, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"sbl_1", std::uint8_t, 9, 4>,
               groov::field<"sinc", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, common::access::ro>,
               groov::field<"sdw_log2", std::uint8_t, 1, 0>>;

// gpdma_gpdma_c7tr2_v1: GPDMA_C7TR2
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7tr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"tcem", std::uint8_t, 31, 30>,
               groov::field<"reserved3", std::uint8_t, 29, 26, common::access::ro>,
               groov::field<"trigpol", std::uint8_t, 25, 24>,
               groov::field<"reserved2", std::uint8_t, 23, 22, common::access::ro>,
               groov::field<"trigsel", std::uint8_t, 21, 16>,
               groov::field<"trigm", std::uint8_t, 15, 14>,
               groov::field<"reserved1", bool, 13, 13, common::access::ro>,
               groov::field<"pfreq", bool, 12, 12>,
               groov::field<"breq", bool, 11, 11>,
               groov::field<"dreq", bool, 10, 10>,
               groov::field<"swreq", bool, 9, 9>,
               groov::field<"reserved0", bool, 8, 8, common::access::ro>,
               groov::field<"reqsel", std::uint8_t, 7, 0>>;

// gpdma_gpdma_c7tr3_v1: GPDMA_C7TR3
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_c7tr3_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 29, common::access::ro>,
               groov::field<"dao", std::uint16_t, 28, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 13, common::access::ro>,
               groov::field<"sao", std::uint16_t, 12, 0>>;

// gpdma_gpdma_misr_v1: GPDMA_MISR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_misr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"mis7", bool, 7, 7, common::access::ro>,
               groov::field<"mis6", bool, 6, 6, common::access::ro>,
               groov::field<"mis5", bool, 5, 5, common::access::ro>,
               groov::field<"mis4", bool, 4, 4, common::access::ro>,
               groov::field<"mis3", bool, 3, 3, common::access::ro>,
               groov::field<"mis2", bool, 2, 2, common::access::ro>,
               groov::field<"mis1", bool, 1, 1, common::access::ro>,
               groov::field<"mis0", bool, 0, 0, common::access::ro>>;

// gpdma_gpdma_privcfgr_v1: GPDMA_PRIVCFGR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_privcfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"priv7", bool, 7, 7>,
               groov::field<"priv6", bool, 6, 6>,
               groov::field<"priv5", bool, 5, 5>,
               groov::field<"priv4", bool, 4, 4>,
               groov::field<"priv3", bool, 3, 3>,
               groov::field<"priv2", bool, 2, 2>,
               groov::field<"priv1", bool, 1, 1>,
               groov::field<"priv0", bool, 0, 0>>;

// gpdma_gpdma_rcfglockr_v1: GPDMA_RCFGLOCKR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_rcfglockr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"lock7", common::bit_locked, 7, 7>,
               groov::field<"lock6", common::bit_locked, 6, 6>,
               groov::field<"lock5", common::bit_locked, 5, 5>,
               groov::field<"lock4", common::bit_locked, 4, 4>,
               groov::field<"lock3", common::bit_locked, 3, 3>,
               groov::field<"lock2", common::bit_locked, 2, 2>,
               groov::field<"lock1", common::bit_locked, 1, 1>,
               groov::field<"lock0", common::bit_locked, 0, 0>>;

// gpdma_gpdma_seccfgr_v1: GPDMA_SECCFGR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_seccfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"sec7", bool, 7, 7>,
               groov::field<"sec6", bool, 6, 6>,
               groov::field<"sec5", bool, 5, 5>,
               groov::field<"sec4", bool, 4, 4>,
               groov::field<"sec3", bool, 3, 3>,
               groov::field<"sec2", bool, 2, 2>,
               groov::field<"sec1", bool, 1, 1>,
               groov::field<"sec0", bool, 0, 0>>;

// gpdma_gpdma_smisr_v1: GPDMA_SMISR
// Used by: GPDMA1, SEC_GPDMA1, GPDMA2, SEC_GPDMA2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using gpdma_gpdma_smisr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"mis7", bool, 7, 7, common::access::ro>,
               groov::field<"mis6", bool, 6, 6, common::access::ro>,
               groov::field<"mis5", bool, 5, 5, common::access::ro>,
               groov::field<"mis4", bool, 4, 4, common::access::ro>,
               groov::field<"mis3", bool, 3, 3, common::access::ro>,
               groov::field<"mis2", bool, 2, 2, common::access::ro>,
               groov::field<"mis1", bool, 1, 1, common::access::ro>,
               groov::field<"mis0", bool, 0, 0, common::access::ro>>;

} // namespace stm32::regs
