/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/crc.hpp"
namespace erworks::stm32::stm32wl33 {
#include "../../../common/peripherals/crc_943b9606643e.inc"
} // namespace erworks::stm32::stm32wl33
