/* File autogenerated with svd2groov for stm32l496 */
#pragma once

#include "peripherals/adc.hpp"
#include "peripherals/aes.hpp"
#include "peripherals/can.hpp"
#include "peripherals/comp.hpp"
#include "peripherals/crc.hpp"
#include "peripherals/crs.hpp"
#include "peripherals/dac.hpp"
#include "peripherals/dbgmcu.hpp"
#include "peripherals/dcmi.hpp"
#include "peripherals/dfsdm.hpp"
#include "peripherals/dma.hpp"
#include "peripherals/dma2d.hpp"
#include "peripherals/exti.hpp"
#include "peripherals/firewall.hpp"
#include "peripherals/flash.hpp"
#include "peripherals/fmc.hpp"
#include "peripherals/gpio.hpp"
#include "peripherals/hash.hpp"
#include "peripherals/i2c.hpp"
#include "peripherals/iwdg.hpp"
#include "peripherals/lcd.hpp"
#include "peripherals/lptim.hpp"
#include "peripherals/opamp.hpp"
#include "peripherals/pwr.hpp"
#include "peripherals/quadspi.hpp"
#include "peripherals/rcc.hpp"
#include "peripherals/rng.hpp"
#include "peripherals/rtc.hpp"
#include "peripherals/sai.hpp"
#include "peripherals/sdio.hpp"
#include "peripherals/spi.hpp"
#include "peripherals/swpmi.hpp"
#include "peripherals/syscfg.hpp"
#include "peripherals/tim.hpp"
#include "peripherals/tsc.hpp"
#include "peripherals/usart.hpp"
#include "peripherals/usb_otg_fs.hpp"
#include "peripherals/vref.hpp"
#include "peripherals/wwdg.hpp"

#include "peripherals/addresses.hpp"

namespace mcu::stm32 {

constexpr auto adc1 = stm32l496::adcx::adcx_t<"adc1",stm32l496::adc1::ADC1_BASE>{};

constexpr auto adc2 = stm32l496::adcx::adcx_t<"adc2",stm32l496::adc2::ADC2_BASE>{};

constexpr auto adc3 = stm32l496::adcx::adcx_t<"adc3",stm32l496::adc3::ADC3_BASE>{};

constexpr auto adc_common = stm32l496::adc_common::adc_common_t<stm32l496::adc_common::ADC_COMMON_BASE>{};

constexpr auto aes = stm32l496::aes::aes_t<stm32l496::aes::AES_BASE>{};

constexpr auto can1 = stm32l496::canx::canx_t<"can1",stm32l496::can1::CAN1_BASE>{};

constexpr auto can2 = stm32l496::canx::canx_t<"can2",stm32l496::can2::CAN2_BASE>{};

constexpr auto comp = stm32l496::comp::comp_t<stm32l496::comp::COMP_BASE>{};

constexpr auto crc = stm32l496::crc::crc_t<stm32l496::crc::CRC_BASE>{};

constexpr auto crs = stm32l496::crs::crs_t<stm32l496::crs::CRS_BASE>{};

constexpr auto dac = stm32l496::dac::dac_t<stm32l496::dac::DAC_BASE>{};

constexpr auto dbgmcu = stm32l496::dbgmcu::dbgmcu_t<stm32l496::dbgmcu::DBGMCU_BASE>{};

constexpr auto dcmi = stm32l496::dcmi::dcmi_t<stm32l496::dcmi::DCMI_BASE>{};

constexpr auto dfsdm1 = stm32l496::dfsdm1::dfsdm1_t<stm32l496::dfsdm1::DFSDM1_BASE>{};

constexpr auto dma1 = stm32l496::dmax::dmax_t<"dma1",stm32l496::dma1::DMA1_BASE>{};

constexpr auto dma2 = stm32l496::dmax::dmax_t<"dma2",stm32l496::dma2::DMA2_BASE>{};

constexpr auto dma2d = stm32l496::dma2d::dma2d_t<stm32l496::dma2d::DMA2D_BASE>{};

constexpr auto exti = stm32l496::exti::exti_t<stm32l496::exti::EXTI_BASE>{};

constexpr auto firewall = stm32l496::firewall::firewall_t<stm32l496::firewall::FIREWALL_BASE>{};

constexpr auto flash = stm32l496::flash::flash_t<stm32l496::flash::FLASH_BASE>{};

constexpr auto fmc = stm32l496::fmc::fmc_t<stm32l496::fmc::FMC_BASE>{};

constexpr auto gpioa = stm32l496::gpioa::gpioa_t<stm32l496::gpioa::GPIOA_BASE>{};

constexpr auto gpiob = stm32l496::gpiob::gpiob_t<stm32l496::gpiob::GPIOB_BASE>{};

constexpr auto gpioc = stm32l496::gpiox::gpiox_t<"gpioc",stm32l496::gpioc::GPIOC_BASE>{};

constexpr auto gpiod = stm32l496::gpiox::gpiox_t<"gpiod",stm32l496::gpiod::GPIOD_BASE>{};

constexpr auto gpioe = stm32l496::gpiox::gpiox_t<"gpioe",stm32l496::gpioe::GPIOE_BASE>{};

constexpr auto gpiof = stm32l496::gpiox::gpiox_t<"gpiof",stm32l496::gpiof::GPIOF_BASE>{};

constexpr auto gpiog = stm32l496::gpiox::gpiox_t<"gpiog",stm32l496::gpiog::GPIOG_BASE>{};

constexpr auto gpioh = stm32l496::gpiox::gpiox_t<"gpioh",stm32l496::gpioh::GPIOH_BASE>{};

constexpr auto gpioi = stm32l496::gpioi::gpioi_t<stm32l496::gpioi::GPIOI_BASE>{};

constexpr auto hash = stm32l496::hash::hash_t<stm32l496::hash::HASH_BASE>{};

constexpr auto i2c1 = stm32l496::i2cx::i2cx_t<"i2c1",stm32l496::i2c1::I2C1_BASE>{};

constexpr auto i2c2 = stm32l496::i2cx::i2cx_t<"i2c2",stm32l496::i2c2::I2C2_BASE>{};

constexpr auto i2c3 = stm32l496::i2cx::i2cx_t<"i2c3",stm32l496::i2c3::I2C3_BASE>{};

constexpr auto i2c4 = stm32l496::i2cx::i2cx_t<"i2c4",stm32l496::i2c4::I2C4_BASE>{};

constexpr auto iwdg = stm32l496::iwdg::iwdg_t<stm32l496::iwdg::IWDG_BASE>{};

constexpr auto lcd = stm32l496::lcd::lcd_t<stm32l496::lcd::LCD_BASE>{};

constexpr auto lptim1 = stm32l496::lptimx::lptimx_t<"lptim1",stm32l496::lptim1::LPTIM1_BASE>{};

constexpr auto lptim2 = stm32l496::lptimx::lptimx_t<"lptim2",stm32l496::lptim2::LPTIM2_BASE>{};

constexpr auto lpuart1 = stm32l496::lpuart1::lpuart1_t<stm32l496::lpuart1::LPUART1_BASE>{};

constexpr auto opamp = stm32l496::opamp::opamp_t<stm32l496::opamp::OPAMP_BASE>{};

constexpr auto otg_fs_device = stm32l496::otg_fs_device::otg_fs_device_t<stm32l496::otg_fs_device::OTG_FS_DEVICE_BASE>{};

constexpr auto otg_fs_global = stm32l496::otg_fs_global::otg_fs_global_t<stm32l496::otg_fs_global::OTG_FS_GLOBAL_BASE>{};

constexpr auto otg_fs_host = stm32l496::otg_fs_host::otg_fs_host_t<stm32l496::otg_fs_host::OTG_FS_HOST_BASE>{};

constexpr auto otg_fs_pwrclk = stm32l496::otg_fs_pwrclk::otg_fs_pwrclk_t<stm32l496::otg_fs_pwrclk::OTG_FS_PWRCLK_BASE>{};

constexpr auto pwr = stm32l496::pwr::pwr_t<stm32l496::pwr::PWR_BASE>{};

constexpr auto quadspi = stm32l496::quadspi::quadspi_t<stm32l496::quadspi::QUADSPI_BASE>{};

constexpr auto rcc = stm32l496::rcc::rcc_t<stm32l496::rcc::RCC_BASE>{};

constexpr auto rng = stm32l496::rng::rng_t<stm32l496::rng::RNG_BASE>{};

constexpr auto rtc = stm32l496::rtc::rtc_t<stm32l496::rtc::RTC_BASE>{};

constexpr auto sai1 = stm32l496::saix::saix_t<"sai1",stm32l496::sai1::SAI1_BASE>{};

constexpr auto sai2 = stm32l496::saix::saix_t<"sai2",stm32l496::sai2::SAI2_BASE>{};

constexpr auto sdmmc1 = stm32l496::sdmmc1::sdmmc1_t<stm32l496::sdmmc1::SDMMC1_BASE>{};

constexpr auto spi1 = stm32l496::spix::spix_t<"spi1",stm32l496::spi1::SPI1_BASE>{};

constexpr auto spi2 = stm32l496::spix::spix_t<"spi2",stm32l496::spi2::SPI2_BASE>{};

constexpr auto spi3 = stm32l496::spix::spix_t<"spi3",stm32l496::spi3::SPI3_BASE>{};

constexpr auto swpmi1 = stm32l496::swpmi1::swpmi1_t<stm32l496::swpmi1::SWPMI1_BASE>{};

constexpr auto syscfg = stm32l496::syscfg::syscfg_t<stm32l496::syscfg::SYSCFG_BASE>{};

constexpr auto tim1 = stm32l496::tim1::tim1_t<stm32l496::tim1::TIM1_BASE>{};

constexpr auto tim15 = stm32l496::tim15::tim15_t<stm32l496::tim15::TIM15_BASE>{};

constexpr auto tim16 = stm32l496::timx_v2::timx_v2_t<"tim16",stm32l496::tim16::TIM16_BASE>{};

constexpr auto tim17 = stm32l496::timx_v2::timx_v2_t<"tim17",stm32l496::tim17::TIM17_BASE>{};

constexpr auto tim2 = stm32l496::timx::timx_t<"tim2",stm32l496::tim2::TIM2_BASE>{};

constexpr auto tim3 = stm32l496::timx::timx_t<"tim3",stm32l496::tim3::TIM3_BASE>{};

constexpr auto tim4 = stm32l496::timx::timx_t<"tim4",stm32l496::tim4::TIM4_BASE>{};

constexpr auto tim5 = stm32l496::timx::timx_t<"tim5",stm32l496::tim5::TIM5_BASE>{};

constexpr auto tim6 = stm32l496::timx_v3::timx_v3_t<"tim6",stm32l496::tim6::TIM6_BASE>{};

constexpr auto tim7 = stm32l496::timx_v3::timx_v3_t<"tim7",stm32l496::tim7::TIM7_BASE>{};

constexpr auto tim8 = stm32l496::tim8::tim8_t<stm32l496::tim8::TIM8_BASE>{};

constexpr auto tsc = stm32l496::tsc::tsc_t<stm32l496::tsc::TSC_BASE>{};

constexpr auto uart4 = stm32l496::usartx::usartx_t<"uart4",stm32l496::uart4::UART4_BASE>{};

constexpr auto uart5 = stm32l496::usartx::usartx_t<"uart5",stm32l496::uart5::UART5_BASE>{};

constexpr auto usart1 = stm32l496::usart1::usart1_t<stm32l496::usart1::USART1_BASE>{};

constexpr auto usart2 = stm32l496::usart2::usart2_t<stm32l496::usart2::USART2_BASE>{};

constexpr auto usart3 = stm32l496::usart3::usart3_t<stm32l496::usart3::USART3_BASE>{};

constexpr auto vrefbuf = stm32l496::vrefbuf::vrefbuf_t<stm32l496::vrefbuf::VREFBUF_BASE>{};

constexpr auto wwdg = stm32l496::wwdg::wwdg_t<stm32l496::wwdg::WWDG_BASE>{};

} // namespace mcu::stm32
