/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/usb.hpp"
namespace erworks::stm32::stm32l152 {
#include "../../../common/peripherals/usb_40b19ffe7f9f.inc"
} // namespace erworks::stm32::stm32l152
