/* File autogenerated with cmsis2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../access.hpp"
#include "../../bittypes.hpp"

namespace mcu::core {
namespace dwt {

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ctrl_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"numcomp", std::uint8_t, 31, 28>,
               groov::field<"notrcpkt", bool, 27, 27>,
               groov::field<"noexttrig", bool, 26, 26>,
               groov::field<"nocyccnt", bool, 25, 25>,
               groov::field<"noprfcnt", bool, 24, 24>,
               groov::field<"cycevtena", bool, 22, 22>,
               groov::field<"foldevtena", bool, 21, 21>,
               groov::field<"lsuevtena", bool, 20, 20>,
               groov::field<"sleepevtena", bool, 19, 19>,
               groov::field<"excevtena", bool, 18, 18>,
               groov::field<"cpievtena", bool, 17, 17>,
               groov::field<"exctrcena", bool, 16, 16>,
               groov::field<"pcsamplena", bool, 12, 12>,
               groov::field<"synctap", std::uint8_t, 11, 10>,
               groov::field<"cyctap", bool, 9, 9>,
               groov::field<"postinit", std::uint8_t, 8, 5>,
               groov::field<"postpreset", std::uint8_t, 4, 1>,
               groov::field<"cyccntena", bool, 0, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using cyccnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"cyccnt", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using cpicnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"cpicnt", std::uint8_t, 7, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using exccnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"exccnt", std::uint8_t, 7, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using sleepcnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"sleepcnt", std::uint8_t, 7, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using lsucnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"lsucnt", std::uint8_t, 7, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using foldcnt_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"foldcnt", std::uint8_t, 7, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using pcsr_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro
             groov::field<"pcsr", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using comp0_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"comp0", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using mask0_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"mask0", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using function0_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"function0", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using comp1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"comp1", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using mask1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"mask1", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using function1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"function1", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using comp2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"comp2", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using mask2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"mask2", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using function2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"function2", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using comp3_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"comp3", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using mask3_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"mask3", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using function3_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw
             groov::field<"function3", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using lar_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo
             groov::field<"lar", std::uint32_t, 31, 0>>;

template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using lsr_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro
             groov::field<"lsr", std::uint32_t, 31, 0>>;

template <std::uint32_t baseaddress>
using dwt_t =
  groov::group<"dwt",
               groov::mmio_bus<>,
               ctrl_tt<"ctrl", baseaddress, 0x0>,
               cyccnt_tt<"cyccnt", baseaddress, 0x4>,
               cpicnt_tt<"cpicnt", baseaddress, 0x8>,
               exccnt_tt<"exccnt", baseaddress, 0xc>,
               sleepcnt_tt<"sleepcnt", baseaddress, 0x10>,
               lsucnt_tt<"lsucnt", baseaddress, 0x14>,
               foldcnt_tt<"foldcnt", baseaddress, 0x18>,
               pcsr_tt<"pcsr", baseaddress, 0x1c>,
               comp0_tt<"comp0", baseaddress, 0x20>,
               mask0_tt<"mask0", baseaddress, 0x24>,
               function0_tt<"function0", baseaddress, 0x28>,
               comp1_tt<"comp1", baseaddress, 0x30>,
               mask1_tt<"mask1", baseaddress, 0x34>,
               function1_tt<"function1", baseaddress, 0x38>,
               comp2_tt<"comp2", baseaddress, 0x40>,
               mask2_tt<"mask2", baseaddress, 0x44>,
               function2_tt<"function2", baseaddress, 0x48>,
               comp3_tt<"comp3", baseaddress, 0x50>,
               mask3_tt<"mask3", baseaddress, 0x54>,
               function3_tt<"function3", baseaddress, 0x58>,
               lar_tt<"lar", baseaddress, 0xfb0>,
               lsr_tt<"lsr", baseaddress, 0xfb4>>;

inline constexpr std::uint32_t DWT_BASE = 0xE0001000U;

} // namespace dwt
} // namespace mcu::core
