/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/adc.hpp"
namespace erworks::stm32::stm32h5e4 {
#include "../../../common/peripherals/adc_83626effdc96.inc"
} // namespace erworks::stm32::stm32h5e4
