/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32n647/registers/hdp.hpp>

namespace stm32::stm32n647 {

namespace hdpx {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_ctrl_tt = regs::hdp_hdp_ctrl_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_mux_tt = regs::hdp_hdp_mux_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_val_tt = regs::hdp_hdp_val_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_gposet_tt = regs::hdp_hdp_gposet_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_gpoclr_tt = regs::hdp_hdp_gpoclr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using hdp_gpoval_tt = regs::hdp_hdp_gpoval_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using hdpx_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 hdp_ctrl_tt<"hdp_ctrl", baseaddress, 0x0>,
                 hdp_mux_tt<"hdp_mux", baseaddress, 0x4>,
                 hdp_val_tt<"hdp_val", baseaddress, 0x10>,
                 hdp_gposet_tt<"hdp_gposet", baseaddress, 0x14>,
                 hdp_gpoclr_tt<"hdp_gpoclr", baseaddress, 0x18>,
                 hdp_gpoval_tt<"hdp_gpoval", baseaddress, 0x1c>>;

} // namespace hdpx

} // namespace stm32::stm32n647
