/* File autogenerated with svd2groov for stm32h5f4 */
#pragma once

#include "peripherals/adc.hpp"
#include "peripherals/adf.hpp"
#include "peripherals/aes.hpp"
#include "peripherals/ccb.hpp"
#include "peripherals/cec.hpp"
#include "peripherals/comp.hpp"
#include "peripherals/cordic.hpp"
#include "peripherals/crc.hpp"
#include "peripherals/crs.hpp"
#include "peripherals/dac.hpp"
#include "peripherals/dbgmcu.hpp"
#include "peripherals/dcache.hpp"
#include "peripherals/dcmi.hpp"
#include "peripherals/dlybos1.hpp"
#include "peripherals/dma2d.hpp"
#include "peripherals/dts.hpp"
#include "peripherals/eth.hpp"
#include "peripherals/exti.hpp"
#include "peripherals/fdcan1.hpp"
#include "peripherals/flash.hpp"
#include "peripherals/fmac.hpp"
#include "peripherals/fmc.hpp"
#include "peripherals/gfxtim.hpp"
#include "peripherals/gpdma.hpp"
#include "peripherals/gpioa.hpp"
#include "peripherals/gpiob.hpp"
#include "peripherals/gpioc.hpp"
#include "peripherals/gpiod.hpp"
#include "peripherals/gpioe.hpp"
#include "peripherals/gpiof.hpp"
#include "peripherals/gpiog.hpp"
#include "peripherals/gpioh.hpp"
#include "peripherals/gpioi.hpp"
#include "peripherals/gpioj.hpp"
#include "peripherals/gpiok.hpp"
#include "peripherals/gtzc1.hpp"
#include "peripherals/gtzc1_mpcbb1.hpp"
#include "peripherals/gtzc1_mpcbb2.hpp"
#include "peripherals/gtzc1_mpcbb3.hpp"
#include "peripherals/hash.hpp"
#include "peripherals/i2c1.hpp"
#include "peripherals/i3c1.hpp"
#include "peripherals/icache.hpp"
#include "peripherals/iwdg.hpp"
#include "peripherals/jpeg.hpp"
#include "peripherals/lptim1.hpp"
#include "peripherals/lptim2.hpp"
#include "peripherals/lptim3.hpp"
#include "peripherals/lptim4.hpp"
#include "peripherals/lptim5.hpp"
#include "peripherals/lptim6.hpp"
#include "peripherals/lpuart1.hpp"
#include "peripherals/ltdc.hpp"
#include "peripherals/mdf.hpp"
#include "peripherals/octospi1.hpp"
#include "peripherals/octospim.hpp"
#include "peripherals/opamp1.hpp"
#include "peripherals/otfdec1.hpp"
#include "peripherals/otg_fs.hpp"
#include "peripherals/pka.hpp"
#include "peripherals/play.hpp"
#include "peripherals/pssi.hpp"
#include "peripherals/pwr.hpp"
#include "peripherals/ramcfg.hpp"
#include "peripherals/rcc.hpp"
#include "peripherals/rng.hpp"
#include "peripherals/rtc.hpp"
#include "peripherals/sai1.hpp"
#include "peripherals/sbs.hpp"
#include "peripherals/sdmmc1.hpp"
#include "peripherals/spi.hpp"
#include "peripherals/tamp.hpp"
#include "peripherals/tim1.hpp"
#include "peripherals/tim12.hpp"
#include "peripherals/tim13.hpp"
#include "peripherals/tim14.hpp"
#include "peripherals/tim15.hpp"
#include "peripherals/tim16.hpp"
#include "peripherals/tim17.hpp"
#include "peripherals/tim2.hpp"
#include "peripherals/tim3.hpp"
#include "peripherals/tim4.hpp"
#include "peripherals/tim5.hpp"
#include "peripherals/tim6.hpp"
#include "peripherals/tim7.hpp"
#include "peripherals/tim8.hpp"
#include "peripherals/ucpd.hpp"
#include "peripherals/usart1.hpp"
#include "peripherals/vrefbuf.hpp"
#include "peripherals/wwdg.hpp"

#include "peripherals/addresses.hpp"

namespace mcu::stm32 {

constexpr auto adc = stm32h5f4::adcx::adcx_t<"adc",stm32h5f4::adc::ADC_BASE>{};

constexpr auto adc3 = stm32h5f4::adcx::adcx_t<"adc3",stm32h5f4::adc3::ADC3_BASE>{};

constexpr auto adc3_s = stm32h5f4::adcx::adcx_t<"adc3_s",stm32h5f4::adc3_s::ADC3_S_BASE>{};

constexpr auto adc_s = stm32h5f4::adcx::adcx_t<"adc_s",stm32h5f4::adc_s::ADC_S_BASE>{};

constexpr auto adf = stm32h5f4::adfx::adfx_t<"adf",stm32h5f4::adf::ADF_BASE>{};

constexpr auto adf_s = stm32h5f4::adfx::adfx_t<"adf_s",stm32h5f4::adf_s::ADF_S_BASE>{};

constexpr auto aes = stm32h5f4::aesx::aesx_t<"aes",stm32h5f4::aes::AES_BASE>{};

constexpr auto aes_s = stm32h5f4::aesx::aesx_t<"aes_s",stm32h5f4::aes_s::AES_S_BASE>{};

constexpr auto ccb = stm32h5f4::ccbx::ccbx_t<"ccb",stm32h5f4::ccb::CCB_BASE>{};

constexpr auto ccb_s = stm32h5f4::ccbx::ccbx_t<"ccb_s",stm32h5f4::ccb_s::CCB_S_BASE>{};

constexpr auto cec = stm32h5f4::cecx::cecx_t<"cec",stm32h5f4::cec::CEC_BASE>{};

constexpr auto cec_s = stm32h5f4::cecx::cecx_t<"cec_s",stm32h5f4::cec_s::CEC_S_BASE>{};

constexpr auto comp = stm32h5f4::compx::compx_t<"comp",stm32h5f4::comp::COMP_BASE>{};

constexpr auto comp_s = stm32h5f4::compx::compx_t<"comp_s",stm32h5f4::comp_s::COMP_S_BASE>{};

constexpr auto cordic = stm32h5f4::cordicx::cordicx_t<"cordic",stm32h5f4::cordic::CORDIC_BASE>{};

constexpr auto cordic_s = stm32h5f4::cordicx::cordicx_t<"cordic_s",stm32h5f4::cordic_s::CORDIC_S_BASE>{};

constexpr auto crc = stm32h5f4::crcx::crcx_t<"crc",stm32h5f4::crc::CRC_BASE>{};

constexpr auto crc_s = stm32h5f4::crcx::crcx_t<"crc_s",stm32h5f4::crc_s::CRC_S_BASE>{};

constexpr auto crs = stm32h5f4::crsx::crsx_t<"crs",stm32h5f4::crs::CRS_BASE>{};

constexpr auto crs_s = stm32h5f4::crsx::crsx_t<"crs_s",stm32h5f4::crs_s::CRS_S_BASE>{};

constexpr auto dac = stm32h5f4::dacx::dacx_t<"dac",stm32h5f4::dac::DAC_BASE>{};

constexpr auto dac_s = stm32h5f4::dacx::dacx_t<"dac_s",stm32h5f4::dac_s::DAC_S_BASE>{};

constexpr auto dbgmcu = stm32h5f4::dbgmcux::dbgmcux_t<"dbgmcu",stm32h5f4::dbgmcu::DBGMCU_BASE>{};

constexpr auto dbgmcu_s = stm32h5f4::dbgmcux::dbgmcux_t<"dbgmcu_s",stm32h5f4::dbgmcu_s::DBGMCU_S_BASE>{};

constexpr auto dcache = stm32h5f4::dcachex::dcachex_t<"dcache",stm32h5f4::dcache::DCACHE_BASE>{};

constexpr auto dcache_s = stm32h5f4::dcachex::dcachex_t<"dcache_s",stm32h5f4::dcache_s::DCACHE_S_BASE>{};

constexpr auto dcmi = stm32h5f4::dcmix::dcmix_t<"dcmi",stm32h5f4::dcmi::DCMI_BASE>{};

constexpr auto dcmi_s = stm32h5f4::dcmix::dcmix_t<"dcmi_s",stm32h5f4::dcmi_s::DCMI_S_BASE>{};

constexpr auto dlybos1 = stm32h5f4::dlybos1x::dlybos1x_t<"dlybos1",stm32h5f4::dlybos1::DLYBOS1_BASE>{};

constexpr auto dlybos1_s = stm32h5f4::dlybos1x::dlybos1x_t<"dlybos1_s",stm32h5f4::dlybos1_s::DLYBOS1_S_BASE>{};

constexpr auto dlybos2 = stm32h5f4::dlybos1x::dlybos1x_t<"dlybos2",stm32h5f4::dlybos2::DLYBOS2_BASE>{};

constexpr auto dlybos2_s = stm32h5f4::dlybos1x::dlybos1x_t<"dlybos2_s",stm32h5f4::dlybos2_s::DLYBOS2_S_BASE>{};

constexpr auto dlybsd1 = stm32h5f4::dlybos1x::dlybos1x_t<"dlybsd1",stm32h5f4::dlybsd1::DLYBSD1_BASE>{};

constexpr auto dlybsd1_s = stm32h5f4::dlybos1x::dlybos1x_t<"dlybsd1_s",stm32h5f4::dlybsd1_s::DLYBSD1_S_BASE>{};

constexpr auto dlybsd2 = stm32h5f4::dlybos1x::dlybos1x_t<"dlybsd2",stm32h5f4::dlybsd2::DLYBSD2_BASE>{};

constexpr auto dlybsd2_s = stm32h5f4::dlybos1x::dlybos1x_t<"dlybsd2_s",stm32h5f4::dlybsd2_s::DLYBSD2_S_BASE>{};

constexpr auto dma2d = stm32h5f4::dma2dx::dma2dx_t<"dma2d",stm32h5f4::dma2d::DMA2D_BASE>{};

constexpr auto dma2d_s = stm32h5f4::dma2dx::dma2dx_t<"dma2d_s",stm32h5f4::dma2d_s::DMA2D_S_BASE>{};

constexpr auto dts = stm32h5f4::dtsx::dtsx_t<"dts",stm32h5f4::dts::DTS_BASE>{};

constexpr auto dts_s = stm32h5f4::dtsx::dtsx_t<"dts_s",stm32h5f4::dts_s::DTS_S_BASE>{};

constexpr auto eth = stm32h5f4::ethx::ethx_t<"eth",stm32h5f4::eth::ETH_BASE>{};

constexpr auto eth_s = stm32h5f4::ethx::ethx_t<"eth_s",stm32h5f4::eth_s::ETH_S_BASE>{};

constexpr auto exti = stm32h5f4::extix::extix_t<"exti",stm32h5f4::exti::EXTI_BASE>{};

constexpr auto exti_s = stm32h5f4::extix::extix_t<"exti_s",stm32h5f4::exti_s::EXTI_S_BASE>{};

constexpr auto fdcan1 = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan1",stm32h5f4::fdcan1::FDCAN1_BASE>{};

constexpr auto fdcan1_s = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan1_s",stm32h5f4::fdcan1_s::FDCAN1_S_BASE>{};

constexpr auto fdcan2 = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan2",stm32h5f4::fdcan2::FDCAN2_BASE>{};

constexpr auto fdcan2_s = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan2_s",stm32h5f4::fdcan2_s::FDCAN2_S_BASE>{};

constexpr auto fdcan3 = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan3",stm32h5f4::fdcan3::FDCAN3_BASE>{};

constexpr auto fdcan3_s = stm32h5f4::fdcan1x::fdcan1x_t<"fdcan3_s",stm32h5f4::fdcan3_s::FDCAN3_S_BASE>{};

constexpr auto flash = stm32h5f4::flashx::flashx_t<"flash",stm32h5f4::flash::FLASH_BASE>{};

constexpr auto flash_s = stm32h5f4::flashx::flashx_t<"flash_s",stm32h5f4::flash_s::FLASH_S_BASE>{};

constexpr auto fmac = stm32h5f4::fmacx::fmacx_t<"fmac",stm32h5f4::fmac::FMAC_BASE>{};

constexpr auto fmac_s = stm32h5f4::fmacx::fmacx_t<"fmac_s",stm32h5f4::fmac_s::FMAC_S_BASE>{};

constexpr auto fmc = stm32h5f4::fmcx::fmcx_t<"fmc",stm32h5f4::fmc::FMC_BASE>{};

constexpr auto fmc_s = stm32h5f4::fmcx::fmcx_t<"fmc_s",stm32h5f4::fmc_s::FMC_S_BASE>{};

constexpr auto gfxtim = stm32h5f4::gfxtimx::gfxtimx_t<"gfxtim",stm32h5f4::gfxtim::GFXTIM_BASE>{};

constexpr auto gfxtim_s = stm32h5f4::gfxtimx::gfxtimx_t<"gfxtim_s",stm32h5f4::gfxtim_s::GFXTIM_S_BASE>{};

constexpr auto gpdma = stm32h5f4::gpdmax::gpdmax_t<"gpdma",stm32h5f4::gpdma::GPDMA_BASE>{};

constexpr auto gpdma2 = stm32h5f4::gpdmax::gpdmax_t<"gpdma2",stm32h5f4::gpdma2::GPDMA2_BASE>{};

constexpr auto gpdma2_s = stm32h5f4::gpdmax::gpdmax_t<"gpdma2_s",stm32h5f4::gpdma2_s::GPDMA2_S_BASE>{};

constexpr auto gpdma_s = stm32h5f4::gpdmax::gpdmax_t<"gpdma_s",stm32h5f4::gpdma_s::GPDMA_S_BASE>{};

constexpr auto gpioa = stm32h5f4::gpioax::gpioax_t<"gpioa",stm32h5f4::gpioa::GPIOA_BASE>{};

constexpr auto gpioa_s = stm32h5f4::gpioax::gpioax_t<"gpioa_s",stm32h5f4::gpioa_s::GPIOA_S_BASE>{};

constexpr auto gpiob = stm32h5f4::gpiobx::gpiobx_t<"gpiob",stm32h5f4::gpiob::GPIOB_BASE>{};

constexpr auto gpiob_s = stm32h5f4::gpiobx::gpiobx_t<"gpiob_s",stm32h5f4::gpiob_s::GPIOB_S_BASE>{};

constexpr auto gpioc = stm32h5f4::gpiocx::gpiocx_t<"gpioc",stm32h5f4::gpioc::GPIOC_BASE>{};

constexpr auto gpioc_s = stm32h5f4::gpiocx::gpiocx_t<"gpioc_s",stm32h5f4::gpioc_s::GPIOC_S_BASE>{};

constexpr auto gpiod = stm32h5f4::gpiodx::gpiodx_t<"gpiod",stm32h5f4::gpiod::GPIOD_BASE>{};

constexpr auto gpiod_s = stm32h5f4::gpiodx::gpiodx_t<"gpiod_s",stm32h5f4::gpiod_s::GPIOD_S_BASE>{};

constexpr auto gpioe = stm32h5f4::gpioex::gpioex_t<"gpioe",stm32h5f4::gpioe::GPIOE_BASE>{};

constexpr auto gpioe_s = stm32h5f4::gpioex::gpioex_t<"gpioe_s",stm32h5f4::gpioe_s::GPIOE_S_BASE>{};

constexpr auto gpiof = stm32h5f4::gpiofx::gpiofx_t<"gpiof",stm32h5f4::gpiof::GPIOF_BASE>{};

constexpr auto gpiof_s = stm32h5f4::gpiofx::gpiofx_t<"gpiof_s",stm32h5f4::gpiof_s::GPIOF_S_BASE>{};

constexpr auto gpiog = stm32h5f4::gpiogx::gpiogx_t<"gpiog",stm32h5f4::gpiog::GPIOG_BASE>{};

constexpr auto gpiog_s = stm32h5f4::gpiogx::gpiogx_t<"gpiog_s",stm32h5f4::gpiog_s::GPIOG_S_BASE>{};

constexpr auto gpioh = stm32h5f4::gpiohx::gpiohx_t<"gpioh",stm32h5f4::gpioh::GPIOH_BASE>{};

constexpr auto gpioh_s = stm32h5f4::gpiohx::gpiohx_t<"gpioh_s",stm32h5f4::gpioh_s::GPIOH_S_BASE>{};

constexpr auto gpioi = stm32h5f4::gpioix::gpioix_t<"gpioi",stm32h5f4::gpioi::GPIOI_BASE>{};

constexpr auto gpioi_s = stm32h5f4::gpioix::gpioix_t<"gpioi_s",stm32h5f4::gpioi_s::GPIOI_S_BASE>{};

constexpr auto gpioj = stm32h5f4::gpiojx::gpiojx_t<"gpioj",stm32h5f4::gpioj::GPIOJ_BASE>{};

constexpr auto gpioj_s = stm32h5f4::gpiojx::gpiojx_t<"gpioj_s",stm32h5f4::gpioj_s::GPIOJ_S_BASE>{};

constexpr auto gpiok = stm32h5f4::gpiokx::gpiokx_t<"gpiok",stm32h5f4::gpiok::GPIOK_BASE>{};

constexpr auto gpiok_s = stm32h5f4::gpiokx::gpiokx_t<"gpiok_s",stm32h5f4::gpiok_s::GPIOK_S_BASE>{};

constexpr auto gtzc1_mpcbb1 = stm32h5f4::gtzc1_mpcbb1x::gtzc1_mpcbb1x_t<"gtzc1_mpcbb1",stm32h5f4::gtzc1_mpcbb1::GTZC1_MPCBB1_BASE>{};

constexpr auto gtzc1_mpcbb1_s = stm32h5f4::gtzc1_mpcbb1x::gtzc1_mpcbb1x_t<"gtzc1_mpcbb1_s",stm32h5f4::gtzc1_mpcbb1_s::GTZC1_MPCBB1_S_BASE>{};

constexpr auto gtzc1_mpcbb2 = stm32h5f4::gtzc1_mpcbb2x::gtzc1_mpcbb2x_t<"gtzc1_mpcbb2",stm32h5f4::gtzc1_mpcbb2::GTZC1_MPCBB2_BASE>{};

constexpr auto gtzc1_mpcbb2_s = stm32h5f4::gtzc1_mpcbb2x::gtzc1_mpcbb2x_t<"gtzc1_mpcbb2_s",stm32h5f4::gtzc1_mpcbb2_s::GTZC1_MPCBB2_S_BASE>{};

constexpr auto gtzc1_mpcbb3 = stm32h5f4::gtzc1_mpcbb3x::gtzc1_mpcbb3x_t<"gtzc1_mpcbb3",stm32h5f4::gtzc1_mpcbb3::GTZC1_MPCBB3_BASE>{};

constexpr auto gtzc1_mpcbb3_s = stm32h5f4::gtzc1_mpcbb3x::gtzc1_mpcbb3x_t<"gtzc1_mpcbb3_s",stm32h5f4::gtzc1_mpcbb3_s::GTZC1_MPCBB3_S_BASE>{};

constexpr auto gtzc1_tzic = stm32h5f4::gtzc1x_v2::gtzc1x_v2_t<"gtzc1_tzic",stm32h5f4::gtzc1_tzic::GTZC1_TZIC_BASE>{};

constexpr auto gtzc1_tzic_s = stm32h5f4::gtzc1x_v2::gtzc1x_v2_t<"gtzc1_tzic_s",stm32h5f4::gtzc1_tzic_s::GTZC1_TZIC_S_BASE>{};

constexpr auto gtzc1_tzsc = stm32h5f4::gtzc1x::gtzc1x_t<"gtzc1_tzsc",stm32h5f4::gtzc1_tzsc::GTZC1_TZSC_BASE>{};

constexpr auto gtzc1_tzsc_s = stm32h5f4::gtzc1x::gtzc1x_t<"gtzc1_tzsc_s",stm32h5f4::gtzc1_tzsc_s::GTZC1_TZSC_S_BASE>{};

constexpr auto hash = stm32h5f4::hashx::hashx_t<"hash",stm32h5f4::hash::HASH_BASE>{};

constexpr auto hash_s = stm32h5f4::hashx::hashx_t<"hash_s",stm32h5f4::hash_s::HASH_S_BASE>{};

constexpr auto i2c1 = stm32h5f4::i2c1x::i2c1x_t<"i2c1",stm32h5f4::i2c1::I2C1_BASE>{};

constexpr auto i2c1_s = stm32h5f4::i2c1x::i2c1x_t<"i2c1_s",stm32h5f4::i2c1_s::I2C1_S_BASE>{};

constexpr auto i2c2 = stm32h5f4::i2c1x::i2c1x_t<"i2c2",stm32h5f4::i2c2::I2C2_BASE>{};

constexpr auto i2c2_s = stm32h5f4::i2c1x::i2c1x_t<"i2c2_s",stm32h5f4::i2c2_s::I2C2_S_BASE>{};

constexpr auto i2c3 = stm32h5f4::i2c1x::i2c1x_t<"i2c3",stm32h5f4::i2c3::I2C3_BASE>{};

constexpr auto i2c3_s = stm32h5f4::i2c1x::i2c1x_t<"i2c3_s",stm32h5f4::i2c3_s::I2C3_S_BASE>{};

constexpr auto i2c4 = stm32h5f4::i2c1x::i2c1x_t<"i2c4",stm32h5f4::i2c4::I2C4_BASE>{};

constexpr auto i2c4_s = stm32h5f4::i2c1x::i2c1x_t<"i2c4_s",stm32h5f4::i2c4_s::I2C4_S_BASE>{};

constexpr auto i3c1 = stm32h5f4::i3c1x::i3c1x_t<"i3c1",stm32h5f4::i3c1::I3C1_BASE>{};

constexpr auto i3c1_s = stm32h5f4::i3c1x::i3c1x_t<"i3c1_s",stm32h5f4::i3c1_s::I3C1_S_BASE>{};

constexpr auto i3c2 = stm32h5f4::i3c1x::i3c1x_t<"i3c2",stm32h5f4::i3c2::I3C2_BASE>{};

constexpr auto i3c2_s = stm32h5f4::i3c1x::i3c1x_t<"i3c2_s",stm32h5f4::i3c2_s::I3C2_S_BASE>{};

constexpr auto icache = stm32h5f4::icachex::icachex_t<"icache",stm32h5f4::icache::ICACHE_BASE>{};

constexpr auto icache_s = stm32h5f4::icachex::icachex_t<"icache_s",stm32h5f4::icache_s::ICACHE_S_BASE>{};

constexpr auto iwdg = stm32h5f4::iwdgx::iwdgx_t<"iwdg",stm32h5f4::iwdg::IWDG_BASE>{};

constexpr auto iwdg_s = stm32h5f4::iwdgx::iwdgx_t<"iwdg_s",stm32h5f4::iwdg_s::IWDG_S_BASE>{};

constexpr auto jpeg = stm32h5f4::jpegx::jpegx_t<"jpeg",stm32h5f4::jpeg::JPEG_BASE>{};

constexpr auto jpeg_s = stm32h5f4::jpegx::jpegx_t<"jpeg_s",stm32h5f4::jpeg_s::JPEG_S_BASE>{};

constexpr auto lptim1 = stm32h5f4::lptim1x::lptim1x_t<"lptim1",stm32h5f4::lptim1::LPTIM1_BASE>{};

constexpr auto lptim1_s = stm32h5f4::lptim1x::lptim1x_t<"lptim1_s",stm32h5f4::lptim1_s::LPTIM1_S_BASE>{};

constexpr auto lptim2 = stm32h5f4::lptim2x::lptim2x_t<"lptim2",stm32h5f4::lptim2::LPTIM2_BASE>{};

constexpr auto lptim2_s = stm32h5f4::lptim2x::lptim2x_t<"lptim2_s",stm32h5f4::lptim2_s::LPTIM2_S_BASE>{};

constexpr auto lptim3 = stm32h5f4::lptim3x::lptim3x_t<"lptim3",stm32h5f4::lptim3::LPTIM3_BASE>{};

constexpr auto lptim3_s = stm32h5f4::lptim3x::lptim3x_t<"lptim3_s",stm32h5f4::lptim3_s::LPTIM3_S_BASE>{};

constexpr auto lptim4 = stm32h5f4::lptim4x::lptim4x_t<"lptim4",stm32h5f4::lptim4::LPTIM4_BASE>{};

constexpr auto lptim4_s = stm32h5f4::lptim4x::lptim4x_t<"lptim4_s",stm32h5f4::lptim4_s::LPTIM4_S_BASE>{};

constexpr auto lptim5 = stm32h5f4::lptim5x::lptim5x_t<"lptim5",stm32h5f4::lptim5::LPTIM5_BASE>{};

constexpr auto lptim5_s = stm32h5f4::lptim5x::lptim5x_t<"lptim5_s",stm32h5f4::lptim5_s::LPTIM5_S_BASE>{};

constexpr auto lptim6 = stm32h5f4::lptim6x::lptim6x_t<"lptim6",stm32h5f4::lptim6::LPTIM6_BASE>{};

constexpr auto lptim6_s = stm32h5f4::lptim6x::lptim6x_t<"lptim6_s",stm32h5f4::lptim6_s::LPTIM6_S_BASE>{};

constexpr auto lpuart1 = stm32h5f4::lpuart1x::lpuart1x_t<"lpuart1",stm32h5f4::lpuart1::LPUART1_BASE>{};

constexpr auto lpuart1_s = stm32h5f4::lpuart1x::lpuart1x_t<"lpuart1_s",stm32h5f4::lpuart1_s::LPUART1_S_BASE>{};

constexpr auto ltdc = stm32h5f4::ltdcx::ltdcx_t<"ltdc",stm32h5f4::ltdc::LTDC_BASE>{};

constexpr auto ltdc_s = stm32h5f4::ltdcx::ltdcx_t<"ltdc_s",stm32h5f4::ltdc_s::LTDC_S_BASE>{};

constexpr auto mdf = stm32h5f4::mdfx::mdfx_t<"mdf",stm32h5f4::mdf::MDF_BASE>{};

constexpr auto mdf_s = stm32h5f4::mdfx::mdfx_t<"mdf_s",stm32h5f4::mdf_s::MDF_S_BASE>{};

constexpr auto octospi1 = stm32h5f4::octospi1x::octospi1x_t<"octospi1",stm32h5f4::octospi1::OCTOSPI1_BASE>{};

constexpr auto octospi1_s = stm32h5f4::octospi1x::octospi1x_t<"octospi1_s",stm32h5f4::octospi1_s::OCTOSPI1_S_BASE>{};

constexpr auto octospi2 = stm32h5f4::octospi1x::octospi1x_t<"octospi2",stm32h5f4::octospi2::OCTOSPI2_BASE>{};

constexpr auto octospi2_s = stm32h5f4::octospi1x::octospi1x_t<"octospi2_s",stm32h5f4::octospi2_s::OCTOSPI2_S_BASE>{};

constexpr auto octospim = stm32h5f4::octospimx::octospimx_t<"octospim",stm32h5f4::octospim::OCTOSPIM_BASE>{};

constexpr auto octospim_s = stm32h5f4::octospimx::octospimx_t<"octospim_s",stm32h5f4::octospim_s::OCTOSPIM_S_BASE>{};

constexpr auto opamp1 = stm32h5f4::opamp1x::opamp1x_t<"opamp1",stm32h5f4::opamp1::OPAMP1_BASE>{};

constexpr auto opamp1_s = stm32h5f4::opamp1x::opamp1x_t<"opamp1_s",stm32h5f4::opamp1_s::OPAMP1_S_BASE>{};

constexpr auto otfdec1 = stm32h5f4::otfdec1x::otfdec1x_t<"otfdec1",stm32h5f4::otfdec1::OTFDEC1_BASE>{};

constexpr auto otfdec1_s = stm32h5f4::otfdec1x::otfdec1x_t<"otfdec1_s",stm32h5f4::otfdec1_s::OTFDEC1_S_BASE>{};

constexpr auto otfdec2 = stm32h5f4::otfdec1x::otfdec1x_t<"otfdec2",stm32h5f4::otfdec2::OTFDEC2_BASE>{};

constexpr auto otfdec2_s = stm32h5f4::otfdec1x::otfdec1x_t<"otfdec2_s",stm32h5f4::otfdec2_s::OTFDEC2_S_BASE>{};

constexpr auto otg_fs = stm32h5f4::otg_fsx::otg_fsx_t<"otg_fs",stm32h5f4::otg_fs::OTG_FS_BASE>{};

constexpr auto otg_fs_s = stm32h5f4::otg_fsx::otg_fsx_t<"otg_fs_s",stm32h5f4::otg_fs_s::OTG_FS_S_BASE>{};

constexpr auto pka = stm32h5f4::pkax::pkax_t<"pka",stm32h5f4::pka::PKA_BASE>{};

constexpr auto pka_s = stm32h5f4::pkax::pkax_t<"pka_s",stm32h5f4::pka_s::PKA_S_BASE>{};

constexpr auto play = stm32h5f4::playx::playx_t<"play",stm32h5f4::play::PLAY_BASE>{};

constexpr auto play_s = stm32h5f4::playx::playx_t<"play_s",stm32h5f4::play_s::PLAY_S_BASE>{};

constexpr auto pssi = stm32h5f4::pssix::pssix_t<"pssi",stm32h5f4::pssi::PSSI_BASE>{};

constexpr auto pssi_s = stm32h5f4::pssix::pssix_t<"pssi_s",stm32h5f4::pssi_s::PSSI_S_BASE>{};

constexpr auto pwr = stm32h5f4::pwrx::pwrx_t<"pwr",stm32h5f4::pwr::PWR_BASE>{};

constexpr auto pwr_s = stm32h5f4::pwrx::pwrx_t<"pwr_s",stm32h5f4::pwr_s::PWR_S_BASE>{};

constexpr auto ramcfg = stm32h5f4::ramcfgx::ramcfgx_t<"ramcfg",stm32h5f4::ramcfg::RAMCFG_BASE>{};

constexpr auto ramcfg_s = stm32h5f4::ramcfgx::ramcfgx_t<"ramcfg_s",stm32h5f4::ramcfg_s::RAMCFG_S_BASE>{};

constexpr auto rcc = stm32h5f4::rccx::rccx_t<"rcc",stm32h5f4::rcc::RCC_BASE>{};

constexpr auto rcc_s = stm32h5f4::rccx::rccx_t<"rcc_s",stm32h5f4::rcc_s::RCC_S_BASE>{};

constexpr auto rng = stm32h5f4::rngx::rngx_t<"rng",stm32h5f4::rng::RNG_BASE>{};

constexpr auto rng_s = stm32h5f4::rngx::rngx_t<"rng_s",stm32h5f4::rng_s::RNG_S_BASE>{};

constexpr auto rtc = stm32h5f4::rtcx::rtcx_t<"rtc",stm32h5f4::rtc::RTC_BASE>{};

constexpr auto rtc_s = stm32h5f4::rtcx::rtcx_t<"rtc_s",stm32h5f4::rtc_s::RTC_S_BASE>{};

constexpr auto saes = stm32h5f4::aesx::aesx_t<"saes",stm32h5f4::saes::SAES_BASE>{};

constexpr auto saes_s = stm32h5f4::aesx::aesx_t<"saes_s",stm32h5f4::saes_s::SAES_S_BASE>{};

constexpr auto sai1 = stm32h5f4::sai1x::sai1x_t<"sai1",stm32h5f4::sai1::SAI1_BASE>{};

constexpr auto sai1_s = stm32h5f4::sai1x::sai1x_t<"sai1_s",stm32h5f4::sai1_s::SAI1_S_BASE>{};

constexpr auto sai2 = stm32h5f4::sai1x::sai1x_t<"sai2",stm32h5f4::sai2::SAI2_BASE>{};

constexpr auto sai2_s = stm32h5f4::sai1x::sai1x_t<"sai2_s",stm32h5f4::sai2_s::SAI2_S_BASE>{};

constexpr auto sbs = stm32h5f4::sbsx::sbsx_t<"sbs",stm32h5f4::sbs::SBS_BASE>{};

constexpr auto sbs_s = stm32h5f4::sbsx::sbsx_t<"sbs_s",stm32h5f4::sbs_s::SBS_S_BASE>{};

constexpr auto sdmmc1 = stm32h5f4::sdmmc1x::sdmmc1x_t<"sdmmc1",stm32h5f4::sdmmc1::SDMMC1_BASE>{};

constexpr auto sdmmc1_s = stm32h5f4::sdmmc1x::sdmmc1x_t<"sdmmc1_s",stm32h5f4::sdmmc1_s::SDMMC1_S_BASE>{};

constexpr auto sdmmc2 = stm32h5f4::sdmmc1x::sdmmc1x_t<"sdmmc2",stm32h5f4::sdmmc2::SDMMC2_BASE>{};

constexpr auto sdmmc2_s = stm32h5f4::sdmmc1x::sdmmc1x_t<"sdmmc2_s",stm32h5f4::sdmmc2_s::SDMMC2_S_BASE>{};

constexpr auto spi = stm32h5f4::spix::spix_t<"spi",stm32h5f4::spi::SPI_BASE>{};

constexpr auto spi2 = stm32h5f4::spix::spix_t<"spi2",stm32h5f4::spi2::SPI2_BASE>{};

constexpr auto spi2_s = stm32h5f4::spix::spix_t<"spi2_s",stm32h5f4::spi2_s::SPI2_S_BASE>{};

constexpr auto spi3 = stm32h5f4::spix::spix_t<"spi3",stm32h5f4::spi3::SPI3_BASE>{};

constexpr auto spi3_s = stm32h5f4::spix::spix_t<"spi3_s",stm32h5f4::spi3_s::SPI3_S_BASE>{};

constexpr auto spi4 = stm32h5f4::spix::spix_t<"spi4",stm32h5f4::spi4::SPI4_BASE>{};

constexpr auto spi4_s = stm32h5f4::spix::spix_t<"spi4_s",stm32h5f4::spi4_s::SPI4_S_BASE>{};

constexpr auto spi5 = stm32h5f4::spix::spix_t<"spi5",stm32h5f4::spi5::SPI5_BASE>{};

constexpr auto spi5_s = stm32h5f4::spix::spix_t<"spi5_s",stm32h5f4::spi5_s::SPI5_S_BASE>{};

constexpr auto spi6 = stm32h5f4::spix::spix_t<"spi6",stm32h5f4::spi6::SPI6_BASE>{};

constexpr auto spi6_s = stm32h5f4::spix::spix_t<"spi6_s",stm32h5f4::spi6_s::SPI6_S_BASE>{};

constexpr auto spi_s = stm32h5f4::spix::spix_t<"spi_s",stm32h5f4::spi_s::SPI_S_BASE>{};

constexpr auto tamp = stm32h5f4::tampx::tampx_t<"tamp",stm32h5f4::tamp::TAMP_BASE>{};

constexpr auto tamp_s = stm32h5f4::tampx::tampx_t<"tamp_s",stm32h5f4::tamp_s::TAMP_S_BASE>{};

constexpr auto tim1 = stm32h5f4::tim1x::tim1x_t<"tim1",stm32h5f4::tim1::TIM1_BASE>{};

constexpr auto tim12 = stm32h5f4::tim12x::tim12x_t<"tim12",stm32h5f4::tim12::TIM12_BASE>{};

constexpr auto tim12_s = stm32h5f4::tim12x::tim12x_t<"tim12_s",stm32h5f4::tim12_s::TIM12_S_BASE>{};

constexpr auto tim13 = stm32h5f4::tim13x::tim13x_t<"tim13",stm32h5f4::tim13::TIM13_BASE>{};

constexpr auto tim13_s = stm32h5f4::tim13x::tim13x_t<"tim13_s",stm32h5f4::tim13_s::TIM13_S_BASE>{};

constexpr auto tim14 = stm32h5f4::tim14x::tim14x_t<"tim14",stm32h5f4::tim14::TIM14_BASE>{};

constexpr auto tim14_s = stm32h5f4::tim14x::tim14x_t<"tim14_s",stm32h5f4::tim14_s::TIM14_S_BASE>{};

constexpr auto tim15 = stm32h5f4::tim15x::tim15x_t<"tim15",stm32h5f4::tim15::TIM15_BASE>{};

constexpr auto tim15_s = stm32h5f4::tim15x::tim15x_t<"tim15_s",stm32h5f4::tim15_s::TIM15_S_BASE>{};

constexpr auto tim16 = stm32h5f4::tim16x::tim16x_t<"tim16",stm32h5f4::tim16::TIM16_BASE>{};

constexpr auto tim16_s = stm32h5f4::tim16x::tim16x_t<"tim16_s",stm32h5f4::tim16_s::TIM16_S_BASE>{};

constexpr auto tim17 = stm32h5f4::tim17x::tim17x_t<"tim17",stm32h5f4::tim17::TIM17_BASE>{};

constexpr auto tim17_s = stm32h5f4::tim17x::tim17x_t<"tim17_s",stm32h5f4::tim17_s::TIM17_S_BASE>{};

constexpr auto tim1_s = stm32h5f4::tim1x::tim1x_t<"tim1_s",stm32h5f4::tim1_s::TIM1_S_BASE>{};

constexpr auto tim2 = stm32h5f4::tim2x::tim2x_t<"tim2",stm32h5f4::tim2::TIM2_BASE>{};

constexpr auto tim2_s = stm32h5f4::tim2x::tim2x_t<"tim2_s",stm32h5f4::tim2_s::TIM2_S_BASE>{};

constexpr auto tim3 = stm32h5f4::tim3x::tim3x_t<"tim3",stm32h5f4::tim3::TIM3_BASE>{};

constexpr auto tim3_s = stm32h5f4::tim3x::tim3x_t<"tim3_s",stm32h5f4::tim3_s::TIM3_S_BASE>{};

constexpr auto tim4 = stm32h5f4::tim4x::tim4x_t<"tim4",stm32h5f4::tim4::TIM4_BASE>{};

constexpr auto tim4_s = stm32h5f4::tim4x::tim4x_t<"tim4_s",stm32h5f4::tim4_s::TIM4_S_BASE>{};

constexpr auto tim5 = stm32h5f4::tim5x::tim5x_t<"tim5",stm32h5f4::tim5::TIM5_BASE>{};

constexpr auto tim5_s = stm32h5f4::tim5x::tim5x_t<"tim5_s",stm32h5f4::tim5_s::TIM5_S_BASE>{};

constexpr auto tim6 = stm32h5f4::tim6x::tim6x_t<"tim6",stm32h5f4::tim6::TIM6_BASE>{};

constexpr auto tim6_s = stm32h5f4::tim6x::tim6x_t<"tim6_s",stm32h5f4::tim6_s::TIM6_S_BASE>{};

constexpr auto tim7 = stm32h5f4::tim7x::tim7x_t<"tim7",stm32h5f4::tim7::TIM7_BASE>{};

constexpr auto tim7_s = stm32h5f4::tim7x::tim7x_t<"tim7_s",stm32h5f4::tim7_s::TIM7_S_BASE>{};

constexpr auto tim8 = stm32h5f4::tim8x::tim8x_t<"tim8",stm32h5f4::tim8::TIM8_BASE>{};

constexpr auto tim8_s = stm32h5f4::tim8x::tim8x_t<"tim8_s",stm32h5f4::tim8_s::TIM8_S_BASE>{};

constexpr auto uart12 = stm32h5f4::usart1x::usart1x_t<"uart12",stm32h5f4::uart12::UART12_BASE>{};

constexpr auto uart12_s = stm32h5f4::usart1x::usart1x_t<"uart12_s",stm32h5f4::uart12_s::UART12_S_BASE>{};

constexpr auto uart4 = stm32h5f4::usart1x::usart1x_t<"uart4",stm32h5f4::uart4::UART4_BASE>{};

constexpr auto uart4_s = stm32h5f4::usart1x::usart1x_t<"uart4_s",stm32h5f4::uart4_s::UART4_S_BASE>{};

constexpr auto uart5 = stm32h5f4::usart1x::usart1x_t<"uart5",stm32h5f4::uart5::UART5_BASE>{};

constexpr auto uart5_s = stm32h5f4::usart1x::usart1x_t<"uart5_s",stm32h5f4::uart5_s::UART5_S_BASE>{};

constexpr auto uart7 = stm32h5f4::usart1x::usart1x_t<"uart7",stm32h5f4::uart7::UART7_BASE>{};

constexpr auto uart7_s = stm32h5f4::usart1x::usart1x_t<"uart7_s",stm32h5f4::uart7_s::UART7_S_BASE>{};

constexpr auto uart8 = stm32h5f4::usart1x::usart1x_t<"uart8",stm32h5f4::uart8::UART8_BASE>{};

constexpr auto uart8_s = stm32h5f4::usart1x::usart1x_t<"uart8_s",stm32h5f4::uart8_s::UART8_S_BASE>{};

constexpr auto uart9 = stm32h5f4::usart1x::usart1x_t<"uart9",stm32h5f4::uart9::UART9_BASE>{};

constexpr auto uart9_s = stm32h5f4::usart1x::usart1x_t<"uart9_s",stm32h5f4::uart9_s::UART9_S_BASE>{};

constexpr auto ucpd = stm32h5f4::ucpdx::ucpdx_t<"ucpd",stm32h5f4::ucpd::UCPD_BASE>{};

constexpr auto ucpd_s = stm32h5f4::ucpdx::ucpdx_t<"ucpd_s",stm32h5f4::ucpd_s::UCPD_S_BASE>{};

constexpr auto usart1 = stm32h5f4::usart1x::usart1x_t<"usart1",stm32h5f4::usart1::USART1_BASE>{};

constexpr auto usart10 = stm32h5f4::usart1x::usart1x_t<"usart10",stm32h5f4::usart10::USART10_BASE>{};

constexpr auto usart10_s = stm32h5f4::usart1x::usart1x_t<"usart10_s",stm32h5f4::usart10_s::USART10_S_BASE>{};

constexpr auto usart11 = stm32h5f4::usart1x::usart1x_t<"usart11",stm32h5f4::usart11::USART11_BASE>{};

constexpr auto usart11_s = stm32h5f4::usart1x::usart1x_t<"usart11_s",stm32h5f4::usart11_s::USART11_S_BASE>{};

constexpr auto usart1_s = stm32h5f4::usart1x::usart1x_t<"usart1_s",stm32h5f4::usart1_s::USART1_S_BASE>{};

constexpr auto usart2 = stm32h5f4::usart1x::usart1x_t<"usart2",stm32h5f4::usart2::USART2_BASE>{};

constexpr auto usart2_s = stm32h5f4::usart1x::usart1x_t<"usart2_s",stm32h5f4::usart2_s::USART2_S_BASE>{};

constexpr auto usart3 = stm32h5f4::usart1x::usart1x_t<"usart3",stm32h5f4::usart3::USART3_BASE>{};

constexpr auto usart3_s = stm32h5f4::usart1x::usart1x_t<"usart3_s",stm32h5f4::usart3_s::USART3_S_BASE>{};

constexpr auto usart6 = stm32h5f4::usart1x::usart1x_t<"usart6",stm32h5f4::usart6::USART6_BASE>{};

constexpr auto usart6_s = stm32h5f4::usart1x::usart1x_t<"usart6_s",stm32h5f4::usart6_s::USART6_S_BASE>{};

constexpr auto vrefbuf = stm32h5f4::vrefbufx::vrefbufx_t<"vrefbuf",stm32h5f4::vrefbuf::VREFBUF_BASE>{};

constexpr auto vrefbuf_s = stm32h5f4::vrefbufx::vrefbufx_t<"vrefbuf_s",stm32h5f4::vrefbuf_s::VREFBUF_S_BASE>{};

constexpr auto wwdg = stm32h5f4::wwdgx::wwdgx_t<"wwdg",stm32h5f4::wwdg::WWDG_BASE>{};

constexpr auto wwdg_s = stm32h5f4::wwdgx::wwdgx_t<"wwdg_s",stm32h5f4::wwdg_s::WWDG_S_BASE>{};

} // namespace mcu::stm32
