/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32wl33/registers/rng.hpp>

namespace stm32::stm32wl33 {

namespace rng {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_cr_tt = regs::rng_rng_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_sr_tt = regs::rng_rng_sr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_val_tt = regs::rng_rng_val_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_tcr_tt = regs::rng_rng_tcr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rng_itip_tt = regs::rng_rng_itip_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid0_tt = regs::rng_rngperiphid0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid1_tt = regs::rng_rngperiphid1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid2_tt = regs::rng_rngperiphid2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngperiphid3_tt = regs::rng_rngperiphid3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid0_tt = regs::rng_rngpcellid0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid1_tt = regs::rng_rngpcellid1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid2_tt = regs::rng_rngpcellid2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rngpcellid3_tt = regs::rng_rngpcellid3_v1_tt<name, baseaddress, offset>;

  template <std::uint32_t baseaddress>
  using rng_t =
    groov::group<"rng",
                 groov::mmio_bus<>,
                 rng_cr_tt<"rng_cr", baseaddress, 0x0>,
                 rng_sr_tt<"rng_sr", baseaddress, 0x4>,
                 rng_val_tt<"rng_val", baseaddress, 0x8>,
                 rng_tcr_tt<"rng_tcr", baseaddress, 0x80>,
                 rng_itip_tt<"rng_itip", baseaddress, 0x84>,
                 rngperiphid0_tt<"rngperiphid0", baseaddress, 0xfe0>,
                 rngperiphid1_tt<"rngperiphid1", baseaddress, 0xfe4>,
                 rngperiphid2_tt<"rngperiphid2", baseaddress, 0xfe8>,
                 rngperiphid3_tt<"rngperiphid3", baseaddress, 0xfec>,
                 rngpcellid0_tt<"rngpcellid0", baseaddress, 0xff0>,
                 rngpcellid1_tt<"rngpcellid1", baseaddress, 0xff4>,
                 rngpcellid2_tt<"rngpcellid2", baseaddress, 0xff8>,
                 rngpcellid3_tt<"rngpcellid3", baseaddress, 0xffc>>;

} // namespace rng

} // namespace stm32::stm32wl33
