/* File autogenerated with svd2groov for stm32f412 */
#pragma once

#include "peripherals/adc.hpp"
#include "peripherals/can.hpp"
#include "peripherals/crc.hpp"
#include "peripherals/dbg.hpp"
#include "peripherals/dfsdm.hpp"
#include "peripherals/dma.hpp"
#include "peripherals/exti.hpp"
#include "peripherals/flash.hpp"
#include "peripherals/fsmc.hpp"
#include "peripherals/gpio.hpp"
#include "peripherals/i2c.hpp"
#include "peripherals/iwdg.hpp"
#include "peripherals/pwr.hpp"
#include "peripherals/quadspi.hpp"
#include "peripherals/rcc.hpp"
#include "peripherals/rng.hpp"
#include "peripherals/rtc.hpp"
#include "peripherals/sdio.hpp"
#include "peripherals/spi.hpp"
#include "peripherals/syscfg.hpp"
#include "peripherals/tim.hpp"
#include "peripherals/usart.hpp"
#include "peripherals/usb_otg_fs.hpp"
#include "peripherals/wwdg.hpp"

#include "peripherals/addresses.hpp"

namespace mcu::stm32 {

constexpr auto adc1 = stm32f412::adc1::adc1_t<stm32f412::adc1::ADC1_BASE>{};

constexpr auto adc_common = stm32f412::adc_common::adc_common_t<stm32f412::adc_common::ADC_COMMON_BASE>{};

constexpr auto can1 = stm32f412::canx::canx_t<"can1",stm32f412::can1::CAN1_BASE>{};

constexpr auto can2 = stm32f412::canx::canx_t<"can2",stm32f412::can2::CAN2_BASE>{};

constexpr auto crc = stm32f412::crc::crc_t<stm32f412::crc::CRC_BASE>{};

constexpr auto dbg = stm32f412::dbg::dbg_t<stm32f412::dbg::DBG_BASE>{};

constexpr auto dfsdm = stm32f412::dfsdm::dfsdm_t<stm32f412::dfsdm::DFSDM_BASE>{};

constexpr auto dma1 = stm32f412::dmax::dmax_t<"dma1",stm32f412::dma1::DMA1_BASE>{};

constexpr auto dma2 = stm32f412::dmax::dmax_t<"dma2",stm32f412::dma2::DMA2_BASE>{};

constexpr auto exti = stm32f412::exti::exti_t<stm32f412::exti::EXTI_BASE>{};

constexpr auto flash = stm32f412::flash::flash_t<stm32f412::flash::FLASH_BASE>{};

constexpr auto fsmc = stm32f412::fsmc::fsmc_t<stm32f412::fsmc::FSMC_BASE>{};

constexpr auto gpioa = stm32f412::gpioa::gpioa_t<stm32f412::gpioa::GPIOA_BASE>{};

constexpr auto gpiob = stm32f412::gpiob::gpiob_t<stm32f412::gpiob::GPIOB_BASE>{};

constexpr auto gpioc = stm32f412::gpiox::gpiox_t<"gpioc",stm32f412::gpioc::GPIOC_BASE>{};

constexpr auto gpiod = stm32f412::gpiox::gpiox_t<"gpiod",stm32f412::gpiod::GPIOD_BASE>{};

constexpr auto gpioe = stm32f412::gpiox::gpiox_t<"gpioe",stm32f412::gpioe::GPIOE_BASE>{};

constexpr auto gpiof = stm32f412::gpiox::gpiox_t<"gpiof",stm32f412::gpiof::GPIOF_BASE>{};

constexpr auto gpiog = stm32f412::gpiox::gpiox_t<"gpiog",stm32f412::gpiog::GPIOG_BASE>{};

constexpr auto gpioh = stm32f412::gpiox::gpiox_t<"gpioh",stm32f412::gpioh::GPIOH_BASE>{};

constexpr auto i2c1 = stm32f412::i2cx::i2cx_t<"i2c1",stm32f412::i2c1::I2C1_BASE>{};

constexpr auto i2c2 = stm32f412::i2cx::i2cx_t<"i2c2",stm32f412::i2c2::I2C2_BASE>{};

constexpr auto i2c3 = stm32f412::i2cx::i2cx_t<"i2c3",stm32f412::i2c3::I2C3_BASE>{};

constexpr auto i2c4 = stm32f412::i2c4::i2c4_t<stm32f412::i2c4::I2C4_BASE>{};

constexpr auto i2s2ext = stm32f412::spix::spix_t<"i2s2ext",stm32f412::i2s2ext::I2S2EXT_BASE>{};

constexpr auto i2s3ext = stm32f412::spix::spix_t<"i2s3ext",stm32f412::i2s3ext::I2S3EXT_BASE>{};

constexpr auto iwdg = stm32f412::iwdg::iwdg_t<stm32f412::iwdg::IWDG_BASE>{};

constexpr auto otg_fs_device = stm32f412::otg_fs_device::otg_fs_device_t<stm32f412::otg_fs_device::OTG_FS_DEVICE_BASE>{};

constexpr auto otg_fs_global = stm32f412::otg_fs_global::otg_fs_global_t<stm32f412::otg_fs_global::OTG_FS_GLOBAL_BASE>{};

constexpr auto otg_fs_host = stm32f412::otg_fs_host::otg_fs_host_t<stm32f412::otg_fs_host::OTG_FS_HOST_BASE>{};

constexpr auto otg_fs_pwrclk = stm32f412::otg_fs_pwrclk::otg_fs_pwrclk_t<stm32f412::otg_fs_pwrclk::OTG_FS_PWRCLK_BASE>{};

constexpr auto pwr = stm32f412::pwr::pwr_t<stm32f412::pwr::PWR_BASE>{};

constexpr auto quadspi = stm32f412::quadspi::quadspi_t<stm32f412::quadspi::QUADSPI_BASE>{};

constexpr auto rcc = stm32f412::rcc::rcc_t<stm32f412::rcc::RCC_BASE>{};

constexpr auto rng = stm32f412::rng::rng_t<stm32f412::rng::RNG_BASE>{};

constexpr auto rtc = stm32f412::rtc::rtc_t<stm32f412::rtc::RTC_BASE>{};

constexpr auto sdio = stm32f412::sdio::sdio_t<stm32f412::sdio::SDIO_BASE>{};

constexpr auto spi1 = stm32f412::spix::spix_t<"spi1",stm32f412::spi1::SPI1_BASE>{};

constexpr auto spi2 = stm32f412::spix::spix_t<"spi2",stm32f412::spi2::SPI2_BASE>{};

constexpr auto spi3 = stm32f412::spix::spix_t<"spi3",stm32f412::spi3::SPI3_BASE>{};

constexpr auto spi4 = stm32f412::spix::spix_t<"spi4",stm32f412::spi4::SPI4_BASE>{};

constexpr auto spi5 = stm32f412::spix::spix_t<"spi5",stm32f412::spi5::SPI5_BASE>{};

constexpr auto syscfg = stm32f412::syscfg::syscfg_t<stm32f412::syscfg::SYSCFG_BASE>{};

constexpr auto tim1 = stm32f412::timx::timx_t<"tim1",stm32f412::tim1::TIM1_BASE>{};

constexpr auto tim10 = stm32f412::tim10::tim10_t<stm32f412::tim10::TIM10_BASE>{};

constexpr auto tim11 = stm32f412::tim11::tim11_t<stm32f412::tim11::TIM11_BASE>{};

constexpr auto tim12 = stm32f412::tim12::tim12_t<stm32f412::tim12::TIM12_BASE>{};

constexpr auto tim13 = stm32f412::timx_v4::timx_v4_t<"tim13",stm32f412::tim13::TIM13_BASE>{};

constexpr auto tim14 = stm32f412::timx_v4::timx_v4_t<"tim14",stm32f412::tim14::TIM14_BASE>{};

constexpr auto tim2 = stm32f412::tim2::tim2_t<stm32f412::tim2::TIM2_BASE>{};

constexpr auto tim3 = stm32f412::timx_v2::timx_v2_t<"tim3",stm32f412::tim3::TIM3_BASE>{};

constexpr auto tim4 = stm32f412::timx_v2::timx_v2_t<"tim4",stm32f412::tim4::TIM4_BASE>{};

constexpr auto tim5 = stm32f412::tim5::tim5_t<stm32f412::tim5::TIM5_BASE>{};

constexpr auto tim6 = stm32f412::timx_v3::timx_v3_t<"tim6",stm32f412::tim6::TIM6_BASE>{};

constexpr auto tim7 = stm32f412::timx_v3::timx_v3_t<"tim7",stm32f412::tim7::TIM7_BASE>{};

constexpr auto tim8 = stm32f412::timx::timx_t<"tim8",stm32f412::tim8::TIM8_BASE>{};

constexpr auto tim9 = stm32f412::tim9::tim9_t<stm32f412::tim9::TIM9_BASE>{};

constexpr auto usart1 = stm32f412::usartx::usartx_t<"usart1",stm32f412::usart1::USART1_BASE>{};

constexpr auto usart2 = stm32f412::usartx::usartx_t<"usart2",stm32f412::usart2::USART2_BASE>{};

constexpr auto usart3 = stm32f412::usartx::usartx_t<"usart3",stm32f412::usart3::USART3_BASE>{};

constexpr auto usart6 = stm32f412::usartx::usartx_t<"usart6",stm32f412::usart6::USART6_BASE>{};

constexpr auto wwdg = stm32f412::wwdg::wwdg_t<stm32f412::wwdg::WWDG_BASE>{};

} // namespace mcu::stm32
