/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/flash.hpp"
namespace erworks::stm32::stm32wb55_cm0p {
#include "../../../common/peripherals/flash_7de4800174fa.inc"
} // namespace erworks::stm32::stm32wb55_cm0p
