/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/tim.hpp"
namespace erworks::stm32::stm32wb55_cm0p {
#include "../../../common/peripherals/tim_581c5c94e658.inc"
} // namespace erworks::stm32::stm32wb55_cm0p
