/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/lptim.hpp"
namespace mcu::stm32::stm32u031 {
#include "../../common/peripherals/lptim_2f05871c95db.inc"
} // namespace mcu::stm32::stm32u031
