/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dma.hpp"
namespace erworks::stm32::stm32l4a6 {
#include "../../../common/peripherals/dma_992ac603fad3.inc"
} // namespace erworks::stm32::stm32l4a6
