/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/ucpd.hpp"
namespace erworks::stm32::stm32g0c1 {
#include "../../../common/peripherals/ucpd_bfcd7010577b.inc"
} // namespace erworks::stm32::stm32g0c1
