/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/rtc.hpp"
namespace erworks::stm32::stm32c051 {
#include "../../../common/peripherals/rtc_d2aa5701f0c0.inc"
} // namespace erworks::stm32::stm32c051
