/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/pwr.hpp"
namespace mcu::stm32::stm32c071 {
#include "../../common/peripherals/pwr_ffc00f989615.inc"
} // namespace mcu::stm32::stm32c071
