/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/tim3.hpp"
namespace mcu::stm32::stm32c071 {
#include "../../common/peripherals/tim3_1d74dadd7c36.inc"
} // namespace mcu::stm32::stm32c071
