/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/usart.hpp"
namespace mcu::stm32::stm32f439 {
#include "../../common/peripherals/usart_3889214345c0.inc"
} // namespace mcu::stm32::stm32f439
