/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/adc.hpp"
namespace erworks::stm32::stm32f215 {
#include "../../../common/peripherals/adc_272f268f42aa.inc"
} // namespace erworks::stm32::stm32f215
