/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/crs.hpp"
namespace mcu::stm32::stm32l412 {
#include "../../common/peripherals/crs_1f0044658dd0.inc"
} // namespace mcu::stm32::stm32l412
