/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/access.hpp"
#include "../../common/bittypes.hpp"
namespace erworks::stm32::stm32wba52 {
namespace regs {

// tim16_tim_af1_v1: TIM_AF1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_af1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 14, common::access::ro>,
               groov::field<"bkcmp4p", bool, 13, 13>,
               groov::field<"bkcmp3p", bool, 12, 12>,
               groov::field<"bkcmp2p", bool, 11, 11>,
               groov::field<"bkcmp1p", bool, 10, 10>,
               groov::field<"bkinp", bool, 9, 9>,
               groov::field<"bkcmp8e", common::bit_enable, 8, 8>,
               groov::field<"bkcmp7e", common::bit_enable, 7, 7>,
               groov::field<"bkcmp6e", common::bit_enable, 6, 6>,
               groov::field<"bkcmp5e", common::bit_enable, 5, 5>,
               groov::field<"bkcmp4e", common::bit_enable, 4, 4>,
               groov::field<"bkcmp3e", common::bit_enable, 3, 3>,
               groov::field<"bkcmp2e", common::bit_enable, 2, 2>,
               groov::field<"bkcmp1e", common::bit_enable, 1, 1>,
               groov::field<"bkine", bool, 0, 0>>;

// tim16_tim_bdtr_v1: TIM_BDTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_bdtr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 29, common::access::ro>,
               groov::field<"bkbid", bool, 28, 28>,
               groov::field<"reserved1", bool, 27, 27, common::access::ro>,
               groov::field<"bkdsrm", bool, 26, 26>,
               groov::field<"reserved0", std::uint8_t, 25, 20, common::access::ro>,
               groov::field<"bkf", std::uint8_t, 19, 16>,
               groov::field<"moe", bool, 15, 15>,
               groov::field<"aoe", bool, 14, 14>,
               groov::field<"bkp", bool, 13, 13>,
               groov::field<"bke", bool, 12, 12>,
               groov::field<"ossr", bool, 11, 11>,
               groov::field<"ossi", bool, 10, 10>,
               groov::field<"lock", std::uint8_t, 9, 8>,
               groov::field<"dtg", std::uint8_t, 7, 0>>;

// tim16_tim_ccer_v1: TIM_CCER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_ccer_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"cc1np", bool, 3, 3>,
               groov::field<"cc1ne", bool, 2, 2>,
               groov::field<"cc1p", bool, 1, 1>,
               groov::field<"cc1e", common::bit_enable, 0, 0>>;

// tim16_tim_ccmr1_v1: TIM_CCMR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_ccmr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"ic1f", std::uint8_t, 7, 4>,
               groov::field<"ic1psc", std::uint8_t, 3, 2>,
               groov::field<"cc1s", std::uint8_t, 1, 0>>;

// tim16_tim_ccmr1_alternate1_v1: TIM_CCMR1_ALTERNATE1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_ccmr1_alternate1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"oc1m_1", bool, 16, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"oc1ce", bool, 7, 7>,
               groov::field<"oc1m", std::uint8_t, 6, 4>,
               groov::field<"oc1pe", common::bit_enable, 3, 3>,
               groov::field<"oc1fe", common::bit_enable, 2, 2>,
               groov::field<"cc1s", std::uint8_t, 1, 0>>;

// tim16_tim_cr1_v1: TIM_CR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_cr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 13, common::access::ro>,
               groov::field<"dithen", common::bit_enable, 12, 12>,
               groov::field<"uifremap", bool, 11, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"ckd", std::uint8_t, 9, 8>,
               groov::field<"arpe", common::bit_enable, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 4, common::access::ro>,
               groov::field<"opm", bool, 3, 3>,
               groov::field<"urs", bool, 2, 2>,
               groov::field<"udis", common::bit_nenable, 1, 1>,
               groov::field<"cen", common::bit_enable, 0, 0>>;

// tim16_tim_cr2_v1: TIM_CR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_cr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 10, common::access::ro>,
               groov::field<"ois1n", bool, 9, 9>,
               groov::field<"ois1", bool, 8, 8>,
               groov::field<"reserved1", std::uint8_t, 7, 4, common::access::ro>,
               groov::field<"ccds", bool, 3, 3>,
               groov::field<"ccus", bool, 2, 2>,
               groov::field<"reserved0", bool, 1, 1, common::access::ro>,
               groov::field<"ccpc", bool, 0, 0>>;

// tim16_tim_dier_v1: TIM_DIER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_dier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 10, common::access::ro>,
               groov::field<"cc1de", common::bit_enable, 9, 9>,
               groov::field<"ude", common::bit_enable, 8, 8>,
               groov::field<"bie", common::bit_enable, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"comie", common::bit_enable, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1ie", common::bit_enable, 1, 1>,
               groov::field<"uie", common::bit_enable, 0, 0>>;

// tim16_tim_egr_v1: TIM_EGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_egr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved2", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"bg", bool, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"comg", bool, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1g", bool, 1, 1>,
               groov::field<"ug", bool, 0, 0>>;

// tim16_tim_or1_v1: TIM_OR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_or1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 2, common::access::ro>,
               groov::field<"hse32en", common::bit_enable, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

// tim16_tim_rcr_v1: TIM_RCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_rcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"rep", std::uint8_t, 7, 0>>;

// tim16_tim_sr_v1: TIM_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint32_t, 31, 10, common::access::ro>,
               groov::field<"cc1of", bool, 9, 9>,
               groov::field<"reserved2", bool, 8, 8, common::access::ro>,
               groov::field<"bif", bool, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"comif", bool, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1if", bool, 1, 1>,
               groov::field<"uif", bool, 0, 0>>;

// tim16_tim_tisel_v1: TIM_TISEL
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim_tisel_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"ti1sel", std::uint8_t, 3, 0>>;

} // namespace regs

namespace tim16x {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_cr1_tt = regs::tim16_tim_cr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_cr2_tt = regs::tim16_tim_cr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_dier_tt = regs::tim16_tim_dier_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_sr_tt = regs::tim16_tim_sr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_egr_tt = regs::tim16_tim_egr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_ccmr1_tt = regs::tim16_tim_ccmr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_ccmr1_alternate1_tt = regs::tim16_tim_ccmr1_alternate1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_ccer_tt = regs::tim16_tim_ccer_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_cnt_tt = regs::tim1_tim1_cnt_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_psc_tt = regs::tim1_tim1_psc_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_arr_tt = regs::tim1_tim1_arr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_rcr_tt = regs::tim16_tim_rcr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_ccr1_tt = regs::tim1_tim1_ccr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_bdtr_tt = regs::tim16_tim_bdtr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_dtr2_tt = regs::tim1_tim1_dtr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_tisel_tt = regs::tim16_tim_tisel_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_af1_tt = regs::tim16_tim_af1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_af2_tt = regs::tim2_tim_af2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_or1_tt = regs::tim16_tim_or1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_dcr_tt = regs::tim1_tim1_dcr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using tim_dmar_tt = regs::tim1_tim1_dmar_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim16x_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 tim_cr1_tt<"tim_cr1", baseaddress, 0x0>,
                 tim_cr2_tt<"tim_cr2", baseaddress, 0x4>,
                 tim_dier_tt<"tim_dier", baseaddress, 0xc>,
                 tim_sr_tt<"tim_sr", baseaddress, 0x10>,
                 tim_egr_tt<"tim_egr", baseaddress, 0x14>,
                 tim_ccmr1_tt<"tim_ccmr1", baseaddress, 0x18>,
                 tim_ccmr1_alternate1_tt<"tim_ccmr1_alternate1", baseaddress, 0x18>,
                 tim_ccer_tt<"tim_ccer", baseaddress, 0x20>,
                 tim_cnt_tt<"tim_cnt", baseaddress, 0x24>,
                 tim_psc_tt<"tim_psc", baseaddress, 0x28>,
                 tim_arr_tt<"tim_arr", baseaddress, 0x2c>,
                 tim_rcr_tt<"tim_rcr", baseaddress, 0x30>,
                 tim_ccr1_tt<"tim_ccr1", baseaddress, 0x34>,
                 tim_bdtr_tt<"tim_bdtr", baseaddress, 0x44>,
                 tim_dtr2_tt<"tim_dtr2", baseaddress, 0x54>,
                 tim_tisel_tt<"tim_tisel", baseaddress, 0x5c>,
                 tim_af1_tt<"tim_af1", baseaddress, 0x60>,
                 tim_af2_tt<"tim_af2", baseaddress, 0x64>,
                 tim_or1_tt<"tim_or1", baseaddress, 0x68>,
                 tim_dcr_tt<"tim_dcr", baseaddress, 0x3dc>,
                 tim_dmar_tt<"tim_dmar", baseaddress, 0x3e0>>;

} // namespace tim16x
} // namespace erworks::stm32::stm32wba52
