/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dbg.hpp"
namespace mcu::stm32::stm32f446 {
#include "../../../common/peripherals/dbg_d0a6576a81f7.inc"
} // namespace mcu::stm32::stm32f446
