/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/adc.hpp"
namespace erworks::stm32::stm32f100 {
#include "../../../common/peripherals/adc_3395b0ddf47d.inc"
} // namespace erworks::stm32::stm32f100
