/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/lptim.hpp"
namespace erworks::stm32::stm32l422 {
#include "../../../common/peripherals/lptim_82b56d0c48e4.inc"
} // namespace erworks::stm32::stm32l422
