/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/fmc.hpp"
namespace mcu::stm32::stm32u595 {
#include "../../../common/peripherals/fmc_b81e45c7ce8f.inc"
} // namespace mcu::stm32::stm32u595
