/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/gpdma.hpp"
namespace erworks::stm32::stm32u595 {
#include "../../../common/peripherals/gpdma_a9e1d0bd287e.inc"
} // namespace erworks::stm32::stm32u595
