/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include "../access.hpp"
#include "../bittypes.hpp"

namespace erworks::stm32::regs {

// iwdg_ewcr_v1: EWCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_ewcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ewie", common::bit_enable, 15, 15>,
               groov::field<"ewic", bool, 14, 14>,
               groov::field<"reserved0", std::uint8_t, 13, 12, common::access::ro>,
               groov::field<"ewit", std::uint16_t, 11, 0>>;

// iwdg_hwcfgr_v1: HWCFGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_hwcfgr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"pr_default", std::uint8_t, 7, 4>,
               groov::field<"window", std::uint8_t, 3, 0>>;

// iwdg_ipidr_v1: IPIDR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_ipidr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"ipid", std::uint32_t, 31, 0>>;

// iwdg_iwdg_ewcr_v1: IWDG_EWCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_ewcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ewie", common::bit_enable, 15, 15>,
               groov::field<"ewic", bool, 14, 14, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 13, 12, common::access::ro>,
               groov::field<"ewit", std::uint16_t, 11, 0>>;

// iwdg_iwdg_ewcr_v2: IWDG_EWCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_ewcr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ewie", common::bit_enable, 15, 15>,
               groov::field<"reserved0", std::uint8_t, 14, 12, common::access::ro>,
               groov::field<"ewit", std::uint16_t, 11, 0>>;

// iwdg_iwdg_icr_v1: IWDG_ICR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_icr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ewic", bool, 15, 15>,
               groov::field<"reserved0", std::uint16_t, 14, 0, common::access::ro>>;

// iwdg_iwdg_kr_v1: IWDG_KR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_kr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"key", std::uint16_t, 15, 0, common::access::wo>>;

// iwdg_iwdg_kr_v2: IWDG_KR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_kr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"key", std::uint16_t, 15, 0>>;

// iwdg_iwdg_pr_v1: IWDG_PR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_pr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"pr", std::uint8_t, 2, 0>>;

// iwdg_iwdg_pr_v2: IWDG_PR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_pr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"pr", std::uint8_t, 3, 0>>;

// iwdg_iwdg_rlr_v1: IWDG_RLR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_rlr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"rl", std::uint16_t, 11, 0>>;

// iwdg_iwdg_sr_v1: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"wvu", bool, 2, 2, common::access::ro>,
               groov::field<"rvu", bool, 1, 1, common::access::ro>,
               groov::field<"pvu", bool, 0, 0, common::access::ro>>;

// iwdg_iwdg_sr_v2: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 3>,
               groov::field<"wvu", bool, 2, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_iwdg_sr_v3: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v3_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"ewif", bool, 14, 14, common::access::ro>,
               groov::field<"reserved0", std::uint16_t, 13, 4, common::access::ro>,
               groov::field<"ewu", bool, 3, 3, common::access::ro>,
               groov::field<"wvu", bool, 2, 2, common::access::ro>,
               groov::field<"rvu", bool, 1, 1, common::access::ro>,
               groov::field<"pvu", bool, 0, 0, common::access::ro>>;

// iwdg_iwdg_sr_v4: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v4_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved2", std::uint32_t, 31, 15>,
               groov::field<"ewif", bool, 14, 14>,
               groov::field<"reserved1", std::uint8_t, 13, 9>,
               groov::field<"onf", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 4>,
               groov::field<"ewu", bool, 3, 3>,
               groov::field<"wvu", bool, 2, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_iwdg_sr_v5: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v5_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 15, common::access::ro>,
               groov::field<"ewif", bool, 14, 14, common::access::ro>,
               groov::field<"reserved1", std::uint8_t, 13, 9, common::access::ro>,
               groov::field<"onf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 4, common::access::ro>,
               groov::field<"ewu", bool, 3, 3, common::access::ro>,
               groov::field<"wvu", bool, 2, 2, common::access::ro>,
               groov::field<"rvu", bool, 1, 1, common::access::ro>,
               groov::field<"pvu", bool, 0, 0, common::access::ro>>;

// iwdg_iwdg_sr_v6: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v6_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ewif", bool, 15, 15, common::access::ro>,
               groov::field<"reserved1", std::uint8_t, 14, 9, common::access::ro>,
               groov::field<"onf", bool, 8, 8, common::access::ro>,
               groov::field<"reserved0", std::uint8_t, 7, 4, common::access::ro>,
               groov::field<"ewu", bool, 3, 3, common::access::ro>,
               groov::field<"wvu", bool, 2, 2, common::access::ro>,
               groov::field<"rvu", bool, 1, 1, common::access::ro>,
               groov::field<"pvu", bool, 0, 0, common::access::ro>>;

// iwdg_iwdg_sr_v7: IWDG_SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_sr_v7_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 15>,
               groov::field<"ewif", bool, 14, 14>,
               groov::field<"reserved0", std::uint16_t, 13, 4>,
               groov::field<"ewu", bool, 3, 3>,
               groov::field<"wvu", bool, 2, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_iwdg_winr_v1: IWDG_WINR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_iwdg_winr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"win", std::uint16_t, 11, 0>>;

// iwdg_kr_v1: KR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_kr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"key", std::uint16_t, 15, 0>>;

// iwdg_pr_v1: PR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_pr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"pr", std::uint8_t, 2, 0>>;

// iwdg_pr_v2: PR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_pr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, common::access::ro>,
               groov::field<"pr", std::uint8_t, 3, 0>>;

// iwdg_rlr_v1: RLR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_rlr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"rl", std::uint16_t, 11, 0>>;

// iwdg_sidr_v1: SIDR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_sidr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"sid", std::uint32_t, 31, 0>>;

// iwdg_sr_v1: SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 3>,
               groov::field<"wvu", bool, 2, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_sr_v2: SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_sr_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_sr_v3: SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_sr_v3_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved1", std::uint32_t, 31, 15>,
               groov::field<"ewif", bool, 14, 14>,
               groov::field<"reserved0", std::uint16_t, 13, 4>,
               groov::field<"ewu", bool, 3, 3>,
               groov::field<"wvu", bool, 2, 2>,
               groov::field<"rvu", bool, 1, 1>,
               groov::field<"pvu", bool, 0, 0>>;

// iwdg_verr_v1: VERR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_verr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 8>,
               groov::field<"majrev", std::uint8_t, 7, 4>,
               groov::field<"minrev", std::uint8_t, 3, 0>>;

// iwdg_winr_v1: WINR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using iwdg_winr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"win", std::uint16_t, 11, 0>>;

} // namespace erworks::stm32::regs
