/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include "../access.hpp"
#include "../bittypes.hpp"

namespace mcu::stm32::regs {

// tim16_af1_v1: AF1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_af1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 14, common::access::ro>,
               groov::field<"af1_13_12", std::uint8_t, 13, 12>,
               groov::field<"bkcmp2p", bool, 11, 11>,
               groov::field<"bkcmp1p", bool, 10, 10>,
               groov::field<"bkinp", bool, 9, 9>,
               groov::field<"af1_8_3", std::uint8_t, 8, 3>,
               groov::field<"bkcmp2e", common::bit_enable, 2, 2>,
               groov::field<"bkcmp1e", common::bit_enable, 1, 1>,
               groov::field<"bkine", bool, 0, 0>>;

// tim16_af1_v2: AF1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_af1_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 11, common::access::ro>,
               groov::field<"bkcmp1p", bool, 10, 10>,
               groov::field<"bkinp", bool, 9, 9>,
               groov::field<"reserved0", std::uint8_t, 8, 2, common::access::ro>,
               groov::field<"bkcmp1e", common::bit_enable, 1, 1>,
               groov::field<"bkine", bool, 0, 0>>;

// tim16_bdtr_v1: BDTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_bdtr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint8_t, 31, 29, common::access::ro>,
               groov::field<"bkbid", bool, 28, 28>,
               groov::field<"reserved1", bool, 27, 27, common::access::ro>,
               groov::field<"bkdsrm", bool, 26, 26>,
               groov::field<"reserved0", std::uint16_t, 25, 16, common::access::ro>,
               groov::field<"moe", bool, 15, 15>,
               groov::field<"aoe", bool, 14, 14>,
               groov::field<"bkp", bool, 13, 13>,
               groov::field<"bke", bool, 12, 12>,
               groov::field<"ossr", bool, 11, 11>,
               groov::field<"ossi", bool, 10, 10>,
               groov::field<"lock", std::uint8_t, 9, 8>,
               groov::field<"dtg", std::uint8_t, 7, 0>>;

// tim16_ccmr1_v1: CCMR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_ccmr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"oc1m_3", bool, 16, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"oc1ce", bool, 7, 7>,
               groov::field<"oc1m_2_0", std::uint8_t, 6, 4>,
               groov::field<"oc1pe", common::bit_enable, 3, 3>,
               groov::field<"oc1fe", common::bit_enable, 2, 2>,
               groov::field<"cc1s", std::uint8_t, 1, 0>>;

// tim16_ccr1_v1: CCR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_ccr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ccr", std::uint16_t, 15, 0>>;

// tim16_cr1_v1: CR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_cr1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 12, common::access::ro>,
               groov::field<"uif_remap", bool, 11, 11>,
               groov::field<"reserved1", bool, 10, 10, common::access::ro>,
               groov::field<"ckd", std::uint8_t, 9, 8>,
               groov::field<"arpe", common::bit_enable, 7, 7>,
               groov::field<"reserved0", std::uint8_t, 6, 4, common::access::ro>,
               groov::field<"opm", bool, 3, 3>,
               groov::field<"urs", bool, 2, 2>,
               groov::field<"udis", common::bit_nenable, 1, 1>,
               groov::field<"cen", common::bit_enable, 0, 0>>;

// tim16_cr2_v1: CR2
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_cr2_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 10, common::access::ro>,
               groov::field<"ois1n", bool, 9, 9>,
               groov::field<"ois1", bool, 8, 8>,
               groov::field<"ti1s", bool, 7, 7>,
               groov::field<"mms", std::uint8_t, 6, 4>,
               groov::field<"ccds", bool, 3, 3>,
               groov::field<"ccus", bool, 2, 2>,
               groov::field<"reserved0", bool, 1, 1, common::access::ro>,
               groov::field<"ccpc", bool, 0, 0>>;

// tim16_dier_v1: DIER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_dier_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved4", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bde", common::bit_enable, 15, 15>,
               groov::field<"reserved3", bool, 14, 14, common::access::ro>,
               groov::field<"ccude", common::bit_enable, 13, 13>,
               groov::field<"reserved2", std::uint8_t, 12, 10, common::access::ro>,
               groov::field<"cc1de", common::bit_enable, 9, 9>,
               groov::field<"ude", common::bit_enable, 8, 8>,
               groov::field<"bie", common::bit_enable, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"comie", common::bit_enable, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1ie", common::bit_enable, 1, 1>,
               groov::field<"uie", common::bit_enable, 0, 0>>;

// tim16_dier_v2: DIER
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_dier_v2_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"bde", common::bit_enable, 15, 15>,
               groov::field<"tde", common::bit_enable, 14, 14>,
               groov::field<"ccude", common::bit_enable, 13, 13>,
               groov::field<"reserved1", std::uint8_t, 12, 10, common::access::ro>,
               groov::field<"cc1de", common::bit_enable, 9, 9>,
               groov::field<"ude", common::bit_enable, 8, 8>,
               groov::field<"bie", common::bit_enable, 7, 7>,
               groov::field<"tie", common::bit_enable, 6, 6>,
               groov::field<"comie", common::bit_enable, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1ie", common::bit_enable, 1, 1>,
               groov::field<"uie", common::bit_enable, 0, 0>>;

// tim16_egr_v1: EGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_egr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"bg", bool, 7, 7, common::access::wo>,
               groov::field<"tg", bool, 6, 6, common::access::wo>,
               groov::field<"comg", bool, 5, 5, common::access::wo>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1g", bool, 1, 1, common::access::wo>,
               groov::field<"ug", bool, 0, 0, common::access::wo>>;

// tim16_or1_v1: OR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_or1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, common::access::ro>,
               groov::field<"ti1_rmp", std::uint8_t, 2, 1>,
               groov::field<"or1_0", bool, 0, 0>>;

// tim16_smcr_v1: SMCR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_smcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 22, common::access::ro>,
               groov::field<"ts_4_3", std::uint8_t, 21, 20>,
               groov::field<"reserved2", std::uint8_t, 19, 17, common::access::ro>,
               groov::field<"sms_3", bool, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 8, common::access::ro>,
               groov::field<"msm", bool, 7, 7>,
               groov::field<"ts_2_0", std::uint8_t, 6, 4>,
               groov::field<"reserved0", bool, 3, 3, common::access::ro>,
               groov::field<"sms_2_0", std::uint8_t, 2, 0>>;

// tim16_sr_v1: SR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_sr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 10, common::access::ro>,
               groov::field<"cc1of", bool, 9, 9>,
               groov::field<"reserved1", bool, 8, 8, common::access::ro>,
               groov::field<"bif", bool, 7, 7>,
               groov::field<"tif", bool, 6, 6>,
               groov::field<"comif", bool, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1if", bool, 1, 1>,
               groov::field<"uif", bool, 0, 0>>;

// tim16_tim16_egr_v1: TIM16_EGR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim16_egr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::wo,
               groov::field<"reserved2", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"bg", bool, 7, 7>,
               groov::field<"reserved1", bool, 6, 6, common::access::ro>,
               groov::field<"comg", bool, 5, 5>,
               groov::field<"reserved0", std::uint8_t, 4, 2, common::access::ro>,
               groov::field<"cc1g", bool, 1, 1>,
               groov::field<"ug", bool, 0, 0>>;

// tim16_tim16_or1_v1: TIM16_OR1
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using tim16_tim16_or1_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 2, common::access::ro>,
               groov::field<"hse32en", common::bit_enable, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, common::access::ro>>;

} // namespace mcu::stm32::regs
