/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include "../access.hpp"
#include "../bittypes.hpp"

namespace mcu::stm32::regs {

// usb_fs_daddr_v1: DADDR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usb_fs_daddr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 8, common::access::ro>,
               groov::field<"ef", bool, 7, 7>,
               groov::field<"add6", bool, 6, 6>,
               groov::field<"add5", bool, 5, 5>,
               groov::field<"add4", bool, 4, 4>,
               groov::field<"add3", bool, 3, 3>,
               groov::field<"add2", bool, 2, 2>,
               groov::field<"add1", bool, 1, 1>,
               groov::field<"add", bool, 0, 0>>;

// usb_fs_istr_v1: ISTR
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usb_fs_istr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ctr", bool, 15, 15, common::access::ro>,
               groov::field<"pmaovr", bool, 14, 14>,
               groov::field<"err", bool, 13, 13>,
               groov::field<"wkup", bool, 12, 12>,
               groov::field<"susp", bool, 11, 11>,
               groov::field<"reset", bool, 10, 10>,
               groov::field<"sof", bool, 9, 9>,
               groov::field<"esof", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 5, common::access::ro>,
               groov::field<"dir", bool, 4, 4, common::access::ro>,
               groov::field<"ep_id", std::uint8_t, 3, 0, common::access::ro>>;

// usb_fs_usb_ep0r_v1: USB_EP0R
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using usb_fs_usb_ep0r_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, common::access::ro>,
               groov::field<"ctr_rx", bool, 15, 15>,
               groov::field<"dtog_rx", bool, 14, 14>,
               groov::field<"stat_rx", std::uint8_t, 13, 12>,
               groov::field<"setup", bool, 11, 11, common::access::ro>,
               groov::field<"ep_type", std::uint8_t, 10, 9>,
               groov::field<"ep_kind", bool, 8, 8>,
               groov::field<"ctr_tx", bool, 7, 7>,
               groov::field<"dtog_tx", bool, 6, 6>,
               groov::field<"stat_tx", std::uint8_t, 5, 4>,
               groov::field<"ea", std::uint8_t, 3, 0>>;

} // namespace mcu::stm32::regs
