/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dac.hpp"
namespace mcu::stm32::stm32f3x4 {
#include "../../../common/peripherals/dac_028ceb0ad477.inc"
} // namespace mcu::stm32::stm32f3x4
