/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dbgmcu.hpp"
namespace erworks::stm32::stm32l053 {
#include "../../../common/peripherals/dbgmcu_ebd1e172d0ad.inc"
} // namespace erworks::stm32::stm32l053
