/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32::regs {

// stk_calib_v1: CALIB
// Used by: STK
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using stk_calib_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"tenms", std::uint32_t, 23, 0>>;

// stk_ctrl_v1: CTRL
// Used by: STK
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using stk_ctrl_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 17, common::access::ro>,
               groov::field<"countflag", bool, 16, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 3, common::access::ro>,
               groov::field<"clksource", bool, 2, 2>,
               groov::field<"tickint", bool, 1, 1>,
               groov::field<"enable", bool, 0, 0>>;

// stk_load__v1: LOAD_
// Used by: STK
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using stk_load__v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"reload", std::uint32_t, 23, 0>>;

// stk_val_v1: VAL
// Used by: STK
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using stk_val_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             common::access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 24, common::access::ro>,
               groov::field<"current", std::uint32_t, 23, 0>>;

} // namespace stm32::regs
