/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/comp.hpp"
namespace mcu::stm32::stm32wb55_cm0p {
#include "../../common/peripherals/comp_e119fd8cfb71.inc"
} // namespace mcu::stm32::stm32wb55_cm0p
