/* File autogenerated with svd2groov for stm32l412 */
#pragma once

#include <stm32/config.hpp>
#include <stm32/stm32l412/peripherals/adc.hpp>
#include <stm32/stm32l412/peripherals/comp.hpp>
#include <stm32/stm32l412/peripherals/crc.hpp>
#include <stm32/stm32l412/peripherals/crs.hpp>
#include <stm32/stm32l412/peripherals/dbgmcu.hpp>
#include <stm32/stm32l412/peripherals/dma.hpp>
#include <stm32/stm32l412/peripherals/exti.hpp>
#include <stm32/stm32l412/peripherals/firewall.hpp>
#include <stm32/stm32l412/peripherals/flash.hpp>
#include <stm32/stm32l412/peripherals/gpio.hpp>
#include <stm32/stm32l412/peripherals/i2c.hpp>
#include <stm32/stm32l412/peripherals/iwdg.hpp>
#include <stm32/stm32l412/peripherals/lptim.hpp>
#include <stm32/stm32l412/peripherals/opamp.hpp>
#include <stm32/stm32l412/peripherals/pwr.hpp>
#include <stm32/stm32l412/peripherals/quadspi.hpp>
#include <stm32/stm32l412/peripherals/rcc.hpp>
#include <stm32/stm32l412/peripherals/rng.hpp>
#include <stm32/stm32l412/peripherals/rtc.hpp>
#include <stm32/stm32l412/peripherals/spi.hpp>
#include <stm32/stm32l412/peripherals/syscfg.hpp>
#include <stm32/stm32l412/peripherals/tim.hpp>
#include <stm32/stm32l412/peripherals/tsc.hpp>
#include <stm32/stm32l412/peripherals/usart.hpp>
#include <stm32/stm32l412/peripherals/usb.hpp>
#include <stm32/stm32l412/peripherals/wwdg.hpp>

#include <stm32/stm32l412/peripherals/addresses.hpp>

namespace stm32::stm32l412 {

namespace detail {
  struct peripheral_disabled {};
} // namespace detail

} // namespace stm32::stm32l412

namespace stm32 {

constexpr auto adc1 = [] consteval {
  if constexpr (stm32l412::config::adc1) {
    return stm32l412::adcx::adcx_t<"adc1",stm32l412::adc1::ADC1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto adc12_common = [] consteval {
  if constexpr (stm32l412::config::adc12_common) {
    return stm32l412::adc12_common::adc12_common_t<stm32l412::adc12_common::ADC12_COMMON_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto adc2 = [] consteval {
  if constexpr (stm32l412::config::adc2) {
    return stm32l412::adcx::adcx_t<"adc2",stm32l412::adc2::ADC2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto comp = [] consteval {
  if constexpr (stm32l412::config::comp) {
    return stm32l412::comp::comp_t<stm32l412::comp::COMP_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto crc = [] consteval {
  if constexpr (stm32l412::config::crc) {
    return stm32l412::crc::crc_t<stm32l412::crc::CRC_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto crs = [] consteval {
  if constexpr (stm32l412::config::crs) {
    return stm32l412::crs::crs_t<stm32l412::crs::CRS_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto dbgmcu = [] consteval {
  if constexpr (stm32l412::config::dbgmcu) {
    return stm32l412::dbgmcu::dbgmcu_t<stm32l412::dbgmcu::DBGMCU_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto dma1 = [] consteval {
  if constexpr (stm32l412::config::dma1) {
    return stm32l412::dmax::dmax_t<"dma1",stm32l412::dma1::DMA1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto dma2 = [] consteval {
  if constexpr (stm32l412::config::dma2) {
    return stm32l412::dmax::dmax_t<"dma2",stm32l412::dma2::DMA2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto exti = [] consteval {
  if constexpr (stm32l412::config::exti) {
    return stm32l412::exti::exti_t<stm32l412::exti::EXTI_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto firewall = [] consteval {
  if constexpr (stm32l412::config::firewall) {
    return stm32l412::firewall::firewall_t<stm32l412::firewall::FIREWALL_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto flash = [] consteval {
  if constexpr (stm32l412::config::flash) {
    return stm32l412::flash::flash_t<stm32l412::flash::FLASH_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto gpioa = [] consteval {
  if constexpr (stm32l412::config::gpioa) {
    return stm32l412::gpioa::gpioa_t<stm32l412::gpioa::GPIOA_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto gpiob = [] consteval {
  if constexpr (stm32l412::config::gpiob) {
    return stm32l412::gpiob::gpiob_t<stm32l412::gpiob::GPIOB_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto gpioc = [] consteval {
  if constexpr (stm32l412::config::gpioc) {
    return stm32l412::gpiox::gpiox_t<"gpioc",stm32l412::gpioc::GPIOC_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto gpiod = [] consteval {
  if constexpr (stm32l412::config::gpiod) {
    return stm32l412::gpiox::gpiox_t<"gpiod",stm32l412::gpiod::GPIOD_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto gpioh = [] consteval {
  if constexpr (stm32l412::config::gpioh) {
    return stm32l412::gpioh::gpioh_t<stm32l412::gpioh::GPIOH_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto i2c1 = [] consteval {
  if constexpr (stm32l412::config::i2c1) {
    return stm32l412::i2cx::i2cx_t<"i2c1",stm32l412::i2c1::I2C1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto i2c2 = [] consteval {
  if constexpr (stm32l412::config::i2c2) {
    return stm32l412::i2cx::i2cx_t<"i2c2",stm32l412::i2c2::I2C2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto i2c3 = [] consteval {
  if constexpr (stm32l412::config::i2c3) {
    return stm32l412::i2cx::i2cx_t<"i2c3",stm32l412::i2c3::I2C3_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto iwdg = [] consteval {
  if constexpr (stm32l412::config::iwdg) {
    return stm32l412::iwdg::iwdg_t<stm32l412::iwdg::IWDG_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto lptim1 = [] consteval {
  if constexpr (stm32l412::config::lptim1) {
    return stm32l412::lptimx::lptimx_t<"lptim1",stm32l412::lptim1::LPTIM1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto lptim2 = [] consteval {
  if constexpr (stm32l412::config::lptim2) {
    return stm32l412::lptimx::lptimx_t<"lptim2",stm32l412::lptim2::LPTIM2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto lpuart1 = [] consteval {
  if constexpr (stm32l412::config::lpuart1) {
    return stm32l412::lpuart1::lpuart1_t<stm32l412::lpuart1::LPUART1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto opamp = [] consteval {
  if constexpr (stm32l412::config::opamp) {
    return stm32l412::opamp::opamp_t<stm32l412::opamp::OPAMP_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto pwr = [] consteval {
  if constexpr (stm32l412::config::pwr) {
    return stm32l412::pwr::pwr_t<stm32l412::pwr::PWR_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto quadspi = [] consteval {
  if constexpr (stm32l412::config::quadspi) {
    return stm32l412::quadspi::quadspi_t<stm32l412::quadspi::QUADSPI_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto rcc = [] consteval {
  if constexpr (stm32l412::config::rcc) {
    return stm32l412::rcc::rcc_t<stm32l412::rcc::RCC_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto rng = [] consteval {
  if constexpr (stm32l412::config::rng) {
    return stm32l412::rng::rng_t<stm32l412::rng::RNG_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto rtc = [] consteval {
  if constexpr (stm32l412::config::rtc) {
    return stm32l412::rtc::rtc_t<stm32l412::rtc::RTC_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto spi1 = [] consteval {
  if constexpr (stm32l412::config::spi1) {
    return stm32l412::spix::spix_t<"spi1",stm32l412::spi1::SPI1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto spi2 = [] consteval {
  if constexpr (stm32l412::config::spi2) {
    return stm32l412::spix::spix_t<"spi2",stm32l412::spi2::SPI2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto syscfg = [] consteval {
  if constexpr (stm32l412::config::syscfg) {
    return stm32l412::syscfg::syscfg_t<stm32l412::syscfg::SYSCFG_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tim1 = [] consteval {
  if constexpr (stm32l412::config::tim1) {
    return stm32l412::tim1::tim1_t<stm32l412::tim1::TIM1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tim15 = [] consteval {
  if constexpr (stm32l412::config::tim15) {
    return stm32l412::tim15::tim15_t<stm32l412::tim15::TIM15_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tim16 = [] consteval {
  if constexpr (stm32l412::config::tim16) {
    return stm32l412::tim16::tim16_t<stm32l412::tim16::TIM16_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tim2 = [] consteval {
  if constexpr (stm32l412::config::tim2) {
    return stm32l412::tim2::tim2_t<stm32l412::tim2::TIM2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tim6 = [] consteval {
  if constexpr (stm32l412::config::tim6) {
    return stm32l412::tim6::tim6_t<stm32l412::tim6::TIM6_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto tsc = [] consteval {
  if constexpr (stm32l412::config::tsc) {
    return stm32l412::tsc::tsc_t<stm32l412::tsc::TSC_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto usart1 = [] consteval {
  if constexpr (stm32l412::config::usart1) {
    return stm32l412::usart1::usart1_t<stm32l412::usart1::USART1_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto usart2 = [] consteval {
  if constexpr (stm32l412::config::usart2) {
    return stm32l412::usartx::usartx_t<"usart2",stm32l412::usart2::USART2_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto usart3 = [] consteval {
  if constexpr (stm32l412::config::usart3) {
    return stm32l412::usartx::usartx_t<"usart3",stm32l412::usart3::USART3_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto usb_fs = [] consteval {
  if constexpr (stm32l412::config::usb_fs) {
    return stm32l412::usbx::usbx_t<"usb_fs",stm32l412::usb_fs::USB_FS_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto usb_sram = [] consteval {
  if constexpr (stm32l412::config::usb_sram) {
    return stm32l412::usbx::usbx_t<"usb_sram",stm32l412::usb_sram::USB_SRAM_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

constexpr auto wwdg = [] consteval {
  if constexpr (stm32l412::config::wwdg) {
    return stm32l412::wwdg::wwdg_t<stm32l412::wwdg::WWDG_BASE>{};
  } else {
    return stm32l412::detail::peripheral_disabled{};
  }
}();

} // namespace stm32
