/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/exti.hpp"
namespace erworks::stm32::stm32l0x0 {
#include "../../../common/peripherals/exti_972af6b83f0a.inc"
} // namespace erworks::stm32::stm32l0x0
