/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/tamp.hpp"
namespace mcu::stm32::stm32h5e5 {
#include "../../../common/peripherals/tamp_a08a0b7bdc8d.inc"
} // namespace mcu::stm32::stm32h5e5
