/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/tsc.hpp"
namespace mcu::stm32::stm32l562 {
#include "../../../common/peripherals/tsc_993a680aef8c.inc"
} // namespace mcu::stm32::stm32l562
