/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/adc.hpp"
namespace mcu::stm32::stm32wb35_cm4 {
#include "../../../common/peripherals/adc_49581a10b5d1.inc"
} // namespace mcu::stm32::stm32wb35_cm4
