/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/syscfg.hpp"
namespace mcu::stm32::stm32g061 {
#include "../../common/peripherals/syscfg_5a6bb309141c.inc"
} // namespace mcu::stm32::stm32g061
