/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../common/registers/rcc.hpp"
namespace mcu::stm32::stm32g441 {
#include "../../common/peripherals/rcc_f2e5321b3fae.inc"
} // namespace mcu::stm32::stm32g441
