/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/rcc.hpp"
namespace mcu::stm32::stm32h5f5 {
#include "../../../common/peripherals/rcc_f3e8970db346.inc"
} // namespace mcu::stm32::stm32h5f5
