/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32gbk1cbt6/registers/comp.hpp>

namespace stm32::stm32gbk1cbt6 {

namespace comp {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using comp_c1csr_tt = regs::comp_comp_c1csr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using comp_c2csr_tt = regs::comp_comp_c2csr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using comp_c3csr_tt = regs::comp_comp_c3csr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using comp_c4csr_tt = regs::comp_comp_c4csr_v1_tt<name, baseaddress, offset>;

  template <std::uint32_t baseaddress>
  using comp_t =
    groov::group<"comp",
                 groov::mmio_bus<>,
                 comp_c1csr_tt<"comp_c1csr", baseaddress, 0x0>,
                 comp_c2csr_tt<"comp_c2csr", baseaddress, 0x4>,
                 comp_c3csr_tt<"comp_c3csr", baseaddress, 0x8>,
                 comp_c4csr_tt<"comp_c4csr", baseaddress, 0xc>>;

} // namespace comp

} // namespace stm32::stm32gbk1cbt6
