/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/dma.hpp"
namespace mcu::stm32::stm32g473 {
#include "../../../common/peripherals/dma_eeea91ce6be8.inc"
} // namespace mcu::stm32::stm32g473
