/* File autogenerated with svd2groov */
#pragma once
#include <groov/groov.hpp>
#include "../../../common/registers/flash.hpp"
namespace erworks::stm32::stm32c031 {
#include "../../../common/peripherals/flash_6ac108087ea7.inc"
} // namespace erworks::stm32::stm32c031
