/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32h5f5/registers/gtzc1_mpcbb1.hpp>

namespace stm32::stm32h5f5 {

namespace gtzc1_mpcbb1x {
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_cr_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_cr_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_cfglock1_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_cfglock1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr0_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr1_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr2_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr3_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr4_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr4_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr5_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr5_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr6_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr6_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr7_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr7_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr8_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr8_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr9_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr9_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr10_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr10_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr11_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr11_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr12_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr12_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr13_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr13_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr14_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr14_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr15_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr15_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr16_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr16_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr17_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr17_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr18_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr18_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr19_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr19_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr20_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr20_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr21_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr21_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr22_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr22_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr23_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr23_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr24_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr24_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr25_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr25_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr26_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr26_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr27_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr27_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr28_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr28_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr29_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr29_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr30_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr30_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_seccfgr31_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_seccfgr31_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr0_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr0_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr1_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr1_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr2_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr2_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr3_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr3_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr4_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr4_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr5_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr5_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr6_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr6_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr7_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr7_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr8_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr8_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr9_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr9_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr10_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr10_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr11_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr11_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr12_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr12_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr13_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr13_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr14_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr14_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr15_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr15_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr16_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr16_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr17_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr17_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr18_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr18_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr19_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr19_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr20_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr20_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr21_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr21_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr22_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr22_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr23_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr23_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr24_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr24_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr25_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr25_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr26_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr26_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr27_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr27_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr28_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr28_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr29_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr29_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr30_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr30_v1_tt<name, baseaddress, offset>;
  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using gtzc1_mpcbb1_privcfgr31_tt = regs::gtzc1_mpcbb1_gtzc1_mpcbb1_privcfgr31_v1_tt<name, baseaddress, offset>;

  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gtzc1_mpcbb1x_t =
    groov::group<name,
                 groov::mmio_bus<>,
                 gtzc1_mpcbb1_cr_tt<"gtzc1_mpcbb1_cr", baseaddress, 0x0>,
                 gtzc1_mpcbb1_cfglock1_tt<"gtzc1_mpcbb1_cfglock1", baseaddress, 0x10>,
                 gtzc1_mpcbb1_seccfgr0_tt<"gtzc1_mpcbb1_seccfgr0", baseaddress, 0x100>,
                 gtzc1_mpcbb1_seccfgr1_tt<"gtzc1_mpcbb1_seccfgr1", baseaddress, 0x104>,
                 gtzc1_mpcbb1_seccfgr2_tt<"gtzc1_mpcbb1_seccfgr2", baseaddress, 0x108>,
                 gtzc1_mpcbb1_seccfgr3_tt<"gtzc1_mpcbb1_seccfgr3", baseaddress, 0x10c>,
                 gtzc1_mpcbb1_seccfgr4_tt<"gtzc1_mpcbb1_seccfgr4", baseaddress, 0x110>,
                 gtzc1_mpcbb1_seccfgr5_tt<"gtzc1_mpcbb1_seccfgr5", baseaddress, 0x114>,
                 gtzc1_mpcbb1_seccfgr6_tt<"gtzc1_mpcbb1_seccfgr6", baseaddress, 0x118>,
                 gtzc1_mpcbb1_seccfgr7_tt<"gtzc1_mpcbb1_seccfgr7", baseaddress, 0x11c>,
                 gtzc1_mpcbb1_seccfgr8_tt<"gtzc1_mpcbb1_seccfgr8", baseaddress, 0x120>,
                 gtzc1_mpcbb1_seccfgr9_tt<"gtzc1_mpcbb1_seccfgr9", baseaddress, 0x124>,
                 gtzc1_mpcbb1_seccfgr10_tt<"gtzc1_mpcbb1_seccfgr10", baseaddress, 0x128>,
                 gtzc1_mpcbb1_seccfgr11_tt<"gtzc1_mpcbb1_seccfgr11", baseaddress, 0x12c>,
                 gtzc1_mpcbb1_seccfgr12_tt<"gtzc1_mpcbb1_seccfgr12", baseaddress, 0x130>,
                 gtzc1_mpcbb1_seccfgr13_tt<"gtzc1_mpcbb1_seccfgr13", baseaddress, 0x134>,
                 gtzc1_mpcbb1_seccfgr14_tt<"gtzc1_mpcbb1_seccfgr14", baseaddress, 0x138>,
                 gtzc1_mpcbb1_seccfgr15_tt<"gtzc1_mpcbb1_seccfgr15", baseaddress, 0x13c>,
                 gtzc1_mpcbb1_seccfgr16_tt<"gtzc1_mpcbb1_seccfgr16", baseaddress, 0x140>,
                 gtzc1_mpcbb1_seccfgr17_tt<"gtzc1_mpcbb1_seccfgr17", baseaddress, 0x144>,
                 gtzc1_mpcbb1_seccfgr18_tt<"gtzc1_mpcbb1_seccfgr18", baseaddress, 0x148>,
                 gtzc1_mpcbb1_seccfgr19_tt<"gtzc1_mpcbb1_seccfgr19", baseaddress, 0x14c>,
                 gtzc1_mpcbb1_seccfgr20_tt<"gtzc1_mpcbb1_seccfgr20", baseaddress, 0x150>,
                 gtzc1_mpcbb1_seccfgr21_tt<"gtzc1_mpcbb1_seccfgr21", baseaddress, 0x154>,
                 gtzc1_mpcbb1_seccfgr22_tt<"gtzc1_mpcbb1_seccfgr22", baseaddress, 0x158>,
                 gtzc1_mpcbb1_seccfgr23_tt<"gtzc1_mpcbb1_seccfgr23", baseaddress, 0x15c>,
                 gtzc1_mpcbb1_seccfgr24_tt<"gtzc1_mpcbb1_seccfgr24", baseaddress, 0x160>,
                 gtzc1_mpcbb1_seccfgr25_tt<"gtzc1_mpcbb1_seccfgr25", baseaddress, 0x164>,
                 gtzc1_mpcbb1_seccfgr26_tt<"gtzc1_mpcbb1_seccfgr26", baseaddress, 0x168>,
                 gtzc1_mpcbb1_seccfgr27_tt<"gtzc1_mpcbb1_seccfgr27", baseaddress, 0x16c>,
                 gtzc1_mpcbb1_seccfgr28_tt<"gtzc1_mpcbb1_seccfgr28", baseaddress, 0x170>,
                 gtzc1_mpcbb1_seccfgr29_tt<"gtzc1_mpcbb1_seccfgr29", baseaddress, 0x174>,
                 gtzc1_mpcbb1_seccfgr30_tt<"gtzc1_mpcbb1_seccfgr30", baseaddress, 0x178>,
                 gtzc1_mpcbb1_seccfgr31_tt<"gtzc1_mpcbb1_seccfgr31", baseaddress, 0x17c>,
                 gtzc1_mpcbb1_privcfgr0_tt<"gtzc1_mpcbb1_privcfgr0", baseaddress, 0x200>,
                 gtzc1_mpcbb1_privcfgr1_tt<"gtzc1_mpcbb1_privcfgr1", baseaddress, 0x204>,
                 gtzc1_mpcbb1_privcfgr2_tt<"gtzc1_mpcbb1_privcfgr2", baseaddress, 0x208>,
                 gtzc1_mpcbb1_privcfgr3_tt<"gtzc1_mpcbb1_privcfgr3", baseaddress, 0x20c>,
                 gtzc1_mpcbb1_privcfgr4_tt<"gtzc1_mpcbb1_privcfgr4", baseaddress, 0x210>,
                 gtzc1_mpcbb1_privcfgr5_tt<"gtzc1_mpcbb1_privcfgr5", baseaddress, 0x214>,
                 gtzc1_mpcbb1_privcfgr6_tt<"gtzc1_mpcbb1_privcfgr6", baseaddress, 0x218>,
                 gtzc1_mpcbb1_privcfgr7_tt<"gtzc1_mpcbb1_privcfgr7", baseaddress, 0x21c>,
                 gtzc1_mpcbb1_privcfgr8_tt<"gtzc1_mpcbb1_privcfgr8", baseaddress, 0x220>,
                 gtzc1_mpcbb1_privcfgr9_tt<"gtzc1_mpcbb1_privcfgr9", baseaddress, 0x224>,
                 gtzc1_mpcbb1_privcfgr10_tt<"gtzc1_mpcbb1_privcfgr10", baseaddress, 0x228>,
                 gtzc1_mpcbb1_privcfgr11_tt<"gtzc1_mpcbb1_privcfgr11", baseaddress, 0x22c>,
                 gtzc1_mpcbb1_privcfgr12_tt<"gtzc1_mpcbb1_privcfgr12", baseaddress, 0x230>,
                 gtzc1_mpcbb1_privcfgr13_tt<"gtzc1_mpcbb1_privcfgr13", baseaddress, 0x234>,
                 gtzc1_mpcbb1_privcfgr14_tt<"gtzc1_mpcbb1_privcfgr14", baseaddress, 0x238>,
                 gtzc1_mpcbb1_privcfgr15_tt<"gtzc1_mpcbb1_privcfgr15", baseaddress, 0x23c>,
                 gtzc1_mpcbb1_privcfgr16_tt<"gtzc1_mpcbb1_privcfgr16", baseaddress, 0x240>,
                 gtzc1_mpcbb1_privcfgr17_tt<"gtzc1_mpcbb1_privcfgr17", baseaddress, 0x244>,
                 gtzc1_mpcbb1_privcfgr18_tt<"gtzc1_mpcbb1_privcfgr18", baseaddress, 0x248>,
                 gtzc1_mpcbb1_privcfgr19_tt<"gtzc1_mpcbb1_privcfgr19", baseaddress, 0x24c>,
                 gtzc1_mpcbb1_privcfgr20_tt<"gtzc1_mpcbb1_privcfgr20", baseaddress, 0x250>,
                 gtzc1_mpcbb1_privcfgr21_tt<"gtzc1_mpcbb1_privcfgr21", baseaddress, 0x254>,
                 gtzc1_mpcbb1_privcfgr22_tt<"gtzc1_mpcbb1_privcfgr22", baseaddress, 0x258>,
                 gtzc1_mpcbb1_privcfgr23_tt<"gtzc1_mpcbb1_privcfgr23", baseaddress, 0x25c>,
                 gtzc1_mpcbb1_privcfgr24_tt<"gtzc1_mpcbb1_privcfgr24", baseaddress, 0x260>,
                 gtzc1_mpcbb1_privcfgr25_tt<"gtzc1_mpcbb1_privcfgr25", baseaddress, 0x264>,
                 gtzc1_mpcbb1_privcfgr26_tt<"gtzc1_mpcbb1_privcfgr26", baseaddress, 0x268>,
                 gtzc1_mpcbb1_privcfgr27_tt<"gtzc1_mpcbb1_privcfgr27", baseaddress, 0x26c>,
                 gtzc1_mpcbb1_privcfgr28_tt<"gtzc1_mpcbb1_privcfgr28", baseaddress, 0x270>,
                 gtzc1_mpcbb1_privcfgr29_tt<"gtzc1_mpcbb1_privcfgr29", baseaddress, 0x274>,
                 gtzc1_mpcbb1_privcfgr30_tt<"gtzc1_mpcbb1_privcfgr30", baseaddress, 0x278>,
                 gtzc1_mpcbb1_privcfgr31_tt<"gtzc1_mpcbb1_privcfgr31", baseaddress, 0x27c>>;

} // namespace gtzc1_mpcbb1x

} // namespace stm32::stm32h5f5
